docker/buildx

- .dockerignore
- Makefile
- hack/cross
> hack: add cross target

- .travis.yml
- Dockerfile
- Makefile
- hack/dockerfiles/lint.Dockerfile
> add travis

- hack/demo-env/entrypoint.sh
- hack/shell
> hack: make tmux optional for shell

- .travis.yml
> travis: temporarily only build for linux/amd64 and darwin/amd64

- .gitignore
- Dockerfile
- Makefile
- hack/test
> hack: add test target

- build/output.go
> fix and improve outputs parsing

- commands/build.go
> commands: add missing flags as hidden in build

- commands/build.go
> build: do not error out if --network is default

- build/build.go
- commands/build.go
- commands/inspect.go
- commands/util.go
- driver/driver.go
- util/progress/fromreader.go
- util/progress/reset.go
- vendor/modules.txt
> build: add docker output for non-moby drivers

- commands/rm.go
> rm: remove builder even if driver is not responsive

- bake/bake.go
- build/build.go
- build/cache.go
- commands/build.go
> build: add cache-from and cache-to support

- commands/create.go
- commands/use.go
commands: check current context when switching to default
commands: avoid creating instance from tls environment
fixes #30
> commands: environment detection validation

- commands/util.go
> commands: fix using ssh endpoint directly

- commands/util.go
> Negotiate API versions to allow talking with older docker daemons

- Dockerfile
- hack/shell
> Make it easier to use ssh inside demo env

- Dockerfile
> dockerfile: add release target

- commands/root.go
- commands/version.go
> commands: add version command

- Dockerfile
> dockerfile: set binaries target as default

- .travis.yml
- hack/release
> add releases to travis

- README.md
> readme: better title formatting

- bake/compose.go
- bake/compose_test.go
> bake: fix parsing target from compose files

- README.md
> readme: more guide content

- README.md
Signed-off-by: Bin Du <bindu@microsoft.com>
> fix the typo in --cache-to example

- README.md
> Add Linux Nightly Docker install instructions

- Dockerfile
> dockerfile: update to 1.1

- Dockerfile
`buildx install` is now supported in beta3
> dockerfile: unfork cli

- util/imagetools/create.go
Keep arm variant if one is defined in the config.
@dmcgowan 
> imagetools: keep arm variant

- util/progress/printer.go
> progress: add env config

- util/platformutil/parse.go
> platformutil: add local platform

- commands/build.go
> build: add missing flags

- bake/bake.go
- vendor/modules.txt
> bake: make dockerfile relative to context

- README.md
> Update README to use --platform=local with Docker 19.03

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .mailmap
- AUTHORS
- LICENSE
- MAINTAINERS
- Makefile
- README.md
- hack/generate-authors
> Add project files (LICENSE, AUTHORS, MAINTAINERS, Code of Conduct, CONTRIBUTING)

- README.md
> Fix Dockerfile format

- bake/compose.go
> bake: replace env in compose files

- bake/compose.go
- commands/build.go
> build: load default build args from env

- bake/bake.go
- commands/bake.go
> bake: honor --no-cache and --pull

- commands/create.go
- commands/util.go
- driver/docker-container/driver.go
- driver/docker/factory.go
- driver/manager.go
- store/nodegroup.go
- store/nodegroup_test.go
> driver: allow setting buildkit config file

- build/build.go
- build/entitlements.go
- commands/build.go
- vendor/modules.txt
> build: add allowed entitlements

- build/build.go
> build: use correct in-memory input

- build/build.go
> build: fix stdin dockerfile filename

- build/build.go
> build: fix scoping issue in closure inside loop

- bake/bake.go
- bake/bake_test.go
This works just like the `build` command where if you have `--build-arg
FOO`, it will read the variable from env and only set a value if the
variable is defined.
> Support reading from env on bake --set <t>.args

- driver/docker-container/driver.go
When booting `docker-container` driver, it will pull and run image `moby/buildkit:buildx-stable-1`.
If current node cannot connect to dockerhub, driver `docker-container` will always booting failure.
But user may already load the image manually or pull it from a priviate registry.
Buildx should check local docker image store after pull failed.
Fixes: #199 issuecomment-561996661
Signed-off-by: Lu Jingxiao <lujingxiao@huawei.com>
> docker-container: check local image store if pulling image failed

- README.md
i saw there is no available kubernetes driver in documentation but in driver-opts section there is , so i added it to drivers section  too.
> i added kubernetes driver information to drivers section

- go.mod
- go.sum
- vendor/github.com/moby/buildkit/client/solve.go
- vendor/modules.txt
> vendor: update buildkit to v0.7.0

- cmd/buildx/main.go
- vendor/github.com/containerd/containerd/pkg/seed/seed.go
- vendor/github.com/containerd/containerd/pkg/seed/seed_linux.go
- vendor/github.com/containerd/containerd/pkg/seed/seed_other.go
- vendor/modules.txt
> cmd: seed math rand

- build/build.go
> build: improve error checking on load

- build/build.go
docker/for-win#4991
I encount this error message, but I can not understand it.
So, I fix it.
I recreate PR from #352 to fix sign.
Signed-off-by: Kotaro Adachi <k33asby@gmail.com>
> build: fix error message for --push option 

- .travis.yml
This should help with the "connecting to buildkit container" issues seen in CI for #370 fyi @morlay 
> travis: update base image

- hack/binaries
- hack/update-vendor
Follow-up https://github.com/docker/buildx/pull/463#discussion_r536489840
> Update vendor and binaries script

- Dockerfile
> update Dockerfile to v1.2

- build/secrets.go
> Allow secrets with env

- Dockerfile
> Dockerfile: add darwin/arm64 support

- .github/workflows/build.yml
> ci: enable building darwin/arm64 in CI

- go.mod
- go.sum
- vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md
- vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go
- vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression_template.go
- vendor/modules.txt
Looks like some important bugfixes.
> vendor: update hcl

- README.md
- docs/reference/buildx_build.md
- docs/reference/buildx_create.md
- docs/reference/buildx_imagetools_create.md
- docs/reference/buildx_inspect.md
addressing review comments from https://github.com/docker/docker.github.io/pull/12092
> docs: address some review comments from the docs repository

- bake/bake.go
- build/build.go
- commands/build.go
- util/buildflags/cache.go
- util/buildflags/entitlements.go
- util/buildflags/output.go
- util/buildflags/secrets.go
- util/buildflags/ssh.go
Planned to be imported by nerdctl in future.
> build: split buildflags package

- README.md
> note that buildx not in all distros

- .github/workflows/build.yml
- hack/cross
> enable linux/riscv64 builds

- store/store.go
> Use `ioutils.AtomicWriteFile` from moby

- driver/docker-container/driver.go
> don't error on deleting old build containers without state volume

- bake/compose.go
- bake/compose_test.go
- go.mod
- go.sum
- vendor/github.com/compose-spec/compose-go/loader/loader.go
- vendor/github.com/compose-spec/compose-go/template/template.go
- vendor/github.com/compose-spec/compose-go/types/config.go
- vendor/modules.txt
> Set `ConfigFile` to parse compose files with bake

- docs/reference/buildx_bake.md
Follow-up #532 #538 #539 #541 #575 #671
> Update bake docs

- .github/workflows/build.yml
- hack/release
> Create checksums for artifacts

- README.md
- docs/reference/buildx_create.md
Readme enhanced and also wrapped to 80-chars.
> Enhance readme

- Dockerfile
- hack/dockerfiles/docs.Dockerfile
- hack/dockerfiles/lint.Dockerfile
- hack/dockerfiles/vendor.Dockerfile
> Update Dockerfile references to use 1.3

- bake/remote.go
- build/build.go
- build/url.go
- commands/inspect.go
- driver/driver.go
pick #741
(cherry picked from commit 422ba60b046f0b2991ab51958e79b65ce472d9e8)
> [v0.6] use long-running context for client initialization

- .github/workflows/build.yml
- .github/workflows/validate.yml
> github: fix running ci in version branches

- commands/build.go
- docs/reference/buildx_build.md
- docs/reference/docker_buildx_build.yaml
- go.mod
- go.sum
- vendor/github.com/docker/cli-docs-tool/clidocstool_md.go
- vendor/github.com/docker/cli-docs-tool/go.mod
- vendor/github.com/docker/cli-docs-tool/go.sum
- vendor/modules.txt
Closes #735
Closes https://github.com/docker/build-push-action/pull/428
Follow-up https://github.com/docker/cli-docs-tool/pull/8
> Fix flags usage markdown output

- hack/test-driver
> Driver opt not used in e2e tests

- commands/bake.go
- commands/build.go
- commands/create.go
- commands/prune.go
- docs/generate.go
- docs/reference/buildx_bake.md
- docs/reference/buildx_build.md
- docs/reference/buildx_create.md
- docs/reference/buildx_prune.md
- driver/manager.go
Also render value as code for other flags in markdown.
> Fix --driver flag usage markdown output

- bake/bake.go
- bake/bake_test.go
This broke with #773. The added test works with pre-#773 as well
For array fields, overrides are merged together
but override is not merged with the target. If merging
with the target is desired we can add support for
overrides with += operator in the future.
> bake: restore previous override merge behavior

- Dockerfile
- docker-bake.hcl
- hack/dockerfiles/docs.Dockerfile
- hack/dockerfiles/lint.Dockerfile
- hack/dockerfiles/vendor.Dockerfile
* https://github.com/golang/go/issues?q=milestone%3AGo1.17.1+label%3ACherryPickApproved
* https://github.com/golang/go/issues?q=milestone%3AGo1.17.2+label%3ACherryPickApproved
> update go to 1.17.2

- Dockerfile
> dockerfile: update xx to 1.0.0

- commands/build.go
- commands/util.go
> commands: clean up unnecessary code

- bake/bake.go
- bake/bake_test.go
- commands/bake.go
- docs/reference/buildx_bake.md
> [v0.7 backport] bake: fix print output

- util/imagetools/inspect.go
ref https://github.com/containerd/containerd/pull/3400
> imagetools resolver: fix deprecated client opt

- util/imagetools/inspect.go
Discard containerd logger in imagetools resolver to avoid printing unnecessary info during image reference resolution:
```console
$ docker buildx imagetools inspect alpinefoo
INFO[0001] trying next host                              error="pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" host=registry-1.docker.io
error: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```
now:
```console
$ docker buildx imagetools inspect alpinefoo
error: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```
Signed-off-by: CrazyMax …
> imagetools resolver: discard containerd logger output

- .github/workflows/e2e.yml
- commands/bake.go
- commands/build.go
- hack/test-driver
follow-up https://github.com/moby/buildkit/pull/2610
> build: enhance metadata json output

- bake/bake.go
- bake/compose.go
- build/build.go
- commands/build.go
- docs/reference/buildx_bake.md
- docs/reference/buildx_build.md
Allows specifying the `no-cache` per stage. Partially implements https://github.com/moby/buildkit/issues/1213
> build: add no-cache-filter

- docs/reference/buildx.md
- docs/reference/buildx_bake.md
- docs/reference/buildx_build.md
- docs/reference/buildx_create.md
- docs/reference/buildx_du.md
- docs/reference/buildx_imagetools.md
- docs/reference/buildx_imagetools_create.md
- docs/reference/buildx_imagetools_inspect.md
- docs/reference/buildx_inspect.md
- docs/reference/buildx_prune.md
- docs/reference/buildx_rm.md
- docs/reference/buildx_stop.md
- docs/reference/buildx_use.md
- go.mod
- go.sum
- vendor/github.com/docker/cli-docs-tool/annotation/annotation.go
- vendor/github.com/docker/cli-docs-tool/clidocstool_md.go
- vendor/github.com/docker/cli-docs-tool/clidocstool_yaml.go
- vendor/modules.txt
follow-up https://github.com/docker/cli-docs-tool/pull/19
cc @thaJeztah 
> docs: update cli-docs-tool to v0.4.0

- README.md
- commands/build.go
- docs/reference/buildx_bake.md
- docs/reference/buildx_build.md
closes docker/build-push-action#435
> docs: small fixes

- build/build.go
> build: remove target context if platform specific used

- util/progress/multiwriter.go
- util/progress/printer.go
- util/progress/writer.go
> progress: avoid double logs when multiple targets build same step

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/version/version.go
- vendor/github.com/klauspost/compress/README.md
- vendor/github.com/klauspost/compress/huff0/bitreader.go
- vendor/github.com/klauspost/compress/huff0/compress.go
- vendor/github.com/klauspost/compress/huff0/decompress.go
- vendor/github.com/klauspost/compress/huff0/huff0.go
- vendor/github.com/klauspost/compress/zstd/README.md
- vendor/github.com/klauspost/compress/zstd/bitreader.go
- vendor/github.com/klauspost/compress/zstd/blockdec.go
- vendor/github.com/klauspost/compress/zstd/bytebuf.go
- vendor/github.com/klauspost/compress/zstd/decoder.go
- vendor/github.com/klauspost/compress/zstd/decoder_options.go
- vendor/github.com/klauspost/compress/zstd/encoder.go
- vendor/github.com/klauspost/compress/zstd/encoder_options.go
- vendor/github.com/klauspost/compress/zstd/framedec.go
- vendor/github.com/klauspost/compress/zstd/fuzz.go
- vendor/github.com/klauspost/compress/zstd/fuzz_none.go
- vendor/github.com/klauspost/compress/zstd/history.go
- vendor/github.com/klauspost/compress/zstd/seqdec.go
- vendor/github.com/klauspost/compress/zstd/zstd.go
- vendor/github.com/moby/buildkit/client/prune.go
- vendor/github.com/moby/buildkit/client/workers.go
- vendor/github.com/moby/buildkit/cmd/buildkitd/config/config.go
- vendor/github.com/moby/buildkit/exporter/containerimage/exptypes/types.go
- vendor/github.com/moby/buildkit/util/progress/progressui/display.go
- vendor/github.com/moby/buildkit/util/progress/progressui/printer.go
- vendor/modules.txt
Brings in updates for progressui.
> vendor: update buildkit

- go.mod
- go.sum
- util/imagetools/printers.go
- vendor/github.com/moby/buildkit/util/imageutil/buildinfo.go
- vendor/modules.txt
also needs to vendor buildkit v0.10.0.
> imagetools inspect: use buildinfo helper

- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/walker.go
- vendor/modules.txt
Brings in fix for https://github.com/tonistiigi/fsutil/pull/122
> vendor: update fsutil to 9ed61262

- bake/bake.go
- bake/bake_test.go
#1021
(cherry picked from commit 0b8dde1071b92d7600c3459a703a85e3e10e7327)
> [v0.8] bake: fix skipped group when already visited by another one

- commands/root.go
> root: ignore SSH CloseRead warning

- README.md
- docs/generate.go
- docs/reference/buildx_create.md
> Add remote driver documentation

- Dockerfile
- docker-bake.hcl
- hack/dockerfiles/docs.Dockerfile
- hack/dockerfiles/lint.Dockerfile
- hack/dockerfiles/vendor.Dockerfile
> Dockerfile: update dependencies

- hack/release
> release: fix checksum file

- docs/reference/buildx_ls.md
follow-up #998 to reflect latest changes
> docs: update ls output example

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- Dockerfile
- hack/release
> ci: enable cache

- docs/guides/remote-builder.md
> Fix typo in docker-container remote driver instructions

- bake/compose.go
- bake/compose_test.go
> bake: support compose build cache_to

- docs/guides/kubernetes-builder.md
follow-up https://github.com/docker/docker.github.io/pull/14905#issuecomment-1189326265
> docs(guides): fix links

- Dockerfile
> Update xx to 1.1.2

- docs/guides/bake/build-contexts.md
- docs/guides/bake/compose-file.md
- docs/guides/bake/configuring-build.md
- docs/guides/bake/file-definition.md
- docs/guides/bake/hcl-funcs.md
- docs/guides/bake/index.md
- docs/guides/cni-networking.md
- docs/guides/color-output.md
- docs/guides/custom-network.md
- docs/guides/custom-registry-config.md
- docs/guides/kubernetes-builder.md
- docs/guides/opentelemetry.md
- docs/guides/registry-mirror.md
- docs/guides/remote-builder.md
- docs/guides/resource-limiting.md
follow-up https://github.com/moby/buildkit/pull/2970
> docs: remove frontmatter section

- docs/guides/bake/index.md
~needs https://github.com/docker/docker.github.io/pull/15223~
> docs(bake): set experimental note

- docs/guides/drivers/kubernetes.md
follow-up https://github.com/docker/docker.github.io/pull/15262#discussion_r933114216
> docs: fix link to docs website

- build/build.go
Built with fixes from https://github.com/moby/buildkit/pull/3030
> build: update outline fallback image

- go.mod
- go.sum
- vendor/github.com/moby/buildkit/frontend/subrequests/outline/outline.go
- vendor/github.com/moby/buildkit/util/progress/progress.go
- vendor/modules.txt
Brings in fix from https://github.com/moby/buildkit/pull/3030
> vendor: update buildkit to 55ba9d14

- commands/util.go
Caught by @crazy-max in https://github.com/docker/buildx/commit/17d43698666673ec3e94b35d201864e27371f83c#r81522416, thanks :tada:
> Prevent duplicate "failed to find driver" message

- docs/guides/drivers/kubernetes.md
- docs/reference/buildx_bake.md
needs
* docker/docker.github.io#15618
* docker/docker.github.io#15652
> docs: update links to new docs

- docs/guides/drivers/docker-container.md
- docs/guides/drivers/docker.md
- docs/guides/drivers/index.md
- docs/guides/drivers/kubernetes.md
- docs/guides/drivers/remote.md
Updating driver documentation, making editorial and style changes, and aligning with documentation for caching backends.
> Driver docs update

- README.md
- docs/reference/buildx_build.md
> docs: make sure syntax with latest stable dockerfile image is defined

- go.mod
- go.sum
- vendor/github.com/compose-spec/compose-go/dotenv/godotenv.go
- vendor/github.com/compose-spec/compose-go/dotenv/parser.go
- vendor/github.com/compose-spec/compose-go/template/template.go
- vendor/github.com/docker/go-units/size.go
- vendor/modules.txt
https://github.com/compose-spec/compose-go/compare/v1.5.0...v1.6.0
> update github.com/compose-spec/compose-go to v1.6.0

- util/imagetools/create.go
follow-up https://github.com/moby/buildkit/pull/3259
> use double spaces with json marshal indent

- commands/util.go
- driver/kubernetes/context/load.go
> kubernetes: move context config logic to its own pkg

- driver/docker-container/driver.go
- driver/kubernetes/driver.go
Cherry-pick of https://github.com/docker/buildx/pull/1383
> [0.9] driver: don't create tracer delegate opt if tracer is nil

- .github/workflows/build.yml
follow-up https://github.com/docker/buildx/pull/1418#issuecomment-1328992541
> ci: update softprops/action-gh-release to v0.1.15

- hack/hash-files
follow-up https://github.com/docker/buildx/pull/1268#issuecomment-1288488791
> hack: improve hash-files script

- bake/hcl_test.go
- bake/hclparser/hclparser.go
> bake: fix panic for unsupported hcl variable type

- bake/hclparser/expr.go
follow-up https://github.com/docker/buildx/pull/1449#pullrequestreview-1203502702
> hcl: SrcRange not checked when solving JSON func calls

- .github/workflows/build.yml
- .github/workflows/docs-release.yml
- .github/workflows/docs-upstream.yml
- .github/workflows/e2e.yml
- .github/workflows/validate.yml
> ci: fix warnings

- commands/build.go
- docs/reference/buildx_build.md
- relates to https://github.com/docker/docs/pull/16461
- relates to https://github.com/docker/docs/pull/16460
- relates to https://github.com/docker/cli/pull/3525
.
> docs: update anchor links

- docs/reference/buildx.md
- docs/reference/buildx_bake.md
- docs/reference/buildx_build.md
- docs/reference/buildx_create.md
- docs/reference/buildx_du.md
- docs/reference/buildx_imagetools.md
- docs/reference/buildx_imagetools_create.md
- docs/reference/buildx_imagetools_inspect.md
- docs/reference/buildx_inspect.md
- docs/reference/buildx_prune.md
- docs/reference/buildx_rm.md
- docs/reference/buildx_stop.md
- docs/reference/buildx_use.md
- go.mod
- go.sum
- vendor/github.com/docker/cli-docs-tool/README.md
- vendor/github.com/docker/cli-docs-tool/clidocstool_md.go
- vendor/modules.txt
follow-up to https://github.com/docker/buildx/pull/1493
> go.mod: update cli-docs-tool v0.5.1

- .github/workflows/build.yml
- Dockerfile
- go.mod
- go.sum
- vendor/modules.txt
> github: update CI to buildkit v0.11

- .github/workflows/build.yml
- Dockerfile
- docs/reference/buildx_imagetools_inspect.md
- go.mod
- go.sum
- util/imagetools/loader.go
- util/imagetools/printers.go
- vendor/modules.txt
> [v0.10] cherry-picks

- build/build.go
Bug reported by @crazy-max:
> it seems image is not loaded anymore: https://github.com/docker/build-push-action/actions/runs/3892759918/jobs/6644553386#step:5:107
>
> We have importing to docker in the logs but does not look to be imported actually
This occurs when attestations are explicitly requested, and buildkit generates an index - which docker will not import. We should explicitly error in this case, and not allow the user to `--load` an image that contains explicit attestation flags.
> build: error when using docker exporter and attestations

- go.mod
- go.sum
- vendor/github.com/moby/buildkit/session/sshforward/copy.go
- vendor/github.com/moby/buildkit/util/tracing/detect/otlp.go
- vendor/modules.txt
full diff: https://github.com/moby/buildkit/compare/v0.11.0...v0.11.1
> vendor: github.com/moby/buildkit v0.11.1

- build/build.go
:cherries: Cherry-pick of https://github.com/docker/buildx/pull/1511.
> [v0.10] build: error when using docker exporter and attestations

- bake/bake.go
> bake: SOURCE_DATE_EPOCH: fix `panic: assignment to entry in nil map`

- bake/bake.go
- build/build.go
- build/git.go
- builder/node.go
- #1561
- #1564
- #1566
- #1568
> [v0.10] cherry-picks for v0.10.2

- .github/workflows/build.yml
> ci: update buildx and buildkit to latest

- bake/compose.go
- go.mod
- go.sum
- vendor/github.com/compose-spec/compose-go/dotenv/godotenv.go
- vendor/github.com/compose-spec/compose-go/dotenv/parser.go
- vendor/github.com/compose-spec/compose-go/loader/full-example.yml
- vendor/github.com/compose-spec/compose-go/loader/loader.go
- vendor/github.com/compose-spec/compose-go/loader/merge.go
- vendor/github.com/compose-spec/compose-go/loader/normalize.go
- vendor/github.com/compose-spec/compose-go/loader/validate.go
- vendor/github.com/compose-spec/compose-go/schema/compose-spec.json
- vendor/github.com/compose-spec/compose-go/types/project.go
- vendor/github.com/compose-spec/compose-go/types/types.go
- vendor/modules.txt
https://github.com/compose-spec/compose-go/compare/v1.6.0...v1.9.0
> update github.com/compose-spec/compose-go to v1.9.0

- util/gitutil/gitutil.go
- util/gitutil/gitutil_test.go
- util/gitutil/testutil.go
> [v0.10 backport] build: fix git ambiguous argument

- docs/reference/buildx_build.md
Signed-off-by: David Karlsson <david.karlsson@docker.com>
Add a description of the special `--platform=local` value
Closes #1575
> docs: added --platform=local example

- .golangci.yml
- Dockerfile
- bake/bake_test.go
- bake/hcl_test.go
- docker-bake.hcl
- hack/dockerfiles/docs.Dockerfile
- hack/dockerfiles/generated-files.Dockerfile
- hack/dockerfiles/lint.Dockerfile
- hack/dockerfiles/vendor.Dockerfile
Update to Go 1.20 and golangci-lint to 1.51.1 as well.
> update to go 1.20

- build/git.go
- build/git_test.go
partially solves https://github.com/docker/buildx/issues/1623
> build: makes git dirty check opt-in

- docs/reference/buildx_ls.md
follow-up https://github.com/docker/buildx/pull/1552
> docs: update ls command output sample

- bake/bake.go
- bake/remote.go
- driver/remote/driver.go
- go.mod
- go.sum
- vendor/github.com/moby/buildkit/client/client.go
- vendor/github.com/moby/buildkit/frontend/attestations/parse.go
- vendor/github.com/moby/buildkit/frontend/dockerfile/dockerignore/dockerignore.go
- vendor/github.com/moby/buildkit/frontend/dockerui/attr.go
- vendor/github.com/moby/buildkit/frontend/dockerui/build.go
- vendor/github.com/moby/buildkit/frontend/dockerui/config.go
- vendor/github.com/moby/buildkit/frontend/dockerui/context.go
- vendor/github.com/moby/buildkit/frontend/dockerui/namedcontext.go
- vendor/github.com/moby/buildkit/frontend/dockerui/requests.go
- vendor/modules.txt
:arrow_up: Follow-up to https://github.com/moby/buildkit/pull/3769.
See https://github.com/docker/buildx/pull/1710#issuecomment-1494015407:
> We probably also want to update detectGitContext to align with buildkit, but we should do that by exposing that method to be public first (will open a buildkit-side PR to do that).
> Use dockerui context detection

- .github/workflows/build.yml
https://github.com/docker/buildx/actions/runs/4766897080/jobs/8474496621#step:7:129
Will be fixed with https://github.com/docker/buildx/pull/1699.
> ci: fix bin-image job

- driver/docker-container/driver.go
When buildkit container dies with sigkill while the progress is streaming, it could have left the progress hanging.
> container-driver: avoid hanging on container panic

- driver/docker/version.go
- driver/docker/version_test.go
https://gist.github.com/crazy-max/780cb6878c37cb79ec3f7699706cf83f#2304
> driver: update BuildKit version constraint for docker driver

- bake/bake.go
:hammer_and_wrench: Fixes https://github.com/docker/buildx/issues/1738 (can test and confirm with https://github.com/jedevc/bake-test)
Before:
```console
❯ docker buildx bake https://github.com/jedevc/bake-test.git#main foo --progress=plain
#1 [internal] load git source https://github.com/jedevc/bake-test.git#main
#1 0.502 d8471b53d9da6eaabd03504bb41ee1b633b31a90	refs/heads/main
#1 CACHED
#1 [internal] load git source https://github.com/jedevc/bake-test.git#main
#1 0.508 d8471b53d9da6eaabd03504bb41ee1b633b31a90	refs/heads/main
#1 DONE 1.0s
#2 set context to bar
#2 CACHED
#3 [1/1] COPY super-cool.txt /
#3 ERROR: "/super-cool.txt" not found: not found
------
> [1/1] COPY super-cool.txt /:
------
ERROR: failed to solve: failed to compute cache key: "/super-cool.txt" not found: not found
``` …
> bake: copy remote context contents to root

- util/imagetools/create.go
When using imagetools create and combining multiple sources we should check the media type of each manifest and set the right media type for the manifest list.
If there is a mismatch we set OCI index as best effort.
> imagetools(create): set correct media type when combining manifests

- driver/driver.go
follow-up https://github.com/docker/buildx/pull/1846#pullrequestreview-1451837246
> driver: update history api check

- go.mod
- go.sum
- vendor/github.com/compose-spec/compose-go/cli/options.go
- vendor/github.com/compose-spec/compose-go/dotenv/godotenv.go
- vendor/github.com/compose-spec/compose-go/interpolation/interpolation.go
- vendor/github.com/compose-spec/compose-go/loader/full-example.yml
- vendor/github.com/compose-spec/compose-go/loader/interpolate.go
- vendor/github.com/compose-spec/compose-go/loader/loader.go
- vendor/github.com/compose-spec/compose-go/loader/normalize.go
- vendor/github.com/compose-spec/compose-go/loader/null.go
- vendor/github.com/compose-spec/compose-go/loader/volume.go
- vendor/github.com/compose-spec/compose-go/schema/compose-spec.json
- vendor/github.com/compose-spec/compose-go/template/template.go
- vendor/github.com/compose-spec/compose-go/tree/path.go
- vendor/github.com/compose-spec/compose-go/types/project.go
- vendor/github.com/compose-spec/compose-go/types/types.go
- vendor/modules.txt
https://github.com/compose-spec/compose-go/compare/v1.13.4...v1.14.0
> vendor: github.com/compose-spec/compose-go v1.14.0

- tests/bake.go
I went to go and reference a minimal bake integration tests for https://github.com/docker/buildx/pull/1838, only to discover, we don't have one :shrug: 
This PR adds a very minimal bake test that improves our coverage, but also can be used as a simple template when creating new tests.
> tests: add simple local bake test

- Dockerfile
- docker-bake.hcl
- hack/dockerfiles/docs.Dockerfile
- hack/dockerfiles/generated-files.Dockerfile
- hack/dockerfiles/lint.Dockerfile
- hack/dockerfiles/vendor.Dockerfile
> update go to 1.20.6

- bake/remote.go
- build/url.go
follow-up https://github.com/docker/buildx/pull/1954
> build: set remote bake def and remote dockerfile as internal solve

- bake/remote.go
- build/url.go
> [0.11 backport] build: set remote bake def and remote dockerfile as internal solve

- docs/reference/buildx_build.md
(cherry picked from commit 8ad30d0a35ac34b9ee89e8fa7dbbebd85a4d69dd)
> [0.11 backport] docs: update since buildinfo removal

- tests/imagetools.go
While in the process of investigating, https://github.com/docker/buildx/issues/1660, realized we didn't have any tests for it.
I've added some tests to ensure that manifests and indexes are copied with their digests preserved intact.
> tests: add imagetools tests for copying manifests and indexes

- driver/docker/driver.go
- driver/remote/driver.go
This was previously only enabled for container+k8s drivers but Moby is getting OTEL support in https://github.com/moby/moby/pull/45652
> enable trace delegation for docker/remote driver

- .github/workflows/docs-upstream.yml
> ci: update docs upstream validation workflow

- docs/bake-reference.md
> docs: clarify bake file lookup order and merge

- bake/compose.go
- go.mod
- go.sum
- vendor/github.com/compose-spec/compose-go/dotenv/parser.go
- vendor/github.com/compose-spec/compose-go/loader/include.go
- vendor/github.com/compose-spec/compose-go/loader/interpolate.go
- vendor/github.com/compose-spec/compose-go/loader/loader.go
- vendor/github.com/compose-spec/compose-go/loader/mapstructure.go
- vendor/github.com/compose-spec/compose-go/loader/merge.go
- vendor/github.com/compose-spec/compose-go/schema/compose-spec.json
- vendor/github.com/compose-spec/compose-go/types/bytes.go
- vendor/github.com/compose-spec/compose-go/types/command.go
- vendor/github.com/compose-spec/compose-go/types/device.go
- vendor/github.com/compose-spec/compose-go/types/duration.go
- vendor/github.com/compose-spec/compose-go/types/healthcheck.go
- vendor/github.com/compose-spec/compose-go/types/labels.go
- vendor/github.com/compose-spec/compose-go/types/options.go
- vendor/github.com/compose-spec/compose-go/types/stringOrList.go
- vendor/github.com/compose-spec/compose-go/types/types.go
- vendor/modules.txt
https://github.com/compose-spec/compose-go/compare/v1.19.0...v1.20.0
> vendor: update compose-go to v1.20.0

- .github/workflows/codeql.yml
[ESEC-20](https://docker.atlassian.net/browse/ESEC-20)
[ESEC-20]: https://docker.atlassian.net/browse/ESEC-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: enable SAST scanning with CodeQL

- docs/reference/buildx.md
- docs/reference/buildx_bake.md
- docs/reference/buildx_build.md
- docs/reference/buildx_create.md
- docs/reference/buildx_du.md
- docs/reference/buildx_imagetools.md
- docs/reference/buildx_imagetools_create.md
- docs/reference/buildx_imagetools_inspect.md
- docs/reference/buildx_inspect.md
- docs/reference/buildx_ls.md
- docs/reference/buildx_prune.md
- docs/reference/buildx_rm.md
- docs/reference/buildx_stop.md
- docs/reference/buildx_version.md
- driver/docker-container/driver.go
- driver/docker/driver.go
- driver/kubernetes/driver.go
- driver/remote/driver.go
editorial and formatting updates
> docs: minor cli reference editorial updates

- docs/reference/buildx.md
- docs/reference/buildx_bake.md
- docs/reference/buildx_build.md
- docs/reference/buildx_create.md
- docs/reference/buildx_du.md
- docs/reference/buildx_imagetools.md
- docs/reference/buildx_imagetools_create.md
- docs/reference/buildx_imagetools_inspect.md
- docs/reference/buildx_inspect.md
- docs/reference/buildx_ls.md
- docs/reference/buildx_prune.md
- docs/reference/buildx_rm.md
- docs/reference/buildx_stop.md
- docs/reference/buildx_version.md
- driver/docker-container/driver.go
- driver/docker/driver.go
- driver/kubernetes/driver.go
- driver/remote/driver.go
Docs-only cherry-picks:
- #2117
- #2122
> [v0.12] cherry picks docs only

- docs/reference/buildx_du.md
Adds a better description for the `du` command, including asterisks, `RECLAIMABLE`, and examples
> docs: update du cmd description

- bake/bake.go
fixes #2116
The results from credential plugins are cached
and this reduces the lookup times.
> bake: use same auth provider for bake targets

- docs/bake-reference.md
- docs/reference/buildx_build.md
- docs/reference/buildx_imagetools_create.md
Add/improve docs for adding annotations
- relates to docker/docs#18891
> docs: annotations

- docs/bake-reference.md
- docs/reference/buildx_build.md
- docs/reference/buildx_imagetools_create.md
* backport of https://github.com/docker/buildx/pull/2154
> [0.12 backport] docs: annotations

- docs/reference/buildx_build.md
> docs: add --no-cache-filter example

- .github/workflows/validate.yml
- .golangci.yml
- docker-bake.hcl
- hack/dockerfiles/lint.Dockerfile
follow-up https://github.com/moby/buildkit/pull/4411
> enable golangci-lint for supported platforms

- driver/docker-container/factory.go
- tests/create.go
- tests/integration_test.go
- tests/rm.go
> [v0.12 backport] driver(container): fix conditional statement for error handling

- .github/dependabot.yml
related to https://github.com/docker/buildx/pull/2222#issuecomment-1919092153
> chore: ignore docker/docs deps with dependabot

- .github/workflows/build.yml
similar to https://github.com/moby/buildkit/pull/4660
> ci: set codecov token

- tests/build.go
follow-up https://github.com/docker/buildx/pull/2242
> test: build shm-size and ulimit

- go.mod
- go.sum
- vendor/github.com/serialx/hashring/.gitignore
- vendor/github.com/serialx/hashring/hash.go
- vendor/github.com/serialx/hashring/hashring.go
- vendor/github.com/serialx/hashring/key.go
- vendor/modules.txt
full diff: https://github.com/serialx/hashring/compare/8b2912629002...22c0c7ab6b1b
> vendor: github.com/serialx/hashring 22c0c7ab6b1b (master)

- go.mod
- go.sum
- vendor/github.com/moby/buildkit/util/contentutil/multiprovider.go
- vendor/modules.txt
full diff: https://github.com/moby/buildkit/compare/v0.13.0-rc2...v0.13.0-rc3
> vendor: github.com/moby/buildkit v0.13.0-rc3

- .github/workflows/docs-release.yml
Automatically create PR for updating docs on release
I have no idea how to test this
> ci: fix docs-release workflow

- docs/reference/buildx_build.md
> docs: fix link to new target in dockerfile reference

- .github/workflows/validate.yml
similar to https://github.com/moby/buildkit/pull/4739
> ci: enable multi-platform lint only for upstream repo

- util/progress/metricwriter.go
This measures the amount of time it takes to export to a specific
format.
> metrics: measure export image operation

- go.mod
- go.sum
- vendor/github.com/docker/docker/api/swagger.yaml
- vendor/github.com/docker/docker/api/types/registry/registry.go
- vendor/github.com/docker/docker/api/types/types.go
- vendor/github.com/docker/docker/api/types/volume/cluster_volume.go
- vendor/github.com/docker/docker/client/client.go
- vendor/github.com/docker/docker/client/container_create.go
- vendor/github.com/docker/docker/client/container_exec.go
- vendor/github.com/docker/docker/client/container_restart.go
- vendor/github.com/docker/docker/client/container_stop.go
- vendor/github.com/docker/docker/client/container_wait.go
- vendor/github.com/docker/docker/client/errors.go
- vendor/github.com/docker/docker/client/image_list.go
- vendor/github.com/docker/docker/client/network_create.go
- vendor/github.com/docker/docker/client/ping.go
- vendor/github.com/docker/docker/client/request.go
- vendor/github.com/docker/docker/client/service_create.go
- vendor/github.com/docker/docker/client/service_update.go
- vendor/github.com/docker/docker/client/volume_remove.go
- vendor/github.com/docker/docker/pkg/namesgenerator/names-generator.go
- vendor/github.com/docker/docker/registry/search.go
- vendor/modules.txt
follow-up https://github.com/docker/buildx/pull/2372#discussion_r1547483393
> vendor: github.com/docker/docker v26.0.0

- tests/build.go
related to https://github.com/docker/buildx/issues/2368
> tests: build from stdin

- go.mod
- go.sum
- vendor/github.com/compose-spec/compose-go/v2/cli/options.go
- vendor/github.com/compose-spec/compose-go/v2/errdefs/errors.go
- vendor/github.com/compose-spec/compose-go/v2/graph/cycle.go
- vendor/github.com/compose-spec/compose-go/v2/graph/graph.go
- vendor/github.com/compose-spec/compose-go/v2/loader/extends.go
- vendor/github.com/compose-spec/compose-go/v2/loader/include.go
- vendor/github.com/compose-spec/compose-go/v2/loader/loader.go
- vendor/github.com/compose-spec/compose-go/v2/loader/normalize.go
- vendor/github.com/compose-spec/compose-go/v2/loader/validate.go
- vendor/github.com/compose-spec/compose-go/v2/schema/compose-spec.json
- vendor/github.com/compose-spec/compose-go/v2/template/template.go
- vendor/github.com/compose-spec/compose-go/v2/types/project.go
- vendor/github.com/compose-spec/compose-go/v2/types/types.go
- vendor/modules.txt
> vendor: update compose-go to v2.0.2

- go.mod
- go.sum
- vendor/github.com/docker/cli/cli-plugins/plugin/plugin.go
- vendor/github.com/docker/cli/cli/command/telemetry.go
- vendor/github.com/docker/cli/cli/command/telemetry_utils.go
- vendor/github.com/docker/cli/cli/command/utils.go
- vendor/github.com/docker/cli/cli/debug/debug.go
- vendor/modules.txt
fixes https://github.com/docker/buildx/issues/2389
full diff: https://github.com/docker/cli/compare/155dc5e4e406...b6c552212837
> vendor: github.com/docker/cli b6c552212837 (v26.1.0-dev)

- driver/kubernetes/factory.go
- driver/kubernetes/manifest/manifest.go
this allows for custom scheduling of deployments
> feat: adding option to add scheduler name to kubernetes driver

- tests/build.go
follow-up https://github.com/docker/buildx/pull/2416#issuecomment-2061465603
> test: build print

- build/build.go
Brings in fix https://github.com/moby/buildkit/pull/4987
> build: update lint fallback image

- build/build.go
https://github.com/moby/buildkit/actions/runs/9469693574/job/26089312896
> build: update lint fallback image to dockerfile 1.8.0

- tests/build.go
follow-up https://github.com/docker/buildx/pull/2487
Align flags in tests and remove experimental mode check as well.
> test: align build call tests

- .github/workflows/build.yml
- Dockerfile
- codecov.yml
- docker-bake.hcl
- hack/test
- tests/integration.go
follow-up https://github.com/moby/buildkit/pull/4938
https://app.codecov.io/gh/docker/buildx/pull/2508/indirect-changes
> test: setup integration tests coverage

- go.mod
- go.sum
- vendor/github.com/docker/docker-credential-helpers/client/client.go
- vendor/github.com/docker/docker-credential-helpers/credentials/error.go
- vendor/modules.txt
full diff: https://github.com/docker/docker-credential-helpers/compare/v0.8.0...v0.8.2
> vendor: github.com/docker/docker-credential-helpers v0.8.2

- go.mod
- go.sum
- vendor/github.com/moby/buildkit/frontend/dockerfile/shell/lex.go
- vendor/github.com/moby/buildkit/frontend/subrequests/lint/lint.go
- vendor/modules.txt
> vendor: update buildkit v0.14.1

- .github/labeler.yml
- .github/workflows/labeler.yml
Extraction of **Pull request labeler** functionality from https://github.com/docker/buildx/pull/2485.
> ci: add pr-labeler

- go.mod
- go.sum
- vendor/github.com/spf13/cobra/.golangci.yml
- vendor/github.com/spf13/cobra/active_help.go
- vendor/github.com/spf13/cobra/args.go
- vendor/github.com/spf13/cobra/bash_completions.go
- vendor/github.com/spf13/cobra/cobra.go
- vendor/github.com/spf13/cobra/command.go
- vendor/github.com/spf13/cobra/completions.go
- vendor/github.com/spf13/cobra/flag_groups.go
- vendor/github.com/spf13/cobra/powershell_completions.go
- vendor/modules.txt
full diff: https://github.com/spf13/cobra/compare/v1.8.0...v1.8.1
> vendor: github.com/spf13/cobra v1.8.1

- bake/compose_test.go
related to https://github.com/docker/buildx/issues/2548
> test: compose cgroup property

- bake/bake.go
- builder/builder.go
- commands/build.go
- go.mod
- go.sum
- util/buildflags/attests.go
- util/buildflags/cache.go
- util/buildflags/export.go
- util/buildflags/printfunc.go
- util/buildflags/secrets.go
- vendor/github.com/moby/buildkit/frontend/dockerfile/linter/linter.go
- vendor/github.com/moby/buildkit/session/filesync/diffcopy.go
- vendor/github.com/moby/buildkit/session/filesync/diffcopy_unix.go
- vendor/github.com/moby/buildkit/session/filesync/diffcopy_windows.go
- vendor/modules.txt
Update CSV parsing to csvvalue package.
> use csvvalue package for parsing csv inputs

- docs/reference/buildx_build.md
Adds a CLI reference description for:
- `buildx b --call`
- `buildx b --check`
Closes docker/core-build-team#121
> docs: reference description for --call and --check

- docs/reference/buildx_bake.md
follow-up
* https://github.com/docker/buildx/pull/2562
* https://github.com/docker/buildx/pull/2556
> docs: link to build ref page for --call and --check ref with bake

- bake/compose.go
- bake/compose_test.go
> bake: use compose project name from env if set

- commands/bake.go
- commands/build.go
- tests/bake.go
- tests/integration.go
* https://github.com/docker/buildx/pull/2603
* https://github.com/docker/buildx/pull/2612
> [v0.16] cherry-picks for v0.16.1

- commands/bake.go
relates to #2598
Removes extra go routine that is racy when used along the other one from `progress.WithOnClose`.
> bake: fix printer handling

- .github/workflows/labeler.yml
similar to https://github.com/moby/buildkit/pull/5192
> ci: sync labels when files are reverted or no longer changed with labeler

- go.mod
- go.sum
- vendor/github.com/compose-spec/compose-go/v2/schema/compose-spec.json
- vendor/github.com/compose-spec/compose-go/v2/types/derived.gen.go
- vendor/github.com/compose-spec/compose-go/v2/types/develop.go
- vendor/modules.txt
https://github.com/compose-spec/compose-go/compare/v2.1.5...v2.1.6
> vendor: update compose-go to v2.1.6

- bake/bake.go
- bake/bake_test.go
- docs/bake-reference.md
> bake: add network mode support to HCL and docs for network and entitlements

- docs/bake-reference.md
- docs/reference/buildx_build.md
> docs: update run mount secrets examples using env

- bake/bake.go
- tests/bake.go
relates to https://github.com/docker/actions-toolkit/pull/443#issuecomment-2343534589
> bake: fix missing omitempty and optional tags for network field

- go.mod
- go.sum
- vendor/github.com/compose-spec/compose-go/v2/cli/options.go
- vendor/github.com/compose-spec/compose-go/v2/dotenv/parser.go
- vendor/github.com/compose-spec/compose-go/v2/loader/environment.go
- vendor/github.com/compose-spec/compose-go/v2/loader/extends.go
- vendor/github.com/compose-spec/compose-go/v2/loader/full-example.yml
- vendor/github.com/compose-spec/compose-go/v2/loader/loader.go
- vendor/github.com/compose-spec/compose-go/v2/override/uncity.go
- vendor/github.com/compose-spec/compose-go/v2/schema/compose-spec.json
- vendor/github.com/compose-spec/compose-go/v2/transform/canonical.go
- vendor/github.com/compose-spec/compose-go/v2/transform/device.go
- vendor/github.com/compose-spec/compose-go/v2/types/derived.gen.go
- vendor/github.com/compose-spec/compose-go/v2/types/hostList.go
- vendor/github.com/compose-spec/compose-go/v2/types/types.go
- vendor/modules.txt
Bump version of `compose-go` to latest `v2.2.0`
> bump compose-go to v2.2.0

- go.mod
- go.sum
- vendor/github.com/docker/cli/cli/command/telemetry_docker.go
- vendor/modules.txt
Brings in fix for telemetry under WSL2
> [v0.17] update docker/cli to 48a2cdff97

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/docs-release.yml
- .github/workflows/labeler.yml
relates to https://github.com/docker/buildx/pull/2728#issuecomment-2443587745
> ci: fix workflow permissions

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/labeler.yml
relates to https://github.com/docker/buildx/pull/2761#discussion_r1821296760
> ci: keep contents read permissions in jobs

- .github/CONTRIBUTING.md
> docs: add dev instructions on generating/analyzing pprof samples

- Dockerfile
- docker-bake.hcl
relates to #2772 
I think it would be fine to build and release buildx for freebsd.
> build freebsd

- go.mod
- go.sum
- vendor/github.com/tonistiigi/fsutil/.golangci.yml
- vendor/github.com/tonistiigi/fsutil/chtimes_nolinux.go
- vendor/github.com/tonistiigi/fsutil/copy/copy_openbsd.go
- vendor/github.com/tonistiigi/fsutil/copy/copy_unix.go
- vendor/github.com/tonistiigi/fsutil/copy/stat_openbsd.go
- vendor/github.com/tonistiigi/fsutil/docker-bake.hcl
- vendor/github.com/tonistiigi/fsutil/stat_windows.go
- vendor/modules.txt
relates to #2772 
full diff: https://github.com/tonistiigi/fsutil/compare/397af5306b5c...8d32dbdd27d3
> vendor: github.com/tonistiigi/fsutil 8d32dbdd27d3

- Dockerfile
- docker-bake.hcl
relates to #2772 
needs
* https://github.com/docker/buildx/pull/2782
* https://github.com/docker/buildx/pull/2781
> build openbsd

- go.mod
- go.sum
- vendor/github.com/compose-spec/compose-go/v2/template/variables.go
- vendor/github.com/compose-spec/compose-go/v2/types/project.go
- vendor/github.com/compose-spec/compose-go/v2/types/types.go
- vendor/modules.txt
Update compose-go to version `v2.4.5` for bake
> bump compose-go to v2.4.5

- .github/workflows/build.yml
- .github/workflows/docs-release.yml
- .github/workflows/docs-upstream.yml
- .github/workflows/e2e.yml
- .github/workflows/validate.yml
similar to https://github.com/moby/moby/pull/48982
> ci: use edge releases of buildx

- Dockerfile
Fixes compatibility issues with Alpine 3.21
> update xx to v1.6.1

- go.mod
- go.sum
- vendor/github.com/docker/cli/cli-plugins/manager/manager.go
- vendor/github.com/docker/cli/cli/trust/trust.go
- vendor/github.com/docker/docker/registry/types.go
- vendor/modules.txt
full diff: https://github.com/docker/docker/compare/v27.4.0-rc.2...v27.4.0
full diff: https://github.com/docker/cli/compare/v27.4.0-rc.2...v27.4.0
> vendor: github.com/docker/docker, github.com/docker/cli v27.4.0

- .github/workflows/build.yml
- .github/workflows/docs-release.yml
- .github/workflows/docs-upstream.yml
- .github/workflows/e2e.yml
- .github/workflows/validate.yml
https://github.com/docker/bake-action/releases/tag/v6.0.0
> ci: update bake-action to v6

- commands/build.go
- docs/reference/buildx_bake.md
- docs/reference/buildx_build.md
- docs/reference/buildx_debug_build.md
relates to https://github.com/docker/bake-action/issues/278#issuecomment-2577400226
needs follow-up on docs repo as well: https://docs.docker.com/build/building/variables/#buildkit_progress
> docs: missing quiet progress mode

- bake/bake.go
relates to https://github.com/docker/docs/pull/21831
> chore: comments to not forget to update docs

- bake/bake.go
- bake/bake_test.go
- bake/compose.go
- commands/build.go
- util/buildflags/cache.go
- util/buildflags/cache_cty.go
- util/buildflags/cache_test.go
Fixes https://github.com/docker/build-push-action/issues/1306.
> buildflags: fix ref only format for command line and bake

- go.mod
- go.sum
- vendor/modules.txt
> vendor: update buildkit to v0.19.0

- .github/workflows/docs-upstream.yml
- bake/bake.go
- bake/bake_test.go
- bake/compose.go
- commands/build.go
- docs/bake-reference.md
- docs/reference/buildx_bake.md
- util/buildflags/cache.go
- util/buildflags/cache_cty.go
- util/buildflags/cache_test.go
> [v0.20.1] cherry picks

- docs/bake-reference.md
> docs: update bake reference to use composable attrs

- hack/test
follow-up https://github.com/docker/buildx/pull/2979#discussion_r1950093716
> hack: mount docker config on gha

- go.mod
- go.sum
- vendor/github.com/docker/cli/cli-plugins/manager/manager.go
- vendor/github.com/docker/cli/cli/cobra.go
- vendor/github.com/docker/cli/cli/command/cli.go
- vendor/github.com/docker/cli/cli/command/cli_options.go
- vendor/github.com/docker/cli/cli/command/formatter/custom.go
- vendor/github.com/docker/cli/cli/command/formatter/disk_usage.go
- vendor/github.com/docker/cli/cli/command/telemetry.go
- vendor/github.com/docker/cli/cli/connhelper/commandconn/commandconn.go
- vendor/github.com/docker/cli/cli/debug/debug.go
- vendor/github.com/docker/cli/cli/manifest/store/store.go
- vendor/github.com/docker/cli/cli/registry/client/endpoint.go
- vendor/github.com/docker/cli/cli/registry/client/fetcher.go
- vendor/github.com/docker/cli/cli/trust/trust.go
- vendor/github.com/docker/cli/internal/tui/colors.go
- vendor/github.com/docker/cli/opts/config.go
- vendor/github.com/docker/cli/opts/duration.go
- vendor/github.com/docker/cli/opts/gpus.go
- vendor/github.com/docker/cli/opts/mount.go
- vendor/github.com/docker/cli/opts/network.go
- vendor/github.com/docker/cli/opts/opts.go
- vendor/github.com/docker/cli/opts/port.go
- vendor/github.com/docker/cli/opts/quotedstring.go
- vendor/github.com/docker/cli/opts/secret.go
- vendor/github.com/docker/cli/opts/throttledevice.go
- vendor/github.com/docker/cli/opts/ulimit.go
- vendor/github.com/docker/cli/opts/weightdevice.go
- vendor/github.com/docker/docker/api/swagger.yaml
- vendor/modules.txt
no code changes in vendor, only updated swagger file
full diff: https://github.com/docker/docker/compare/v28.0.0-rc.2...v28.0.0-rc.3
no significant changes, only linting fixes
full diff: https://github.com/docker/cli/compare/v28.0.0-rc.2...v28.0.0-rc.3
> vendor: github.com/docker/docker, docker/cli v28.0.0-rc.3

- go.mod
- go.sum
- vendor/modules.txt
- https://github.com/docker/buildx/pull/3010
> [v0.21] cherry-picks for v0.21.0

- util/buildflags/entitlements.go
> remove accidental debug

- util/buildflags/entitlements.go
* backport of https://github.com/docker/buildx/pull/3017
> [v0.21] cherry-picks for v0.21.1

- bake/hcl_test.go
- tests/bake.go
- util/buildflags/attests.go
- util/buildflags/attests_test.go
- util/buildflags/cache.go
- util/buildflags/export.go
backport of
* https://github.com/docker/buildx/pull/3021
* https://github.com/docker/buildx/pull/3027
> [v0.21] cherry-picks for v0.21.2

- commands/bake.go
- commands/build.go
- localstate/localstate.go
- localstate/localstate_test.go
- localstate/migrate.go
- util/tracing/trace.go
https://github.com/docker/buildx/security/advisories/GHSA-m4gq-fm9h-8q75
> cherry-picks for CVE-2025-0495

- go.mod
- go.sum
- vendor/github.com/spf13/cobra/README.md
- vendor/github.com/spf13/cobra/active_help.go
- vendor/github.com/spf13/cobra/bash_completionsV2.go
- vendor/github.com/spf13/cobra/cobra.go
- vendor/github.com/spf13/cobra/command.go
- vendor/github.com/spf13/cobra/completions.go
- vendor/github.com/spf13/cobra/powershell_completions.go
- vendor/github.com/spf13/pflag/.editorconfig
- vendor/github.com/spf13/pflag/.golangci.yaml
- vendor/github.com/spf13/pflag/flag.go
- vendor/github.com/spf13/pflag/ip.go
- vendor/github.com/spf13/pflag/ipnet_slice.go
- vendor/github.com/spf13/pflag/string_array.go
- vendor/modules.txt
full diff: https://github.com/spf13/pflag/compare/v1.0.5...v1.0.6
full diff: https://github.com/spf13/cobra/compare/v1.8.1...v1.9.1
> vendor: github.com/spf13/cobra v1.9.1

- .github/workflows/pr-assign-author.yml
relates to
* https://github.com/crazy-max/.github/pull/46
* https://github.com/crazy-max/.github/pull/47
> ci: update pr-assign-author

- cmd/buildx/main.go
fix https://github.com/docker/buildx/issues/3174
> cmd: custom exit codes for internal, resource and canceled errors

- bake/hclparser/merged.go
- bake/hclparser/merged_test.go
closes https://github.com/docker/buildx/pull/2831
Just getting tests in.
> bake: hcl merged tests

- go.mod
- go.sum
- vendor/modules.txt
backport of
* https://github.com/docker/buildx/pull/3254
> [v0.25] cherry-picks for v0.25.0

- bake/compose.go
- bake/compose_test.go
fixes https://github.com/docker/compose/issues/12989
> compose: evaluate vars from current env in dotenv file

- go.mod
- go.sum
- vendor/github.com/Masterminds/semver/v3/CHANGELOG.md
- vendor/github.com/Masterminds/semver/v3/Makefile
- vendor/github.com/Masterminds/semver/v3/README.md
- vendor/github.com/Masterminds/semver/v3/constraints.go
- vendor/github.com/Masterminds/semver/v3/version.go
- vendor/modules.txt
https://github.com/Masterminds/semver/compare/v3.2.1...v3.4.0
> vendor: github.com/Masterminds/semver/v3 v3.4.0

- bake/compose.go
backport of
* https://github.com/docker/buildx/pull/3322
> [v0.26] cherry-picks for v0.26.0

- bake/compose.go
- bake/compose_test.go
backport of:
* https://github.com/docker/buildx/pull/3329
> [v0.26] cherry-picks for v0.26.1

- dap/eval.go
In the repl context, we will now return the error instead of directly
printing it. We also suppress reporting errors from cobra. The logic
flow has also been changed to prevent returning errors from cobra unless
there was something related to the command line invocation so usage will
only be printed when a command was typed wrong and it will not show up
for every error.
> dap: return error from evaluate command in repl context

- dap/thread.go
- dap/variables.go
Add a file explorer to the debugger that allows exploring the filesystem
of the current container. It will show directory contents, file
contents, and symlink destinations. It will also show the file mode
associated with a file.
The file explorer defaults to marking itself as an expensive operation
so the debugger doesn't automatically retrieve the information.
> dap: filesystem inspection when paused on a digest

- go.mod
- go.sum
- vendor/github.com/moby/buildkit/util/grpcerrors/grpcerrors.go
- vendor/modules.txt
backport of:
- https://github.com/docker/buildx/pull/3442
> [0.29] cherry-picks for v0.29.0

- docs/bake-stdlib.md
Closes https://github.com/docker/buildx/issues/3310
> Docs: examples for each bake standard library functions

- commands/imagetools/create.go
fix #3446
When creating index from singe-arch manifests it
was possible for some of the internal manifests to not be copies and cause error on pushing the index.
> imagetools: fix possible broken chain copy on create
