docker/buildx

hack/dockerfiles/vendor.Dockerfile

Avoid writing on top of build context that forces a new context transfer every time and invalidates cache.

hack: update vendor dockerfile

---

Dockerfile
build/build.go
cmd/buildx/main.go
commands/build.go
commands/root.go
driver/docker/driver.go
driver/docker/factory.go
driver/driver.go
driver/manager.go
go.mod
go.sum
util/progress/printer.go
util/progress/progress.go
util/progress/writer.go
vendor/github.com/docker/docker/pkg/stdcopy/stdcopy.go
vendor/github.com/moby/buildkit/client/client.go
vendor/github.com/moby/buildkit/client/connhelper/connhelper.go
vendor/modules.txt

Starting to implement docker driver

drivers base implementation

---

cmd/buildx/main.go
commands/root.go
vendor/modules.txt

Allow invoking `buildx` binary directly, not only with `docker buildx`

cmd: allow invoking without plugin

---

commands/imagetools/create.go
commands/imagetools/inspect.go
commands/imagetools/root.go
commands/root.go
go.mod
util/imagetools/inspect.go
util/imagetools/printers.go
vendor/modules.txt

These commands are useful when builder outputs manifest lists or pushes directly in the registry. Otherwise, there is no way to see what was actually built or combine results created at different times. Only `inspect` is currently (partially) implemented.

imagetools: initial partial implementation

---

bake/bake.go
build/build.go
commands/build.go
commands/inspect.go
commands/ls.go
commands/util.go
store/nodegroup.go
store/nodegroup_test.go
util/platformutil/parse.go

These fixes make sure that platforms are not duplicated when they are combined from automatic and manual sources, or if the user input is not normalized. It also makes sure that setting a manual platform on a node resets the same platform on other nodes.
Fixes #29

fixes for managing platforms

---

bake/bake.go
bake/bake_test.go
bake/compose.go
bake/compose_test.go
bake/hcl_test.go
build/build.go

Fixes the default values for context/dockerfile. Previously the default value could take precedence over the manual value when targets were combined.

bake: fix dockerfile and context defaults

---

build/build.go
commands/build.go
commands/imagetools/create.go
driver/docker-container/driver.go
driver/docker-container/factory.go
driver/docker/driver.go
driver/docker/factory.go
driver/driver.go
util/imagetools/create.go
util/imagetools/inspect.go
util/progress/multiwriter.go
util/progress/writer.go
vendor/modules.txt

based on #35 
Automatically split a build to chunks based on platform if needed, distribute between nodes and merge back to a manifest list when all nodes have completed.

build: multi-node build support

---

README.md

Explain single-platform limitation of docker export type

---

README.md

`binaries` is already the default target.

readme: simplify install instructions

---

cmd/buildx/main.go

Discussion in docker/cli#1898 and docker/cli#1897
To guard this Docker CLI plugin with docker's experimental CLI config, buildx needs to be built with `go build -ldflags "-X main.experimental=1"`

Allow Docker to ship buildx guarded by the experimental flag

---

bake/compose.go
bake/compose_test.go
hack/demo-env/examples/compose/docker-compose.yml

Closes #79 which is carried in this PR.
This PR basically handles properly compose services without a `build` field, by skipping them, but errors out when neither a `build` nor an `image` field is present.
Tests updated accordingly.

[Carry #79] Change compose file handling to require valid service specifications

---

commands/create.go
driver/manager.go

$ docker buildx driver ls
NAME             USAGE
docker           docker
docker-container docker-container
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

Put driver names to create --help

---

commands/create.go
commands/inspect.go
commands/util.go
driver/docker-container/driver.go
driver/manager.go
go.mod
store/nodegroup.go
store/nodegroup_test.go

Add `docker buildx create --buildkitd-flags ''` for setting custom flags for buildkitd daemon.

driver: allow configuring buildkitd flags

---

commands/create.go
commands/util.go
driver/docker-container/driver.go
driver/docker-container/factory.go
driver/manager.go
store/nodegroup.go
store/nodegroup_test.go

Allow setting driver options `create --driver-opt`:
- `network=host`
- `image=moby/buildkit:v0.5.0`

driver: allow setting driver opts

---

bake/bake.go
bake/bake_test.go

fixes #133 
Workaround is to name all the targets in the command line
@FernandoMiguel 

bake: merge targets on same groups

---

driver/docker-container/driver.go
driver/docker-container/factory.go

Fixes #169
Example usage:
```bash
docker buildx create --driver-opt env.http_proxy=$http_proxy --driver-opt env.https_proxy=$https_proxy --driver-opt '"env.no_proxy='$no_proxy'"'
```
---
Original suggestion:
```bash
docker buildx create --driver-env http_proxy=$http_proxy --driver-env https_proxy=$https_proxy --driver-env '"no_proxy='$no_proxy'"'
```

Support environment variables in docker-container driver

---

commands/imagetools/inspect.go

noticed in https://github.com/docker/buildx/issues/181

imagetools: avoid printing newline on raw mode

---

README.md

Move a paragraph in README to clarify where it fits in the structure. I got confused by this, so taking 5mn to propose a version that would have not confused me.
- Before the move, the paragraph seems to apply to the `--output=local` section when in fact it applies to the entire `--output` section. This is especially confusing for the sentence "if just the path is specified as a value, `buildx` will use the local exporter with this path as the destination".
- After the move, it is clear that the paragraph applies to `--output`

Clarify documentation structure

---

commands/build.go

When following this pattern:
```
buildx build --arg FOO
```
Where we want to pull `FOO` from env, currently we always set `FOO`
regardless if the `FOO` env var is even set.
This change makes it so that `FOO` would only be set if it has been set
in the env (even if it is set to empty).
Signed-off-by: Brian Goff <cpuguy83@gmail.com>

build: only use env for args if set

---

driver/kubernetes/factory.go
go.mod

Otherwise it ends up being default and it's probably not the normal
case.

Make k8s driver priority lower

---

README.md

this dir doesn't exist by default so add a mkdir

README: add mkdir for .docker/cli-plugins

---

bake/bake.go
bake/bake_test.go

Added the bug case in tests:
```hcl
target "dep" {
args {
VAR_INHERITED = "dep"
}
}
target "webapp" {
dockerfile = "Dockerfile.webapp"
inherits = ["dep"]
}
```
`bake --set webapp.args.VAR_INHERITED=override` was still inheriting `dep` value.

bake: fix override bug with inheritance

---

README.md
bake/bake.go
bake/bake_test.go
commands/bake.go
commands/build.go

Although bake is for running multiple targets, --set required a single
target name for overriding a property. This change allows matching
multiple targets for overrides.
bake: add --load and --push shorthands for --set

bake: allow pattern matching for target names in --set

---

README.md
bake/bake.go
commands/bake.go
commands/build.go
util/flagutil/flagutil.go

bake: allow overriding no-cache and pull per target via --set

---

commands/inspect.go
commands/ls.go
util/platformutil/parse.go

Allow preferred platforms to be distinguished from automatic ones and fix missing dedupe in ls.

separate manual and automatically detected platforms

---

commands/prune.go

The docker builder prune command has a shorthand `-f` flag for `--force`:
docker builder prune --help
Usage:	docker builder prune
Remove build cache
Options:
-a, --all                  Remove all unused build cache, not just dangling ones
--filter filter        Provide filter values (e.g. 'until=24h')
-f, --force                Do not prompt for confirmation
--keep-storage bytes   Amount of disk space to keep for cache
Given that `buildx` can be used as a drop-in replacement for the native build
commands, it should match the UI, and also have a shorthand flag.
With this patch applied;
buildx prune --help
Remove build cache
Usage:
buildx prune [flags]
Flags:
-a, --all                  Remove all unused images, not just dangling ones
--filter filter        Provide filter values (e.g. …

Add -f shorthand flag for prune --force

---

bake/bake.go
bake/hcl.go
bake/hcl_test.go

Providing a `docker-bake.json` to `docker buildx bake` fails to parse because we were always assuming `hcl` formatted config after the hcl v2 upgrade.
```
$ cat <<'EOF' > docker-bake.json
{
"variable": {
"TAG": {
"default": "latest"
}
},
"group": {
"default": {
"targets": ["webapp"]
}
},
"target": {
"webapp": {
"args": {
"buildno": "${add(123, 1)}"
}
}
}
}
EOF
$ docker buildx bake -f docker-bake.json --print webapp                                                                   
bake.json:1,1-2: Argument or block definition required; An argument or block definition is required here.  
```
Fixed this by using the json parser based on the file suffix.
```
$ docker buildx bake -f docker-bake.json --print webapp                                                                   
{ …
```

Support parsing json config with hcl v2

---

commands/bake.go

bake: ensure `--builder` is wired from root options

---

hack/demo-env/entrypoint.sh

Some containerd logs print to stdout 🤷‍♂️ , so make sure both fds are sent to file to make sure this doesn't mess up build output.

demo-env: correct dockerd logging

---

build/build.go

cacheonly is a fake exporter name supported by moby to avoid default behavior of creating an image. Add support for buildx as well so same flags can be used.
Second commit also adds an env to opt-out of default behavior that is probably a cleaner solution if you don't know if docker or container driver is used by buildx.

build: support cacheonly exporter

---

driver/docker-container/driver.go

fix #331
Second commit also increases daemon start timeout. Previous value was only 2.2sec so could be that this is what triggered #331 initially.
cc @howardjohn
@AkihiroSuda Would be good to get something similar to the kubernetes driver as well.

docker-container: show logs on bootstrap error

---

commands/util.go
driver/manager.go

grant permission to `service account` of pod.

feat: use k8s cluster config when buildx used in k8s cluster

---

README.md
commands/create.go
commands/util.go
driver/kubernetes/driver.go
driver/kubernetes/factory.go
driver/kubernetes/manifest/manifest.go

fix #342 
now we could use kubernetes driver with `--append`
```bash
docker buildx create --use --name=buildkit --platform=linux/amd64 --node=buildkit-amd64 --driver=kubernetes --driver-opt="nodeselector=kubernetes.io/arch=amd64"
docker buildx create --append --name=buildkit --platform=linux/arm64 --node=buildkit-arm64 --driver=kubernetes --driver-opt="nodeselector=kubernetes.io/arch=arm64"
```
```bash
docker buildx inspect buildkit --bootstrap
Name:   buildkit
Driver: kubernetes
Nodes:
Name:      buildkit-amd64
Endpoint:  kubernetes://buildkit/buildkit-amd64
Status:    running
Platforms: linux/amd64*, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
Name:      buildkit-arm64
Endpoint:  kubernetes://buildkit/buildkit-arm64
Status:    running …
```

feat: enhance kubernetes driver

---

hack/test
hack/util

Noticed that this script hard-coded amd64 on Darwin.
Haven't been able to test the output of `uname -m` on Apple silicon, so if someone's able to verify 🤗 
Also makes some small other changes caught by my linter (see individual commits for details)

hack/util: take other arches into account on Darwin

---

commands/util.go
store/store.go

- decouple store path from `$DOCKER_CONFIG`
- improve containerised build setup
- introduce new `$BUILDX_CONFIG` environment variable
Related to #308

Allow users to have separate store paths

---

bake/hcl.go

depends on #389
Extend typed errors support to cover bake errors from the client side:
```
/work/hello # docker buildx bake
docker-bake.hcl:3
1 |     target "binary" {
2 |       target = "bin"
3 | >>>   plat forms = ["local"]
4 |       output = ["type=local,dest=bin/"]
5 |     }
error: docker-bake.hcl:3,14-15: Invalid block definition; The equals sign "=" indicates an argument definition, and must not be used when defining a block.
```
```
/work/hello # docker buildx bake --print -f docker-bake.json foo
docker-bake.json:3
1 |     {
2 |     	"target": {
3 | >>> 		"foo": {},
4 |     	}
5 |     }
error: docker-bake.json:3,14-15: Trailing comma in object; JSON does not permit a trailing comma after the final …
```

bake: format hcl errors with source definition

---

commands/diskusage.go
commands/prune.go

These annotations were picked up by the YAML docs generator, and showed up as "minimum API version" (https://github.com/docker/docker.github.io/pull/11447). I couldn't find a reference to these annotations in the PR that added them, so thought it would be ok to remove

Remove "version" annotations from du and prune commands

---

build/build.go

build: avoid warn on empty config value

---

commands/rm.go
commands/util.go

Currently `docker buildx --builder=default build .` produces error `error: open /root/.docker/buildx/instances/default: no such file or directory`. This makes it work properly and produces appropriate error if context name is used instead.
@cpuguy83 

allow builder flag to switch to default instance

---

build/build.go
commands/inspect.go
driver/docker-container/driver.go
driver/docker/driver.go
driver/driver.go
driver/kubernetes/driver.go
util/imagetools/inspect.go

Anonymous pulls may get rate limited differently so make sure to send user credentials when pulling buildkit image for creating builder container.
If anyone hits this live workaround is to run `docker pull moby/buildkit:buildx-stable-1` manually before `docker buildx create`.
@AkihiroSuda you probably want to make a similar change for kube driver.

docker-container: ensure credentials are passed when pulling buildkit

---

build/build.go

fixes #415
This was supported by the legacy builder: moby/moby#10858

build: handle lowercase Dockerfile name as a fallback

---

driver/docker-container/driver.go

Disable user namespace remapping in docker-container driver

---

.github/workflows/build.yml
.github/workflows/godev.yml
.gitignore
README.md
codecov.yml
hack/build_ci_first_pass
hack/test
hack/util

Follow-up #451 
* `make test` GHA compatible
* Add local cache for GHA (binaries)
* Add badges in README
* Add godev workflow to "ping" pkg.go.dev for changes when a release is produced (see [Adding a package](https://go.dev/about)).
* Add codecov

GitHub Actions for test

---

build/build.go
commands/inspect.go
commands/util.go
driver/docker-container/driver.go
driver/docker/driver.go
driver/driver.go
driver/kubernetes/driver.go
driver/manager.go
util/imagetools/inspect.go

Refactor driver auth passing from #433 so it is initialized with the driver instead. Carrying auth config with function calls will become very cumbersome when more places that invoke `Boot` are added.

refactor driver auth for easier passing

---

.github/workflows/build.yml
Makefile
hack/cross

GitHub Actions cross

---

commands/build.go

As suggested in #401, replace error generated by `--quiet` option by a warning.

fixes #401 : Replace error generated by `quiet` option by a warning.

---

commands/util.go

Signed-off-by: Wang Jinglei <morlay.null@gmail.com>
use kube config in cluster not work with last PR https://github.com/docker/buildx/pull/368
sorry for checking so late.

fix: buildx in k8s pod with kube client config in cluster

---

README.md
bake/bake.go
bake/hcl.go

this change aims to resolve #427 by allowing either the compact function to be used and also allowing empty strings to be present in the resulting bake file and stripping them out of the final file before actioning.
example file 1 with compact.
```
variable "TAG" {default="" }
group "default" {
targets = [
"app",
]
}
target "app" {
context="."
dockerfile="Dockerfile"
tags = "${compact([
"my-image:latest",
notequal("",TAG) ? "my-image:${TAG}-1": "",
notequal("",TAG) ? "my-image:${TAG}-2": null,
null,
])}"
}
```
Example 2 with allowing empty strings in arrays will no longer cause any issues with docker push as they are stripped.
```variable "TAG" {default="" }
group "default" {
targets = [
"app",
]
}
target "app" {
context="."
dockerfile="Dockerfile"
tags = [
"my-image:latest", …
```

fixes #427: Handle empty strings in elements enabling conditional logic

---

bake/bake.go
bake/bake_test.go
bake/hcl.go
bake/remote.go
build/build.go
build/url.go
commands/bake.go
commands/build.go
commands/inspect.go
driver/docker-container/driver.go
driver/docker/driver.go
driver/driver.go
driver/kubernetes/driver.go
driver/manager.go
util/progress/fromreader.go
util/progress/multiwriter.go
util/progress/printer.go
util/progress/reset.go
util/progress/writer.go

- Add git/http url support to bake
- Add HTTP url support to Dockerfile path
~Depends on unmerged vendor update~

bake: remote inputs support

---

build/build.go

This allows builders to opt into determnistic output regardless of
multi-platform output or not.
This resolves the real intention behind 158; deterministic output.
Closes #158

Get multi-platform buildkit frontend opt from args

---

build/build.go
driver/docker-container/driver.go
driver/docker/driver.go
driver/driver.go
driver/kubernetes/driver.go
util/progress/progress.go

Allow `--push` to be used with Docker driver by pushing the final image with Docker API instead of Buildkit.
@crazy-max 
Depends on: #398 #441

build: add push support to docker driver

---

commands/util.go
driver/kubernetes/factory.go
driver/manager.go

Addresses https://github.com/docker/setup-buildx-action/issues/45
Simple repro:
```
$ buildx create --platform linux/amd64 --use
$ buildx build - <<EOF
from scratch
EOF
```
Since https://github.com/docker/buildx/pull/370 a `platform` driver-opt was automatically inserted with the value specified by `--platform` flag on regardless of the type of driver, even though it was only used in the kubernetes driver. However, because the docker-container driver is pedantic about the options being passed, it errored out.
Another side-effect I suspect is that with the kubernetes driver it was now possible to specify the platforms in two different ways: `--driver-opt platform=...` and `--platform`.
This patch reverts completely the `platform` driver-opt and instead ensures the platforms information is …

driver: do not insert "platform" as driver-opt

---

driver/bkimage/bkimage.go

set DefaultRootlessImage to "moby/buildkit:buildx-stable-1-rootless"

---

commands/util.go

refactor to remove the strange `len(ngi.drivers) == 1`, and to check kubernetes driver first 
When create builder with different drivers (not matter contains kubernetes driver or not), should list node with endpoint
```bash
$ docker buildx create --use --name=buildkit --platform=linux/amd64 --node=local
$ docker buildx create --append --name=buildkit  --platform=linux/arm64 --node=buildkit-arm64 --driver=kubernetes
$ docker buildx inspect buildkit                                
Name:   buildkit
Driver: kubernetes
Nodes:
Name:      buildkit-amd64
Endpoint:  unix:///var/run/docker.sock
Status:    running
Platforms: linux/amd64*, linux/386
Name:      buildkit-arm64
Endpoint:  kubernetes://buildkit?deployment=buildkit-arm64
Status:    running
Platforms: linux/arm64*, linux/amd64, linux/386 …
```

should list real pod nodes when all drivers are kubernetes

---

commands/create.go
commands/util.go

issue from slack by David Giffin
> Is there a way to pass a kubeconfig to "docker buildx"? I need to be able to switch between clusters / builders easily. It looks like buildx is using the default context / cluster when creating buildkit deployments, running builds, etc
failed use docker context, the auth way not support only `username` & `password` (https://github.com/docker/cli/blob/master/cli/context/kubernetes/load.go#L73-L74), 
which will break other auth ways like `client-key` & `client-cert`.
just added query parameter config-file  (from `KUBECONFIG` when builder created). and dynamic load kube config when use the kubernetes builder.

feat: store kube config file to make buildx builder switchable

---

commands/build.go

In my case I want to always use plain to show container output without specifying `--progress` flag every time. This PR allows to set the default `progress` value through the `BUILDX_PROGRESS_DEFAULT` env var.

Allow to set default progress through env var

---

bake/hcl.go

As explained in the following link, it's a very useful function.
https://www.terraform.io/docs/configuration/functions/setproduct.html#finding-combinations-for-for_each
This is my use case:
```hcl
function "create_tags" {
params = [image_name]
variadic_param = tags
result = [
for rt in setproduct(["docker.io", "ghcr.io"], tags):
"${rt[0]}/${image_name}:${rt[1]}"
]
}
```

Add setproduct function to the bake HCL

---

Makefile

New MacOS forbids executable files to be modified after they have run once. There is an inode-based cache that instantly kills the process when this happens. Solution is to use a method that removes the old file and then replaces it.

avoid cp in install target

---

build/build.go

don't require entitlement for network none

---

MAINTAINERS

Welcome @crazy-max to maintainers. Thanks for all the great work around integrating buildx with Github actions.
@AkihiroSuda was already a maintainer from the project start, especially around the k8s driver. Not sure how he got missing from the file 👀 

add akihiro and crazy-max to maintainers

---

bake/hcl.go
bake/hcl_test.go

Currently, all variables used in functions need to be passed in as parameters. This is quite cumbersome and ofter means variables need to be redefined as parameters. Eg. https://github.com/tonistiigi/binfmt/blob/master/docker-bake.hcl#L47 . This change allows user functions to see global variables by just changing their parsing order.
@vanstee @crazy-max 

bake: allow variables in user functions

---

util/progress/printer.go

Allows it to write to `os.DevNull` and by this silencing the printer.
Related to https://github.com/docker/compose-cli/pull/1390

Add quiet mode to progress printer

---

bake/bake.go
bake/hcl.go
bake/hcl_test.go

depends on #538 #532
Allows variables to refer to other variables like the target blocks can. Stdlib functions can also be called. User functions can't atm. , I think changes are needed in upstream to support that.
Non-string variables are also now accepted. The value passed with env is parsed into suitable type first.
@vanstee @crazy-max

bake: allow variables to reference each other

---

commands/imagetools/inspect.go

Saw I had this change uncommitted in my local repo, so let me push it as a PR 😂 
Looks like this function may return an error, which we currently discard.

imagetools inspect: don't discard errors from PrintManifestList

---

bake/hcl.go
bake/hcl_test.go

depends on #539 #538
I propose this as a base for https://github.com/docker/buildx/pull/489#pullrequestreview-561253366 
You can now define global scope attributes in HCL/JSON and use them for code reuse and setting values for variables. This means you can do a "data-only" HCL file with the values you want to set/override and use it in the list of regular output files.
Eg.
```
variable "REPO" {
default = "tonistiigi/repo"
}
APP_TAG="foo"
target "app" {
tags = ["${REPO}/${APP_TAG}"]
args = {
variant = APP_TAG
}
}
```
You can use this file directly or create an override configuration file
```
WHOAMI="myuser"
REPO="${WHOAMI}/foo"
APP_TAG="bar-by-${WHOAMI}"
```
and invoke bake together with both of the files.
So instead of loading a `.env` automatically with another custom format, you can …

bake: allow attributes in global scope

---

build/build.go
build/cache.go

Client-side support for https://github.com/moby/buildkit/pull/1974
`--cache-to type=gha[,scope=foo]`
`--cache-from type=gha[,scope=foo]`
If called outside github environment and required `env` are not present then the configuration will be skipped. Token/URL can also be passed directly in csv but I would expect only a program wrapping buildx to use that method.

allow exporting to github cache backend

---

commands/imagetools/create.go
docs/reference/buildx_imagetools_create.md
util/imagetools/create.go

closes #562 #563
Fixes the case where remote descriptor would overwrite the local one parsed from the JSON and override custom annotations/platform info. Add docs for this case.
@thaJeztah @crazy-max @sjackman

imagetools: fix merging JSON descriptor with old one

---

README.md
docs/reference/buildx_bake.md

Removes 19.03 hacks that are not needed anymore and fixes some linking around bake command.

readme: update installation instructions

---

docs/reference/buildx_create.md
driver/kubernetes/factory.go
driver/kubernetes/manifest/manifest.go

This PR covers https://github.com/docker/buildx/issues/210. 
I have tried to add a single `resources` driver-opt at first which could be used as following:
```
buildx create --driver kubernetes --driver-opt replicas=1,resources="requests.cpu=100m,requests.memory=100Mi,limits.cpu=100m,limits.memory=100Mi"
```
But then found out its not possible to nest keyvalues inside driver-opts at the moment (raised an issue for that https://github.com/docker/buildx/issues/617)
The next step could be https://github.com/docker/buildx/issues/377 where it was proposed to add a possibility of extending the YAML manifest.
I might take care of that later, but decided to add resource handling in a simple way for now.

feat: add resources handling to kubernetes driver

---

docs/reference/buildx_bake.md

Reflect the branch name change of the linked repository.
(It is automatically redirected, so the current link is also working.)
I just happened to open this link and checked the others, but they didn't seem to need similar modifications.

Minor fix to links in the document

---

build/build.go

Avoid doing a build if we cannot load the images at the end.
This doesn't really fix anything but at least users will see the error right away and not after a potentially long build.

Fail fast on multi platform build with load

---

.github/workflows/build.yml
Dockerfile

Dockerfile: enable windows/arm64

---

commands/bake.go
commands/build.go
docs/reference/buildx_bake.md
docs/reference/buildx_build.md

Add `metadata-file` flag

---

.github/workflows/build.yml
README.md

Fixes #647
Could be used like this:
```Dockerfile
FROM docker
COPY --from=docker/buildx:latest /buildx /usr/libexec/docker/cli-plugins/docker-buildx
```
e.g. https://hub.docker.com/r/crazymax/buildx/tags?page=1&ordering=last_updated
cc @chris-crone 

Create buildx image

---

.dockerignore
.github/workflows/build.yml
.gitignore
hack/release

Also remove unused `TAG` env var and wrap binaries in shell script.

Ignore release-out folder

---

bake/bake.go
bake/bake_test.go
bake/hcl_test.go
bake/hclparser/hclparser.go
commands/bake.go

fix #641 
Allows accessing the main context for bake command from bake
file that has been imported remotely.
```bash
{
"target": {
"binary": {
"context": "git:/github.com/docker/cli",
"args": {
"BASE_VARIANT": "alpine",
"GO_STRIP": "",
"VERSION": ""
},
"target": "binary",
"platforms": [
"local"
],
"output": [
"build"
]
}
}
}
/tmp/a # touch foo bar
/tmp/a # docker buildx bake "git://github.com/tonistiigi/buildx#remote-test"
...
> [4/4] RUN ls -l && stop:
#9 0.207 total 0
#9 0.207 -rw-r--r--    1 root     root             0 Jul 13 03:39 bar
#9 0.207 -rw-r--r--    1 root     root             0 Jul 13 03:39 foo
#9 0.207 /bin/sh: stop: not found
...
#8 0.232 -rw-r--r--    1 root     root          1893 Jul 13 03:58 poule.yml
#8 0.232 drwxr-xr-x    7 root     root …
```

bake: allow BAKE_CMD_CONTEXT builtin var

---

commands/rm.go
commands/stop.go
docs/reference/buildx_rm.md
driver/docker-container/driver.go
driver/docker/driver.go
driver/driver.go
driver/kubernetes/driver.go

Retain BuildKit state inside a named volume if the container is removed for the `docker-container` driver. `--volume` flag has also been added to the `rm` command to be able to force volume removal.

Keep BuildKit state in a volume

---

build/build.go

maybe fix https://github.com/docker/buildx/issues/675
I have another issue
With multi-node builder, but single platform build `buildx build --platform=linux/amd64`, will cause the nil issue too

fix: should ignore nil client

---

commands/build.go
docs/reference/buildx_bake.md
docs/reference/buildx_build.md

This PR reverts `BUILDX_PROGRESS_DEFAULT` env var that was introduced in #504 because it was already available through #69 with `BUILDKIT_PROGRESS` env var.
Docs have also been updated as stipulated in https://github.com/docker/buildx/issues/62#issuecomment-886162128

Duplicated progress env var

---

.github/workflows/build.yml

https://github.com/codecov/codecov-action#%EF%B8%8F--deprecration-of-v1

Bump to codecov/codecov-action v2

---

docs/reference/buildx_build.md

Example with gha cache

---

bake/bake.go
bake/bake_test.go
commands/bake.go
docs/reference/buildx_bake.md

Fixes #183
```yaml
services:
addon:
build:
context: .
dockerfile: ./Dockerfile
args:
CT_ECR: foo
CT_TAG: bar
image: ct-addon:bar
environment:
- NODE_ENV=test
- AWS_ACCESS_KEY_ID=dummy
- AWS_SECRET_ACCESS_KEY=dummy
aws:
build:
dockerfile: ./aws.Dockerfile
args:
CT_ECR: foo
CT_TAG: bar
image: ct-fake-aws:bar
```
```console
{
"group": {
"default": [
"aws",
"addon"
]
},
"target": {
"addon": {
"dockerfile": "./Dockerfile",
"args": {
"CT_ECR": "foo",
"CT_TAG": "bar"
},
"tags": [
"ct-addon:bar"
]
},
"aws": {
"context": "../../../tools/mock_servers/fake_aws",
"dockerfile": "./Dockerfile",
"args": {
"CT_ECR": "foo",
"CT_TAG": "bar"
},
"tags": [
"ct-fake-aws:bar"
]
}
}
}
```
```console
$ docker buildx bake addon --print
{
"target": {
"addon": { …
```

bake: print default group

---

commands/create.go
commands/inspect.go
commands/util.go
docs/reference/buildx_create.md

Fixes #189
Allow booting builder after creation with `docker buildx create --bootstrap ...`.
~Also adds `buildx start` command.~

Allow booting builder after creation

---

bake/compose.go
bake/compose_test.go
docs/reference/buildx_bake.md

Ref. compose-spec/compose-spec#120 https://github.com/docker/buildx/issues/183#issuecomment-894698860
Might also need to update the [compose-cli build options](https://github.com/docker/compose-cli/blob/fff0ed2bcd4660454f83e31217bf19ebdf282e4b/pkg/compose/build.go#L255-L288) to handle `x-bake` in a follow-up.
cc @chris-crone 

bake: `x-bake` extension field with compose

---

bake/remote.go
build/build.go
build/url.go
commands/util.go
driver/driver.go

fixes #737
Context passed to `NewClient` should not be canceled after `NewClient` returns but client is still used. Another way would be to create a new context internally and block the `Done` channel but I think passing separate context is clearer.

use long-running context for client initialization

---

driver/docker-container/driver.go

fixes https://github.com/docker/buildx/issues/749
The container-driver creates a Linux container (as there currently isn't a
Windows version of buildkitd). However, the defaults are platform specific.
Buildx was using the defaults from the buildkit `util/appdefault' package,
which resulted in Buildx running on a Windows client to create a Linux
container that used the Windows location, which causes it to fail:
invalid mount config for type "volume": invalid mount path: 'C:/ProgramData/buildkitd/.buildstate' mount path must be absolute
This patch hard-codes the destination to the default Linux path.

container-driver: fix volume destination for cache

---

.github/workflows/build.yml
.github/workflows/validate.yml
driver/docker-container/driver.go

pick #751
The container-driver creates a Linux container (as there currently isn't a
Windows version of buildkitd). However, the defaults are platform specific.
Buildx was using the defaults from the buildkit `util/appdefault' package,
which resulted in Buildx running on a Windows client to create a Linux
container that used the Windows location, which causes it to fail:
invalid mount config for type "volume": invalid mount path: 'C:/ProgramData/buildkitd/.buildstate' mount path must be absolute
This patch hard-codes the destination to the default Linux path.
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
(cherry picked from commit 93867d02f0a989f084e54d7133371f583a4d3c5e)

[v0.6] container-driver: fix volume destination for cache

---

commands/bake.go
docs/reference/buildx_bake.md
docs/reference/docker_buildx_bake.yaml

Add built-in variable `BAKE_LOCAL_PLATFORM` that returns the current platform's default platform specification (e.g. `linux/amd64`).

Built-in variable `BAKE_LOCAL_PLATFORM`

---

Makefile
build/build.go
commands/build.go
docs/reference/buildx_build.md

See #621.  I needed this in order to script logic of the following structure (where I didn't want to use a temporary file on disk for `--iidfile`):
```
$ image=$(docker build --quiet .)
$ docker run $image
```
This worked _unless_ someone had installed `buildx` in place of `docker build` (as I had 😛 ) in which case the `image` was an empty string and the `docker run` failed catastrophically.

Implement `--quiet` support

---

Makefile
docker-bake.hcl
hack/dockerfiles/vendor.Dockerfile

Just a fancy tool to be able to check updates for direct dependencies:
```shell
$ make mod-outdated
...
#12 21.34 +------------------------------------+-----------------------------------------------------+------------------------------------+--------+------------------+
#12 21.34 |               MODULE               |                       VERSION                       |            NEW VERSION             | DIRECT | VALID TIMESTAMPS |
#12 21.34 +------------------------------------+-----------------------------------------------------+------------------------------------+--------+------------------+
#12 21.34 | github.com/compose-spec/compose-go | v0.0.0-20210729195839-de56f4f0cb3c                  | v0.0.0-20210901090333-feb401cda7f7 | true   | true             |
#12 21.34 | …
```

Mod outdated

---

docs/reference/buildx_build.md
docs/reference/buildx_create.md

relates to https://github.com/docker/docker.github.io/pull/13514
- ./_site/engine/reference/commandline/buildx_build/index.html
*  linking to internal hash #--buildkitd-flags-flags that does not exist (line 904)
<a href="/engine/reference/commandline/buildx_create/#--buildkitd-flags-flags"></a>
- ./_site/engine/reference/commandline/buildx_create/index.html
*  linking to internal hash #--buildkitd-flags-flags that does not exist (line 350)
<a href="#--buildkitd-flags-flags"></a>
*  linking to internal hash #--config-file that does not exist (line 336)
<a href="#--config-file"></a>
*  linking to internal hash #--config-file that does not exist (line 336)
<a href="/engine/reference/commandline/buildx_build/#--load"></a>
*  linking to internal hash #--load that does not exist (line 369)
<a …

docs: fix some broken anchors

---

commands/util.go

util: support load Colon-separated KUBECONFIG

---

bake/bake.go
bake/bake_test.go
commands/bake.go
util/buildflags/output.go

Currently, using `bake --push` will replace the target definition with `type=registry`. This means that if the definition defined an output then it gets cleared and completely overwritten.
I think the basis of this refactor can also be used to implement additional operators like `--set key+=value` in the future.

bake: fix using push override with output definition

---

.github/workflows/e2e.yml
Makefile
hack/test-driver

Follow-up #691 
This workflow handles multi-matrix jobs with:
* buildkit image (latest and master)
* buildkit cfg
* driver (docker, container and kubernetes)
* multi-node (restrict to kubernetes atm)

Driver e2e tests

---

docs/reference/buildx_create.md
driver/docker-container/driver.go
driver/docker-container/factory.go

Previously build containers created by the `docker-container` driver were in the default parent cgroup, along with non-build containers. This made it hard to apply resource limits to all the builds on a machine.
This PR adds a `--driver-opt cgroup-parent=CGROUP` to allow the cgroup to be customised. A default value of `/docker/buildx` is  set.

docker-container: place build containers in a separate cgroup

---

bake/remote.go

while investigating with the current state of `git://` protocol (https://github.blog/2021-09-01-improving-git-protocol-security-github/) I encounter an issue with bake and the ability to use a remote definition using https:
```
$ docker buildx bake "https://github.com/docker/cli.git#master" --print
#1 [internal] load remote build context
#1 DONE 0.0s
error: failed to parse https://github.com/docker/cli.git#master: parsing yaml: yaml: line 99: mapping values are not allowed in this context, parsing hcl: https://github.com/docker/cli.git#master.hcl:225,21-22: Unsupported operator; Bitwise operators are not supported. Did you mean boolean AND ("&&")?, and 75 other diagnostic(s)
```
With this PR we now detect if a git-like url is used:
```
$ docker buildx bake …
```

bake: fix protocol detection

---

build/build.go

I can't see any reason for this early return. It breaks using iidfile together with push on multi-node case.

build: fix setting iidfile with multi-node push

---

commands/util.go
driver/docker-container/driver.go
driver/docker/factory.go
driver/kubernetes/driver.go
driver/kubernetes/factory.go
driver/kubernetes/manifest/manifest.go
driver/manager.go
store/nodegroup.go
util/confutil/container.go

Files can be reused when container needs to be booted again.
The second commit enables config files for k8s. @morlay PTAL. If something is wrong we can remove the second commit or you can push a fix to this PR.

store snapshot of config files on create

---

build/build.go
commands/bake.go
commands/build.go
commands/util.go
util/confutil/config.go

This allows separating building different projects so they don't rewrite each other's local source destination for better performance.

build: set local sharedkey per project basename

---

build/build.go
commands/bake.go
commands/build.go
commands/create.go
commands/imagetools/create.go
commands/imagetools/inspect.go
commands/imagetools/root.go
commands/inspect.go
commands/ls.go
commands/rm.go
commands/root.go
commands/stop.go
commands/use.go
commands/util.go
store/storeutil/storeutil.go
util/imagetools/inspect.go
util/resolver/resolver.go
vendor/github.com/moby/buildkit/cmd/buildkitd/config/config.go
vendor/github.com/moby/buildkit/cmd/buildkitd/config/gcpolicy.go
vendor/github.com/moby/buildkit/cmd/buildkitd/config/gcpolicy_unix.go
vendor/github.com/moby/buildkit/cmd/buildkitd/config/gcpolicy_windows.go
vendor/github.com/moby/buildkit/cmd/buildkitd/config/load.go
vendor/github.com/moby/buildkit/util/resolver/config/config.go
vendor/modules.txt

allow multi-node push and imagetools to use custom registry config

---

Dockerfile

Normally I wouldn't optimize for storage instead of debuggability but we seem to do it for some other binaries so better to be consitent.

Dockerfile: strip binary by default

---

docs/reference/buildx_bake.md

relates to https://github.com/docker/docker.github.io/pull/13488#issuecomment-961678105

fix typo in docs

---

commands/bake.go
commands/build.go
commands/create.go
commands/prune.go
commands/root.go
docs/reference/buildx_build.md
go.mod
go.sum
vendor/github.com/docker/cli-docs-tool/annotation/annotation.go
vendor/github.com/docker/cli-docs-tool/clidocstool.go
vendor/github.com/docker/cli-docs-tool/clidocstool_md.go
vendor/github.com/docker/cli-docs-tool/clidocstool_yaml.go
vendor/modules.txt

Usage output on terminal for some flags are currently broken since changes to improve markdown output for docs reference. This is because [backticks are interpreted by pflag to specify a flag type](https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/flag.go#L568-L610).
Currently:
```
$ docker buildx bake --help
Usage:  docker buildx bake [OPTIONS] [TARGET...]
Build from a file
Aliases:
bake, f
Options:
--builder string                      Override the configured builder instance
-f, --file stringArray                    Build definition file
--load --set=*.output=type=docker     Shorthand for --set=*.output=type=docker
--metadata-file string                Write build result metadata to the file
--no-cache                            Do not use cache when building …
```

cli: fix flags usage

---

bake/bake.go
bake/bake_test.go
commands/bake.go
docs/reference/buildx_bake.md

fixes #856 
targets groups are not correctly rendered while being printed with `bake --print` so output cannot be reused.
```hcl
// docker-bake.hcl
group "default" {
targets = ["image"]
}
target "image" {
inherits = ["image"]
output = ["type=docker"]
}
```
```json
// docker-bake.json
{
"group": {
"default": {
"targets": [
"image"
]
}
},
"target": {
"image": {
"output": [
"type=docker"
]
}
}
}
```
```yaml
services:
addon:
build:
context: .
dockerfile: ./Dockerfile
args:
CT_ECR: foo
CT_TAG: bar
image: ct-addon:bar
environment:
- NODE_ENV=test
- AWS_ACCESS_KEY_ID=dummy
- AWS_SECRET_ACCESS_KEY=dummy
aws:
build:
dockerfile: ./aws.Dockerfile
args:
CT_ECR: foo
CT_TAG: bar
image: ct-fake-aws:bar
```
___
```console
$ docker buildx bake -f …
```

bake: fix print output

---

docs/reference/buildx_bake.md

In addition to HCL, variables can also be defined in json.
I believe it might be useful, yet I did not see it documented anywhere. The solution is based on Hashicorp Packer documentation.

add note about variable syntax in json

---

commands/diskusage.go
commands/prune.go
go.mod
vendor/modules.txt

`LAST ACCESSED` is currently not displayed when `docker buildx du` is typed:
```console
$ docker buildx du
ID                                                                      RECLAIMABLE     SIZE            LAST ACCESSED
tfh97mauvv969bbf9alj95dnj*                                              true            528.48MB
zkflab60sf3z1b8lmbik9dyb1                                               true            454.48MB
3jef3cg8lwudcluhb5nahsvif*                                              true            398.66MB
ri0p36t0xhc6yor2304x07h3d*                                              true            160.39MB
5mk6axu5qiga7f6z750nayckn*                                              true            62.00MB
wd188ekm0g89savkrot6cjkf0*                                              true …
```

disk usage: last accessed not displayed

---

bake/bake.go

closes #833
Accept bake build definition file from stdin with `-f -`.
Signed-off-by: Eliott Wiener <eliottwiener@gmail.com>

bake: build definition file via stdin

---

README.md
docs/reference/buildx_bake.md

follow-up https://github.com/docker/buildx/pull/822#issuecomment-958006458
https://github.blog/2021-09-01-improving-git-protocol-security-github/
```
#1 0.234 fatal: remote error: 
#1 0.234   The unauthenticated git protocol on port 9418 is no longer supported.
#1 0.234 Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

docs: fix git protocol

---

bake/bake.go

Missing ignore for `NetworkMode` field. Relates to #863.

bake: ignore NetworkMode field for json and hcl

---

bake/bake.go
bake/bake_test.go

fixes #877 
@tonistiigi Also found an odd case when a group and target can have the same name without erroring:
```hcl
group "foo" {
targets = ["image"]
}
target "foo" {
dockerfile = "bar"
}
target "image" {
dockerfile = "test"
}
```
```console
$ docker buildx bake --print foo
{
"group": {
"default": {
"targets": [
"image"
]
}
},
"target": {
"image": {
"dockerfile": "test"
}
}
}
```
Not sure if it's expected?

bake: fix groups print

---

driver/docker-container/driver.go
driver/docker-container/factory.go

Set `UsernsMode="host"` only when the daemon is running in userns-remapping mode.
Fix #561
The issue will be also fixed in moby/moby#43084 (Docker 20.10.13).
This buildx PR helps users of old releases of Docker.

docker-container: set UsernsMode only when needed

---

driver/docker-container/driver.go
driver/docker-container/factory.go

[v0.7 backport] docker-container: set UsernsMode only when needed

---

commands/build.go
commands/root.go
go.mod
util/logutil/filter.go
util/logutil/pause.go
util/progress/printer.go
vendor/modules.txt

In addition to showing warning where it happens show a summary after build has completed.
```
> docker buildx build .
...
1 warning found (use --debug to expand):
- Empty continuation line found in: RUN date &&     sleep 4 &&     date && echo $GREETING
```
with `--debug`
```
...
1 warning found:
- Empty continuation line found in: RUN date &&     sleep 4 &&     date && echo $GREETING
Empty continuation lines will become errors in a future release
More info: https://github.com/moby/moby/pull/33719
Dockerfile:11
9 |         sleep 4 && \
10 |     
11 | >>>     date && echo $GREETING
12 |     RUN true
13 |      
```
Also fix the issue with progressbar and logging both printing to terminal at same time. Now logs are buffered while the terminal is …

Show summary of build warnings.

---

bake/bake.go
bake/bake_test.go

follow-up #881
If a target has the same name as a group, it's resolution is skipped.
```hcl
group "foo" {
targets = ["foo"]
}
target "foo" {
dockerfile = "bar"
}
```
```
$ docker buildx bake foo --print
{
"group": {
"default": {
"targets": [
"foo"
]
}
},
"target": {}
}
```
Now:
```
$ docker buildx bake foo --print
{
"group": {
"default": {
"targets": [
"foo"
]
}
},
"target": {
"foo": {
"dockerfile": "bar"
}
}
}

bake: fix group resolution

---

bake/compose.go
bake/compose_test.go
go.mod
go.sum
vendor/github.com/compose-spec/compose-go/loader/full-example.yml
vendor/github.com/compose-spec/compose-go/loader/loader.go
vendor/github.com/compose-spec/compose-go/loader/merge.go
vendor/github.com/compose-spec/compose-go/loader/volume.go
vendor/github.com/compose-spec/compose-go/template/template.go
vendor/github.com/compose-spec/compose-go/types/project.go
vendor/github.com/compose-spec/compose-go/types/types.go
vendor/github.com/compose-spec/godotenv/godotenv.go
vendor/github.com/compose-spec/godotenv/parser.go
vendor/modules.txt

fixes #903 
Upgrade compose-go to v1.0.8 to fix the issue and add test.
Last commit allows to set args from service environment which was not covered previously. Let me know if you want this in a dedicated pr.

compose: fix env

---

.github/workflows/build.yml

follow-up https://github.com/moby/buildkit/pull/2491#issuecomment-1010123172
Our actual pipeline is using a bleeding edge release of the BuildKit image which might introduce bugs unrelated to buildx like https://github.com/docker/buildx/runs/4777886890?check_suite_focus=true#step:7:135:
```
error: failed to solve: process "/bin/sh -c set -x; xx-go build -ldflags \"$(cat /tmp/.ldflags) ${LDFLAGS}\" -o /usr/bin/buildx ./cmd/buildx &&   xx-verify --static /usr/bin/buildx" did not complete successfully: failed to mount /tmp/buildkit-mount2802602399: [{Type:overlay Source:overlay Options:[index=off workdir=/var/lib/buildkit/runc-overlayfs/snapshots/snapshots/24/work upperdir=/var/lib/buildkit/runc-overlayfs/snapshots/snapshots/24/fs lowerdir=/var/lib/buildkit/runc-overlayfs/snapshots/snapshots/ …
```

ci: build with stable buildkit image

---

bake/bake.go
bake/bake_test.go

fixes #912 
After first pass inheritance is lost for the next targets in a group.

bake: keep target inheritance

---

build/build.go
commands/build.go
docs/reference/buildx_build.md
go.mod
vendor/modules.txt

This PR enables setting named Dockerfile contexts https://github.com/moby/buildkit/pull/2521 from buildx.
There were some concerns over the flag `--context` with alternatives `--build-context` and `--stage` proposed. This has been updated to `--stage`.
```
buildx build --stage alpine=docker-image://alpine:1.12 .
buildx build --stage project2=path/to/source .
buildx build --stage buildkit-src=https://github.com/moby/buildkit .
```
I'll implement bake support separately. Eventually, it should be possible to set bake targets also this way.
@AkihiroSuda @crazy-max

build: support for named contexts(stages)

---

commands/root.go
util/logutil/filter.go
util/logutil/format.go

relates to https://github.com/docker/buildx/issues/764#issuecomment-961198793
closes #813 
also while doing further tests for https://github.com/docker/cli/pull/3314 I encounter a case where some logs don't match the output format from docker/cli:
```shell
$ docker build ...
WARNING: Error loading config file: ...
WARN[0000] No output specified for docker-container driver. Build result will only remain in ...
```
now using cli writers for logrus and simplify output format for parity:
```shell
$ docker build ...
WARNING: Error loading config file: ...
WARNING: No output specified for docker-container driver. Build result will only remain in ...
```

root: filter out useless commandConn.CloseWrite warning message

---

bake/bake.go
bake/bake_test.go
bake/compose.go
bake/compose_test.go
bake/hcl.go
bake/hclparser/hclparser.go

fixes #888
This fix adds a restriction `[a-zA-Z0-9_-]+`
for target name. This is pretty much the same as the
container name restriction in moby.
___
```yaml
services:
a.bc:
build:
context: .
```
```shell
error: invalid service name "a.bc": only "[a-zA-Z0-9_-]+" are allowed
```
___
```hcl
// docker-bake.hcl
group "default" {
targets = ["a.bc"]
}
target "a.bc" {
context = "."
}
```
```shell
docker-bake.hcl:5
3 |     }
4 |
5 | >>> target "a.bc" {
6 |       context = "."
7 |     }
error: docker-bake.hcl:5,8-14: Invalid name; only "[a-zA-Z0-9_-]+" are allowed
```

bake: restrict target name

---

commands/rm.go
commands/util.go
docs/reference/buildx_rm.md

fixes #851 
Add `--inactive` to be able to remove nodes that are not in running state. This will also remove builders that don't have any node left available after the process.

cli: add --all-inactive for rm command

---

commands/bake.go
commands/build.go
commands/util.go
util/progress/printer.go

- Wanted to just provide `io.Writer` in the plain log output case

Relax to io.Writer requirement for NewPrinter

---

bake/bake.go
bake/bake_test.go
build/build.go
docs/reference/buildx_bake.md
util/waitmap/waitmap.go
util/waitmap/waitmap_test.go

fixes #926
Enable using named contexts in bake targets. The naming is consistent with build args, and `--build-context` and `--build-arg` are similar and both take key-value pairts.
~Still working on creating contexts from other targets that is a bit complex. That can be a follow-up PR.~ Added to same PR. Targets can be linked with `target:` prefix.

bake: add named contexts keys

---

commands/build.go
docs/reference/buildx_build.md

fixes #809 
fixes #927 
cc @basicdays @thaJeztah 

docs: secret usage examples

---

build/build.go

fixes #952
In the case `waitContextDeps` returned error it left the waitgroup block and process deadlocked.

build: fix deadlock on handling deps errors

---

build/build.go
commands/util.go
store/storeutil/storeutil.go

fixes #947
For backward compatibility with docker build.

set build-args from docker proxy configuration

---

commands/bake.go
commands/build.go

Currently, the error was improved only for `build` command and not `bake` command.

bake: use better error in named contexts not supported

---

bake/bake.go
bake/bake_test.go
build/build.go
commands/build.go

- Update named context paths to be relative of remote inputs
- Add basic validation that named paths don't escape the current working directory when loaded from remote sources.

bake: additional support for named context on remote inputs

---

build/build.go

Fixes #978
This issue appears when building multiple targets with bake on a multi-node builder where some targets specify platforms and some don't.

build: fix multi-node builds with mixed platforms

---

build/build.go

fixes #420 
follow-up https://github.com/docker/buildx/pull/975#issuecomment-1053957423
repro https://github.com/crazy-max/buildx-buildkit-tests/runs/5374641648?check_suite_focus=true#step:7:2

build: return imageID when loading without docker driver

---

docs/reference/buildx_imagetools_inspect.md
util/imagetools/printers.go

follow-up #854
keep order from the manifest and also print formatted image config.

imagetools inspect: keep platform order

---

commands/bake.go

Metadata formatting should not depend on the number
of targets.
Reverts this change from https://github.com/docker/buildx/pull/946/files#diff-3f9c21dce82a82fae6d5ca096e77e5ddcf0eccd7051f815b452ec26fbfeb314bR154

bake: restore consistent output for metadata

---

build/build.go

closes #975
Set `containerimage.digest` with correct digest when image is pushed with moby. If `containerimage.digest` already exists, its value will be saved to `containerimage.config.digest` for backward compatibility with #980.
repro: https://github.com/crazy-max/buildx-buildkit-tests/runs/5440498633?check_suite_focus=true#step:7:153
In follow-up create the `imageid` output in our GitHub Action and also fix `digest` output. See https://github.com/docker/build-push-action/pull/569

build: set remote digest when pushed with docker driver

---

.golangci.yml
bake/bake.go
build/build.go
build/url.go
commands/imagetools/create.go
driver/docker-container/driver.go
driver/kubernetes/context/endpoint_test.go
driver/kubernetes/context/save.go
driver/manager.go
store/store.go
store/store_test.go
util/logutil/filter.go
util/progress/fromreader.go
util/progress/printer.go

The package has been deprecated since Go 1.16: https://go.dev/doc/go1.16#ioutil

Remove uses of deprecated io/ioutil

---

go.mod
go.sum
vendor/github.com/tonistiigi/fsutil/walker.go
vendor/modules.txt

#1004
(cherry picked from commit 111ea95629519085cbdc5c28e3e3c1dd1b38fc6f)

[v0.8] vendor: update fsutil to 9ed61262

---

go.mod
go.sum
vendor/github.com/docker/distribution/.mailmap
vendor/github.com/docker/distribution/Dockerfile
vendor/github.com/docker/distribution/README.md
vendor/github.com/docker/distribution/docker-bake.hcl
vendor/modules.txt

no significant changes to code we use, but the v2.8.0 module was borked
full diff: https://github.com/docker/distribution/compare/v2.8.0...v2.8.1

vendor: github.com/docker/distribution v2.8.1

---

commands/inspect.go

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
I've created a builder for an example to be able to test this feature by simply running the following commands:
```shell
$ docker buildx create --name buildkitd-rootless-nightly --driver-opt image=moby/buildkit:nightly-rootless
```
I got the following result:

feat: printing driver options

---

bake/bake.go
bake/compose.go
bake/compose_test.go

This is a hotfix for v0.8 to unblock release and
restore backward compatibility. More proper fix
coming later.
replaces #1012

[v0.8] bake: allow dot in target names for compose

---

bake/bake.go
bake/bake_test.go

fixes #1020 
when a group has already been visited, its resolution will be skipped on next iteration and therefore would fail to find the relevant target when nested groups calling the same target is being used in the definition.

bake: fix skipped group when already visited by another one

---

.github/workflows/build.yml
.github/workflows/e2e.yml
.github/workflows/validate.yml
Dockerfile
docker-bake.hcl
docs/reference/buildx_build.md
hack/dockerfiles/authors.Dockerfile
hack/dockerfiles/docs.Dockerfile
hack/dockerfiles/lint.Dockerfile
hack/dockerfiles/vendor.Dockerfile

follow-up #919
needs to be addressed when 0.8 GA (and available on GitHub runners). Also update our dockerfiles to use edge frontend image.

chore: use no-cache-filter for outdated stage

---

go.mod
go.sum
vendor/github.com/moby/buildkit/util/imageutil/buildinfo.go
vendor/github.com/moby/buildkit/util/progress/progressui/printer.go
vendor/modules.txt

[v0.8] vendor: update buildkit to 10e6f94b

---

docs/reference/buildx_create.md
driver/kubernetes/factory.go
driver/kubernetes/manifest/manifest.go

This PR is to add support for Kubernetes tolerations. Should support all current tolerations options and adding multiple tolerations. This should cover the use cases listed in #377, but it doesn't add the full manifests support.
Adding full support to manifests would be a much more flexible option, but this should solve the main pain points listed in that ticket.

feat: add tolerations handling to kubernetes driver

---

docs/reference/buildx_create.md
driver/kubernetes/manifest/manifest.go

Kubernetes added the official `securityContext.seccompProfile` support in Kubernetes 1.19.
Seccomp is still disabled by default.
The legacy `container.seccomp.security.alpha.kubernetes.io/<PODNAME>` annotation has been deprecated and will be unsupported in Kubernetes 1.25.
https://kubernetes.io/docs/tutorials/security/seccomp/
A test cluster can be created with the following minikube command:
```
minikube start --feature-gates SeccompDefault=true --extra-config kubelet.seccomp-default=true
```
Related to:
- moby/buildkit#2782

kubernetes: replace deprecated seccomp annotations with securityContext

---

commands/inspect.go

follow-up https://github.com/docker/buildx/pull/1003#issuecomment-1084286643
current behavior:
```
Name:   builder
Driver: docker-container
Nodes:
Name:            builder0
Endpoint:        unix:///var/run/docker.sock
Driver Options:  env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
,                env.BUILDKIT_STEP_LOG_MAX_SPEED=-1
,                env.JAEGER_TRACE=localhost:6831
,                image=moby/buildkit:master
,                network=host
Status:          running
Flags:           --debug --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
Platforms:       linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
```
now:
```
Name:   builder …
```

inspect: fix printing of driver options

---

driver/kubernetes/factory.go

Only change the image to the default rootless image when using the
--rootless option if the image has not already customized with the
--image option.
Fix #938
Signed-off-by: Douglas Borg <dougborg@apple.com>

Only set default rootless image if it is not already customized

---

commands/imagetools/create.go
commands/imagetools/inspect.go
commands/imagetools/root.go
commands/root.go

The --builder flag was being ignored by imagetools because of pointer
problems. Essentially, because the root cmds aren't parsed immediately,
we need to pass a pointer to the builder string so that it can be
updated before the RunE function gets called.

imagetools: respect --builder flag

---

bake/compose.go
bake/compose_test.go
go.mod
go.sum
vendor/github.com/compose-spec/compose-go/loader/full-example.yml
vendor/github.com/compose-spec/compose-go/loader/loader.go
vendor/github.com/compose-spec/compose-go/loader/validate.go
vendor/github.com/compose-spec/compose-go/schema/compose-spec.json
vendor/github.com/compose-spec/compose-go/types/project.go
vendor/github.com/compose-spec/compose-go/types/types.go
vendor/modules.txt

fixes #1060 
Adds support for compose build secrets with bake. Needs to vendor compose-go https://github.com/compose-spec/compose-go/compare/v1.2.1...v1.2.4. See spec https://github.com/compose-spec/compose-spec/blob/master/build.md#secrets.
We can keep the [`x-bake` secret field](https://github.com/docker/buildx/blob/master/docs/reference/buildx_bake.md#extension-field-with-compose) for now imo.
Also [env secret type](https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#env) is supported with the following format:
```yaml
services:
webapp:
build:
context: .
secrets:
- ENV_TOKEN
secrets:
ENV_TOKEN: {}
```
I will review our documentation about bake and create dedicated guides for compose and hcl formats for this kind of use cases in a follow-up.
cc @glours …

bake: support compose build secrets

---

commands/create_test.go
docs/reference/buildx_create.md
driver/kubernetes/factory.go
driver/kubernetes/factory_test.go

Followup for #1045. Updates the docs with correct examples on how to quote multiple node selectors or tolerations and removes unquoting from the tolerations, since the CSV parser that parses the driver-opts already handles unquoting.

Fix tolerations not parsing its options correctly, update docs regarding quoted driver options

---

bake/hcl_test.go
bake/hclparser/hclparser.go

fixes #756 
fixes docker/bake-action#61
while checking the issue reported in docker/bake-action#61, I found out that the HCL diagnostic being reported was wrong:
```
/usr/bin/docker buildx bake --file ./docker-bake.hcl --file /tmp/docker-metadata-action-GGKyIw/docker-metadata-action-bake.json --file /tmp/docker-metadata-action-fZ5d0s/docker-metadata-action-bake.json --file /tmp/docker-metadata-action-toPOSl/docker-metadata-action-bake.json --file /tmp/docker-metadata-action-Cqo0nf/docker-metadata-action-bake.json --metadata-file /tmp/docker-build-push-Rpx0C2/metadata-file binary dind proxy tools --print
./docker-bake.hcl:2
1 |     // filled by GitHub Actions
2 | >>> target "docker-metadata-k3d" {}
3 |     target "docker-metadata-k3d-dind" {}
4 |     target …
```

bake: merge targets and vars from multiple JSON files

---

cmd/buildx/main.go
cmd/buildx/tracing.go
commands/root.go

when buildx is invoked directly without the docker cli (standalone) and an error occurs during the build, the error message is returned along with the cobra help usage:
```Dockerfile
FROM qsdqsdalpine
RUN echo "Hello world!"
```
```
$ ~/.docker/cli-plugins/docker-buildx build .
...
#4 [auth] library/qsdqsdalpine:pull token for registry-1.docker.io
#4 DONE 0.0s
#3 [internal] load metadata for docker.io/library/qsdqsdalpine:latest
#3 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
------
> [internal] load metadata for docker.io/library/qsdqsdalpine:latest:
------
Error: failed to solve: qsdqsdalpine: pull access denied, repository does not exist or may require authorization: server message: …
```

cli: fix standalone command behavior

---

.github/workflows/e2e.yml

Avoid building buildx for each matrix input to save some compute and also avoid issues like https://github.com/docker/buildx/runs/6208393943?check_suite_focus=true
```
#3 resolve image config for docker.io/docker/dockerfile:1.4
#3 ERROR: failed to do request: Head "https://registry-1.docker.io/v2/docker/dockerfile/manifests/1.4": net/http: TLS handshake timeout
```
The new workflow will build buildx once and each matrix input will download the artifact.
cc @jedevc 

ci: enhance e2e workflow

---

bake/hcl_test.go
bake/hclparser/hclparser.go

Body.JustAttributes cannot distinguish between blocks and attributes for JSON files, so the variable block could be included in the list of attributes returned.
This patch ensures that JSON and HCL files behave the same way by removing all known block types first, from the provided config schema and then from a generated definitions schema.
Fixes #1051

hclparser: strip out blocks for json files

---

docs/guides/cni-networking.md
docs/guides/custom-network.md
docs/guides/custom-registry-config.md
docs/guides/opentelemetry.md
docs/guides/registry-mirror.md
docs/guides/resource-limiting.md

Fix guides docs so we can include them on docs.docker.com.

docs: fix guides for docs.docker.com

---

docs/guides/remote-builder.md

Added basic scenarios for:
- Connecting over a basic unix socket
- Connecting to a docker buildkit container
- Connecting to a kubernetes buildkit deployment

Add remote driver guide

---

commands/create.go
docs/reference/buildx_create.md
util/confutil/config.go

fixes https://github.com/docker/setup-buildx-action/issues/127
if configuration file is not specified, will look for one by default in:
* `$BUILDX_CONFIG/buildkitd.default.toml`
* `$DOCKER_CONFIG/buildx/buildkitd.default.toml`
* `~/.docker/buildx/buildkitd.default.toml`
this can be useful when a user session should inherit from the same configuration when a builder is created without bothering specifying the config path.

create: load default buildkit config if none specified

---

Dockerfile

optimize test stage to use gobase as based stage instead of build one. also move test step in our ci workflow to a dedicated job.

dockerfile: enhance test stage

---

commands/create.go
commands/ls.go
commands/util.go

```
$ docker context create foo
foo
Successfully created context "foo"
$ docker buildx create --name foo
foo
```
```
$ docker buildx ls
NAME/NODE        DRIVER/ENDPOINT                        STATUS                 PLATFORMS
builder2 *       docker-container
builder20      unix:///var/run/docker.sock            running                linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
foo              docker-container
foo0           unix:///var/run/docker.sock            inactive
desktop-linux                                           protocol not available
desktop-windows                                         protocol not available
foo              docker
foo …
```

ls: dedup instances from store and context

---

.golangci.yml
build/build.go

Resolves the following message in golangci output:
> The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.
Additionally, fix a minor linting issue discovered by revive.

Update golint to revive

---

docs/reference/buildx_inspect.md

Documentation gap was found in issue #1105. In `buildx inspect` command output, asterisks `*` next to platforms listed indicate such platforms had been set manually set in `buildx create`.
This behavior was previously not documented, therefore this PR updates documentation to include it.

Clarify inspect documentation

---

bake/bake.go
build/build.go

fixes #968
fix the issue where no output warning message is being displayed for linked targets and also enhance this message to display which targets don't have an output specified.
```hcl
target "base" {
dockerfile = "baseapp.Dockerfile"
args = {
basefoo = "bar"
}
}
target "base2" {
dockerfile = "baseapp.Dockerfile"
args = {
basefoo = "bar3"
}
}
target "app" {
contexts = {
baseapp = "target:base"
}
}
```
```dockerfile
FROM baseapp
RUN echo "Hello world"
```
```dockerfile
FROM alpine
WORKDIR /src
```
```console
$ docker buildx bake --set app.tags=user/app:latest --set app.output=type=cacheonly app
...
#5 [app 1/2] FROM docker.io/library/alpine@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
#5 resolve docker.io/library/alpine@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84 …
```

build: enhance warning message when no output specified

---

.github/workflows/build.yml
.github/workflows/e2e.yml
.github/workflows/validate.yml

follow-up https://github.com/moby/buildkit/pull/2899
add concurrency check in our workflows to ensure that only a single workflow using the same concurrency group will run at a time. it allows to reduce job build queue in our pipeline.
more info: https://docs.github.com/en/actions/using-jobs/using-concurrency

ci: add concurrency check

---

build/build.go
commands/build.go
go.mod
monitor/monitor.go
monitor/monitor_test.go

https://github.com/docker/buildx/issues/1104
This is a PoC of `--invoke` option to launch a container based on the build result.
Please give me feedbacks on the design of the monitor and CLI design.
This covers PR1 to PR3 of https://github.com/docker/buildx/issues/1104.
> PR1
> Add possibility to interactively run a process using the NewContainer API after the build has completed. The build will run with the progressbar until completion. Progressbar will finish and container will be launched. Container redirects all stdio and signals. TTY is enabled if user enabled TTY for main process.
> PR2
> Add "monitor mode" to the interactive process. When running an interactive process, the user can switch between to process io and monitor process io. Similar to QEMU monitor mode. In monitor mode …

Add `--invoke` option to launch a container from the build result

---

bake/bake_test.go
bake/compose.go
bake/compose_test.go

fixes #1172
Consistency check added in https://github.com/docker/buildx/pull/87 is already handled by the library: https://github.com/compose-spec/compose-go/blob/c45b40b31e66dbc3966642803d133bba33680b21/loader/validate.go#L31-L33
Since we have moved to the compose-go library, we can skip the consistency check, remove the dup check in bake as well and use our own "less-strict" consistency check in bake to be aligned with the HCL format:
```yaml
services:
test:
build:
context: .
tags:
- docker.io/username/webapp:latest
entrypoint: echo 1
```
```yaml
services:
test:
entrypoint: echo 2
```
```console
$ docker buildx bake -f docker-compose.yml test --print
{
"group": {
"default": {
"targets": [
"test"
]
}
},
"target": {
"test": {
"tags": [ …
```

bake: fix compose consistency check

---

driver/kubernetes/podchooser/podchooser.go

This prevents the fall-through to the panic from division by zero in the modulus below, and presents a neater error to the user, so that scenarios like #961 provide a non-panic error.

Add error in kubernetes driver when no pods available

---

docs/guides/remote-builder.md

Ensure that buildx is always used as a docker and correct the invalid `buildx ls` output.

docs: fixup remote builder typos

---

docs/guides/kubernetes-builder.md

This PR introduces a new kubernetes builder guide to match the remote builder guide previously added in #1093.
The content consolidates some of the information already present in the command line reference, and discussions like https://github.com/docker/buildx/discussions/685.
I think this should be a good first pass of the guide, we might want to follow-up and add some more complex deployment scenarios, though I'm not as familiar with those, so will likely leave them to someone with some more experience there :smile:

docs: add new kubernetes build driver docs

---

build/build.go
docs/reference/buildx_build.md
go.mod
go.sum
vendor/modules.txt

Adds to buildx the oci-layout: build-context capabilities added to buildkit in [buildkit 2827](http://github.com/moby/buildkit/pull/2827).
Recommended by @tonistiigi . Remains incomplete, some things I wasn't sure about. Will comment inline.

add support for oci-layout build-context

---

docs/reference/buildx_build.md

follow-up https://github.com/docker/docker.github.io/pull/14948

docs: replace links with ones from docs.docker.com

---

docs/guides/color-output.md
docs/reference/buildx_bake.md
docs/reference/buildx_build.md

follow-up #1226
behavior lgtm:
but looks like the [example in README of BuildKit repo](https://github.com/moby/buildkit#color-output-controls) is not correct:
```console
$ BUILDKIT_COLORS="run=blue;cancel=yellow;warn=orange;error=123,12,0" docker buildx bake
WARN[0000] Could not parse BUILDKIT_COLORS component: run=blue;cancel=yellow;warn=orange;error=123,12,0  error="A valid entry must have exactly two fields"
```
should be `run=blue:cancel=yellow:warn=orange:error=123,12,0` as correct separator but then:
```console
$ BUILDKIT_COLORS="run=blue:cancel=yellow:warn=orange:error=123,12,0" docker buildx bake
WARN[0000] Unknown color value found in BUILDKIT_COLORS: warn=orange  error="Colors must be a name from the pre-defined list or a valid 3-part RGB value"
```
`orange` does not exist in …

docs(guide): color output controls

---

.github/workflows/docs.yml

Creates workflow that will be triggered when a release is published. Steps in this workflow will clone the remote docs repository, build YAML docs and open a PR on docs repo with latest changes.

ci: release workflow to open a PR on docs repo with latest changes

---

docs/guides/bake/file-definition.md
docs/reference/buildx_bake.md

fixes #1192 
There is also some confusion around the list of valid target fields available and the overrides with the `--set` flag:
```hcl
target foo {
secret = ["..."]
}
```
```console
$ docker buildx bake --set *.secrets=...
```
In the bake definition we have `secret` and in the override `secrets` for example.
I think we should align that in a follow-up if it makes sense:
* `no-cache-filter` > `no-cache-filters`
* `output` > `outputs`
* `secret` > `secrets`
* `ssh` > `sshs` (don't like this one :neutral_face:)

docs(bake): fix target fields and show type

---

README.md
docs/guides/drivers/docker-container.md
docs/guides/drivers/index.md
docs/guides/drivers/kubernetes.md
docs/guides/drivers/remote.md

This PR adds a new basic docker-container guide to match with the existing remote and kubernetes guides. Because this is a smaller and simpler driver, the guide is as well :tada:
Additionally, to improve organization, all the driver guides are moved to a dedicated folder, with an index file to describe the high of all the drivers, pulling out existing content from the README, and introducing a new feature comparison table (not sure if I'm missing any essential features?).
Also, I've added a little bit of further reading at the end of each guide to point back to the driver opts in the buildx build reference.

Enhanced driver guides

---

build/build.go

Support Dockerfile from stdin ~or a local file~ with remote contexts. Fixes https://github.com/moby/moby/issues/38254 now that buildx is the only BuildKit client included in the Docker CLI (https://github.com/docker/cli/pull/3314).
Support for external Dockerfile on remote contexts was added to BuildKit in https://github.com/moby/buildkit/pull/947, which is included in the BuildKit v0.5.0 release and first vendored into Moby in https://github.com/moby/moby/pull/39132, included in v19.03.0. The client side was the only missing piece.

build: allow external Dockerfile on remote context

---

docs/guides/drivers/kubernetes.md

related https://github.com/docker/docker.github.io/pull/15262
```
#16 141.8 - ./_site/build/buildx/drivers/kubernetes/index.html
#16 141.8   *  linking to internal hash #build-multi-platform-images that does not exist (line 235)
#16 141.8      <a href="/build/buildx/#build-multi-platform-images">multi-architecture images</a>
```

docs: fix link

---

commands/util.go

while making some tests with @tonistiigi about an issue with `rm --all-inactive` that doesn't effectively remove some inactive nodes we saw that there is an underlying issue with docker context being detected as a docker-container builder:
```
$ docker context create --docker host=ssh://mini remote-buildkit
remote-buildkit
$ docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                               KUBERNETES ENDPOINT   ORCHESTRATOR
default *           moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                                         swarm
desktop-linux       moby                                                          npipe:////./pipe/dockerDesktopLinuxEngine …
```

check context builder endpoint

---

docs/guides/drivers/docker.md
docs/guides/drivers/index.md

Mostly for completeness, this patch adds basic documentation for the docker driver :tada: After this, we'll have guides for all 4 of our drivers.

docs: add minimal docker driver docs

---

commands/create.go
store/nodegroup.go

Previously, errors within the driver config would not be reported to the user until they tried to use the driver, even though they are easily accessible from the node group info.
For example:
```console
$ buildx create --bootstrap --name=kube --driver=kubernetes --driver-opt=namespace=buildkit,replicas=4,loadbalance=test
kube
$ buildx create --bootstrap --name=kube --driver=kubernetes --driver-opt=namespace=buildkit,replicas=4,loadbalance=test
ERROR: failed to initialize builder kube (kube0): invalid loadbalance "test"
kube
```
This is in a similar vein to #1188

buildx: log errors in initializing builders

---

build/build.go
commands/imagetools/create.go
docs/reference/buildx_imagetools_create.md
util/imagetools/create.go

Fixes #486
This PR introduces support for multiple repositories: this allows creating manifest lists with manifests pulled from multiple other locations.
This is split into two commits:
- The first refactors surrounding code to ensure that multiple repositories are recognized - this has changed some of the API surface, making the private `src` struct public to allow keeping the oci descriptor next to where it can be fetched from.
- The second to actually copy the manifests around to the new repository, and enable the multiple repositories feature

Imagetools multiple repositories

---

bake/hclparser/stdlib.go

Fix https://github.com/docker/buildx/issues/1201.
Terraform includes a `timestamp` function to get the current time. go-cty has imported a number of the timestamp functions to it's standard library in https://github.com/zclconf/go-cty/pull/37, however, this was one was not included:
> All but one of the "impure" functions fit into the cryptographic and filesystem categories I covered already anyway. The remaining one is timestamp, and I think it would be overkill to establish a new codebase just for that so maybe again it's sufficient to just copy-paste it into another application that needs it, as long as that application is prepared to deal with a function that doesn't return a stable result.
The result isn't fully stable, but user's should expect that, and can assign the result to a …

bake: add timestamp function

---

go.mod
go.sum
vendor/github.com/compose-spec/compose-go/loader/loader.go
vendor/github.com/compose-spec/compose-go/loader/normalize.go
vendor/github.com/compose-spec/compose-go/template/template.go
vendor/modules.txt

https://github.com/compose-spec/compose-go/releases/tag/v1.3.0 introduced a breaking change that has been fixed in 1.4.0.
https://github.com/compose-spec/compose-go/compare/v1.3.0...v1.4.0

update github.com/compose-spec/compose-go to v1.4.0

---

.github/workflows/docs-release.yml

`published` event is not right in our case as we don't want to open a pr on docs repo for pre-releases.
more info: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
cc @glours

ci: open pr on docs repo only on release

---

MAINTAINERS

@jedevc has made many great contributions to the repository, eg. [remote driver](https://github.com/docker/buildx/pull/1078) or [imagetools multi-repo support](https://github.com/docker/buildx/pull/1137) . Welcome to maintainers!
@AkihiroSuda @crazy-max @tiborvass 

add jedevc to maintainers

---

.github/workflows/docs-upstream.yml
.github/workflows/validate.yml
docs/reference/buildx_build.md

~needs https://github.com/docker/docker.github.io/pull/14905 or https://github.com/docker/docker.github.io/pull/15194~
adds a job to check if links are still valid with upstream docs repository.

ci: upstream docs conformance validation

---

.github/workflows/build.yml
hack/hash-files
hack/release

Split binaries job so now each platform is built on its own runner.
Before: ~19m
Now: ~3m

ci: enhanced build workflow

---

driver/kubernetes/context/load_test.go
go.mod
go.sum
vendor/github.com/docker/cli/cli/command/cli.go
vendor/github.com/docker/cli/cli/command/cli_options.go
vendor/github.com/docker/cli/cli/command/defaultcontextstore.go
vendor/modules.txt

(checking if ~https://github.com/docker/cli/pull/3510~ https://github.com/docker/cli/pull/3715 doesn't
break anything)
vendor: v20.10.3-0.20220803220330-418ca3b4d46f (v22.06.0-dev)
full diff: https://github.com/docker/cli/compare/f1615facb1ca...418ca3b4d46fed752d771cf96483664a631d8197
relevant changes;
- cli/command: remove unused args from ResolveDefaultContext()
- consider empty DOCKER_HOST and DOCKER_CONTEXT env-vars equivalent to "not set"
- cli: set timeout connection ping on sockets as well

vendor: v20.10.3-0.20220803220330-418ca3b4d46f (v22.06.0-dev)

---

commands/create.go
store/nodegroup.go

Around discussion in https://github.com/docker/buildx/issues/1186, a few issues with buildx drivers came up. These scenarios are unsupported, but the user isn't warned, for example:
- The kubernetes endpoint cli arg will be overwritten internally, so the user's specification is ignored
- Appending a new node to a builder with a different driver than the original is unsupported (and atm will overwrite the previous builder's driver)
- ~~Creating builders with the same name as context builders gives a warning, but appending and deleting doesn't.~~
This PR should resolve the above issues, and provide a more helpful local debugging experience.

Introduce new errors for unsupported driver behaviors

---

commands/prune.go

Fixes #400.
Previously, when specifying the filter option with the until value, no cache would be cleaned, preventing users from clearing by time. This bug arises from passing the until field through into buildkit, where, on filtering, a non-existent field returns false for a match.
The fix is simple, as we build up our list of filters to pass to buildkit, we skip over the until key, so create a valid list of filters for buildkit.

Fix prune `--filter until=<duration>` option

---

commands/prune.go
docs/reference/buildx_prune.md

The previous definition was the same as the docker images prune command and referenced dangling images, which isn't what the command does. This commit brings the command description more inline with the buildctl definition.
Additionally, add some more description of what the various flags do in our reference pages.

docs: add correct definition of prune --all flag

---

bake/bake.go
bake/compose.go
bake/compose_test.go
docs/guides/bake/compose-file.md

bake: contexts support with x-bake

---

build/build.go
commands/build.go
monitor/monitor.go
monitor/monitor_test.go

FIxes #1258
> On initial launch of the debug container, a message should be printed "Launching interactive container. Press Ctrl-a-c to switch to monitor console".
```console
[+] Building 3.8s (5/5) FINISHED                                          
=> [internal] load build definition from Dockerfile                 0.1s
=> => transferring dockerfile: 74B                                  0.0s
=> [internal] load .dockerignore                                    0.0s
=> => transferring context: 2B                                      0.0s
=> [internal] load metadata for docker.io/library/busybox:latest    3.2s
=> [1/2] FROM docker.io/library/busybox@sha256:ef320ff10026a50cf5f  0.4s
=> => resolve docker.io/library/busybox@sha256:ef320ff10026a50cf5f  0.0s
=> => …
```

invoke: add messages

---

build/build.go
monitor/monitor.go

Currently, when running `--invoke`, there exist the following issues:
When invoke container is not shut down by gracefully killing the container process itself then the container is left running in buildkit. This means that it also holds onto resources and cache records in `buildx du` do not become releasable. To reproduce, switch IO to monitor mode and then type "exit" or `ctrl-D`/SIGINT.
When switching IO to monitor mode and issuing "rollback" command the buildx process goes to 100% CPU (200% on repeat). Looks like there is a busy loop.
The release problem should be fixed on buildkit side as well as buildkit should handle misbehaving clients. I plan to fix it but we need this for old daemons anyway.
Tbh, I never figured out where the 100% CPU was coming from. Profiling CPU/Blocking was …

build: fix issues with leaving invoke containers running

---

driver/docker/driver.go

follow-up for #1260
Even if these are not supported atm, I think this is the intention, so buildx should try to use all these features.
@ndeloof @crazy-max 

enable other exporters if docker driver uses containerd

---

bake/bake.go
bake/compose.go
bake/compose_test.go
docs/guides/bake/compose-file.md

fixes #282
carry https://github.com/docker/buildx/pull/489
Loads `.env` file if available in the working directory for compose files. The file format is the same as the compose library: https://github.com/compose-spec/compose-go/tree/master/dotenv.

bake: load .env file from working dir for compose files

---

commands/build.go

I messed this up when doing the final review edits for #1100

commands: use buildx env for experimental opt-in

---

commands/create.go
commands/util.go
docs/reference/buildx_create.md
driver/manager.go

Fix https://github.com/docker/buildx/issues/1269.
Previously, the help information for buildx indicated that users could create a new instance of the docker driver - which is explicitly
something we don't support, driver of this form are automatically derived from the available list of docker contexts.
This patch ensures that don't have AllowsInstance set will not appear in the help text, and additionally provide a new more specific error message instead of the generic "failed to find driver". This should help point users in the correct direction.

create: improve interface when attempting to create docker driver

---

commands/build.go
docker-bake.hcl
docs/reference/buildx_build.md
hack/dockerfiles/docs.Dockerfile

Follow-up to https://github.com/docker/buildx/pull/1267
This patch ensures that we have consistent help messages between the two experimental options, and additionally adds the experimental options to the command reference along with information on how to enable them.

Consistent experimental help

---

bake/bake.go
bake/bake_test.go
bake/compose.go
bake/compose_test.go

fixes #1276 
while fixing compose consistency check in https://github.com/docker/buildx/pull/1181 a regression was introduced where services without build context were taken into account.
it was not detected because our test `TestNoBuildOutOfTreeService` was not checking the targets length: https://github.com/docker/buildx/blob/611329fc7f1365556789bff4747f608d40cdc8a9/bake/compose_test.go#L71-L82
by fixing this issue we now remove the ability to merge compose files without a build context https://github.com/docker/buildx/issues/1172. To fix this we now parse compose files all together so the compose-go library can handle a proper sanity check on its side.

bake(compose): fix unskipped services without build context

---

commands/inspect.go
docs/reference/buildx_inspect.md

Follow-up to #998 - this adds the buildkit version information to the `buildx inspect` command if it's available.

inspect: add buildkit version information to command output

---

build/build.go
build/git.go
build/git_test.go

As discussed in #1290, this PR adds opt-in labels for Git provenance.
The following labels will be added when `BUILDX_GIT_LABELS=full` is set:
```json
"Labels": {
"com.docker.image.source.entrypoint": "Dockerfile",
"org.opencontainers.image.revision": "5734329c6af43c2ae295010778cd308866b95d9b",
"org.opencontainers.image.source": "git@github.com:atomisthq/kipz-docker-test.git"
}
```
With only `BUILDX_GIT_LABELS =1` the repository label will not be included:
```json
"Labels": {
"com.docker.image.source.entrypoint": "Dockerfile",
"org.opencontainers.image.revision": "5734329c6af43c2ae295010778cd308866b95d9b"
}
```
If the cloned source is not clean, the `revision` label value will get a `-dirty` suffix:
```json
"Labels": {
"com.docker.image.source.entrypoint": "Dockerfile", …
```

Add git provenance labels

---

commands/diskusage.go
commands/prune.go

Fix driver error being omitted

return di.Err when it's not nil

---

docs/guides/drivers/docker-container.md
docs/guides/drivers/docker.md
docs/guides/drivers/index.md
docs/guides/drivers/kubernetes.md
docs/guides/drivers/remote.md

While working on merging buildx overview page in main overview one, I found out a link was broken in the drivers guide:
```
#16 0.099 - ./_site/build/buildx/drivers/docker/index.html
#16 0.099   *  internally linking to ../index.md, which does not exist (line 147)
#16 0.099      <a href="../index.md">other drivers</a>
```
Looks like we linked _others drivers_ to the buildx overview page which is also broken on GitHub: https://github.com/docker/buildx/blob/master/docs/guides/index.md.
@jedevc I guess you wanted to link to the drivers guide index page.
Also update links to driver reference. About left `FIXME` I don't think we should use relative links actually as we could easily break pages when moving them between sections in docs repo. Also with the `fix_url` jekyll plugin on docs repo we …

docs: fix link in driver guide

---

docs/guides/cache/azblob.md
docs/guides/cache/gha.md
docs/guides/cache/index.md
docs/guides/cache/inline.md
docs/guides/cache/local.md
docs/guides/cache/registry.md
docs/guides/cache/s3.md

This fleshes out the documentation to include information along with examples and detailed use cases for the cache backends. The general format and style follows from the style of the build driver docs.
Eventually, these docs will be included on docs.docker.com along with the rest of the build docs. This docs are designed to complement the introduction in https://github.com/docker/docker.github.io/pull/15603, and after both are merged, we should be able to cross-link between them.
The `s3` and `azblob` backends are both relatively sparse on detail, since I don't have the knowledge to write those best, but would be happy to address these in a follow-up (unless there are any glaring issues wrong with them atm).

docs: add cache storage backend docs

---

.github/workflows/build.yml
.github/workflows/e2e.yml

PRs like https://github.com/docker/buildx/pull/1316 which don't modify any code or ci tooling still run all the long build and e2e workflows.
This patch skips those workflows if the changes affect only "docs" files, currently set to be the entire contents of the `docs/` directory and `README.md`.

ci: don't trigger build and e2e workflows on docs-only pull requests

---

build/git.go
build/git_test.go

This is to make sure that `BUILDX_GIT_LABELS= docker buildx build ...` will not set the git labels.
Fixes https://github.com/docker/buildx/issues/1340
Signed-off-by: David Gageot <david.gageot@docker.com>

[1340] Disable git labels if `BUILDX_GIT_LABELS` is not `1` or `full`

---

driver/kubernetes/manifest/manifest.go

Tested with GKE Autopilot 1.24.3-gke.200 (kernel 5.10.123+, containerd 1.6.6).
ref: moby/buildkit#3097

kubernetes: rootless: support Google Container-Optimized OS  (Fix ` Options:[rbind ro]}]: operation not permitted` errors)

---

docs/guides/cache/azblob.md
docs/guides/cache/gha.md
docs/guides/cache/index.md
docs/guides/cache/inline.md
docs/guides/cache/local.md
docs/guides/cache/registry.md
docs/guides/cache/s3.md
docs/guides/drivers/docker-container.md

Replaced more (broken) relative links with absolute ones
Signed-off-by: David Karlsson <david.karlsson@docker.com>

docs: replaced broken relative links

---

docs/guides/cache/index.md

We should keep consistency with the rest of the list, and call it "inline" instead of "inline-cache".

docs: fix typo in cache docs

---

commands/bake.go

fixes #1344 
Since 0.9 we are checking the context builder endpoint to make sure it's reachable before returning the instance: https://github.com/docker/buildx/pull/1129#issuecomment-1195542481. By doing so we are not soft-failing as before when loading `driversForNodeGroup` and therefore `bake --print` now fails if no instance is available.
This PR will not return an error if we are printing local bake files. An instance is still required when building or loading remote bake files.

bake: do not fail printing definition if instance unavailable

---

docs/guides/cache/azblob.md
docs/guides/cache/gha.md
docs/guides/cache/local.md
docs/guides/cache/registry.md
docs/guides/cache/s3.md

Signed-off-by: David Karlsson <david.karlsson@docker.com>
Add dollar (`$`) user sign for code blocks of type console

docs: add user sign for console blocks

---

.golangci.yml
commands/build.go

`structcheck` is abandoned, and has been replaced by the `unused` linter. See https://golangci-lint.run/usage/linters/#structcheck for more information.
> The owner seems to have abandoned the linter. Replaced by unused.
See similar in https://github.com/moby/buildkit/pull/3196

lint: remove structcheck

---

driver/docker-container/driver.go
driver/docker-container/factory.go

Follow-up to https://github.com/docker/buildx/pull/887 (see https://github.com/docker/buildx/pull/887#issuecomment-1285292603 for more context).
This resolves https://github.com/docker/buildx/discussions/1358, so that a docker-container builder can be created even in the absence of the socket - it shouldn't fail until it is started, either with `--bootstrap` or by attempting a build.
The issue that caused this flow to stop working was introduced in https://github.com/docker/buildx/pull/1206, which was released in [v0.9](https://github.com/docker/buildx/releases/tag/v0.9.0) - I wonder if it's worth cherry-picking?

Userns to driver

---

go.mod
go.sum
vendor/modules.txt

it's the same commit: https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.2...c182affec369

go.mod: matttproud/golang_protobuf_extensions v1.0.2 (use tag)

---

commands/bake.go
commands/build.go
commands/imagetools/create.go
commands/util.go
util/progress/printer.go

See https://github.com/docker/buildx/issues/1288.
The NewPrinter function is mostly borrowed from buildkit. However, at some point, it seems that the implementations drifted.
This patch updates buildx to be more similar in behavior to it's buildkit counterpart, specifically, it will explicitly fail if a TTY output is requested using "--progress=tty", but the output is not available.
To gracefully fallback to plain progress in this scenario, "--progress=plain" is required.

progress: explicitly fail if tty requested but not available

---

driver/kubernetes/manifest/manifest.go

Cherry-pick (clean):
- https://github.com/docker/buildx/pull/1310

[v0.9] kubernetes: rootless: support Google Container-Optimized OS

---

.github/workflows/docs-upstream.yml

related to https://github.com/docker/buildx/pull/1385
Now that docs fetches remote resources using Git, we need to use the right head repo and ref on pull request event, otherwise: https://github.com/docker/buildx/actions/runs/3369331654/jobs/5588889013#step:8:563
```
#20 6.832   Repo https://github.com/docker/buildx
#20 6.832     Cloning repository into /tmp/docker-docs-clone/docker/buildx
#20 7.140                     ------------------------------------------------
#20 7.140       Jekyll 4.2.2   Please append `--trace` to the `build` command 
#20 7.141                      for any additional information or backtrace. 
#20 7.141                     ------------------------------------------------
#20 7.142 /usr/local/bundle/gems/git-1.12.0/lib/git/lib.rb:1125:in `command': git '-c' …
```

ci(docs-upstream): fix ref on pull request event

---

driver/docker-container/driver.go
driver/kubernetes/driver.go

:hammer_and_wrench: fixes https://github.com/moby/buildkit/issues/3242 
The error handling for the cast to client.TracerDelegate was incorrect, and previously, a client would unconditionally append an opt.
This results in the scenario that while the ClientOpt was not nil, the tracer delegate in the ClientOpt was, which isn't an error case explicitly handled by buildkit.
We might want to follow up in buildkit [here](https://github.com/moby/buildkit/blob/master/client/client.go#L78-L80) and add an explicit `nil` check for `withTracerDelegate.TracerDelegate == nil` as a sanity check.

driver: don't create tracer delegate opt if tracer is nil

---

docs/guides/cache/index.md
docs/guides/cicd.md
docs/guides/exporters/image-registry.md
docs/guides/exporters/index.md
docs/guides/exporters/local-tar.md
docs/guides/exporters/oci-docker.md

This patch adds more complete documentation for the various exporters available to buildx.
This is similar in theme to #1316.

Add exporter docs

---

docs/manuals/drivers/docker-container.md
docs/manuals/drivers/kubernetes.md
docs/manuals/drivers/remote.md
docs/manuals/exporters/image-registry.md
docs/manuals/exporters/local-tar.md
docs/manuals/exporters/oci-docker.md

:hammer_and_wrench: Fixes https://github.com/docker/setup-buildx-action/issues/179#issuecomment-1309977562
:hammer_and_wrench: Also ensures we use consistent parameter table headers with "Type" instead of "Value", to be inline with GitHub actions (e.g. [build-push-action](https://github.com/docker/build-push-action#inputs))

Docs consistency fixes

---

util/imagetools/printers.go

If you happen to run:
docker buildx imagetools inspect --format '{{. | json}}' imageRef
Where `imageRef` points to a manifest list with multiple platforms.
You can sometimes run into `concurrent map write` errors as there are multiple goroutines trying to write to the `imageInfo` and `buildInfo` maps.
NB: I'm not a Go developer, if there is a nicer way to do this, happy to make edits.

Synchronise access to the map when printing.

---

util/imagetools/printers.go

https://github.com/docker/buildx/pull/1406

[0.9] Synchronise access to the map when printing

---

bake/bake.go
bake/bake_test.go
commands/bake.go

Fixes https://github.com/docker/buildx/issues/1058.
Groups that contained other groups were not recursively resolved by `ReadTargets`, which prevented output from `--print` from being useable as a self-contained bake file. e.g.
```hcl
group "default" {
targets = ["other-group"]
}
group "other-group" {
targets = ["app"]
}
target "app" {
dockerfile = "Dockerfile"
tags = ["docker.io/username/app"]
}
```
is used as 
```bash
$ buildx bake --print -f docker-bake.hcl
[+] Building 0.0s (0/0)                                                                                                    
{
"group": {
"default": {
"targets": [
"other-group"
]
},
"other-group": {
"targets": [
"app"
]
}
},
"target": {
"app": {
"tags": [
"docker.io/username/app"
]
}
}
} …
```

bake: recursively resolve groups

---

util/progress/multiwriter.go

Fixes #1195. CC @ciaranmcnulty.
As buildkit now uses progress groups for the COPY --link instruction we need to ensure that we additionally prefix the progress group name, or the target name will be left off in bake commands with more than one target.

progress: add prefix to vertex progress group

---

.dockerignore
.github/workflows/build.yml
.github/workflows/e2e.yml
.gitignore
Makefile
docker-bake.hcl
hack/hash-files
hack/release
hack/shell
hack/test-driver
hack/update-docs
hack/update-vendor

reduce footprint in our gitignore by using a single output dir for build, cross and coverage. also remove unused `cross-out`. structure will look like this:
* `./bin/build`
* `./bin/coverage`
* `./bin/release`
can be overridden using the `DESTDIR` env var. name of this en var seems to be the more approriate in our case: https://www.gnu.org/prep/standards/html_node/DESTDIR.html.

hack: use single output dir

---

commands/util.go

follow-up https://github.com/docker/buildx/issues/1249#issuecomment-1205162020
Use `docker.EndpointFromContext` to parse context docker endpoint metadata.
Also remove `dockerapi.NegotiateAPIVersion(ctx)` which is already provided by `ep.ClientOpts()`: https://github.com/docker/cli/blob/f1615facb1ca44e4336ab20e621315fc2cfb845a/cli/context/docker/load.go#L124.

docker api: use helper to parse context docker endpoint metadata

---

go.mod
go.sum
vendor/modules.txt

- relates to https://github.com/moby/buildkit/pull/3320
This module made a whoopsie, and updated to `google.golang.org/protobuf` in a patch release, but `google.golang.org/protobuf` is not backward compatible with `github.com/golang/protobuf`.
Updating the minimum version to v1.0.4 which corrects this, to prevent users of buildx as a module from accidentally pulling in the wrong version:
- v1.0.3 switched to use `google.golang.org/protobuf`; https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.2..v1.0.3
- This was reverted in v1.0.4 (which is the same as v1.0.2); https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.3..v1.0.4
- And a `v2` was created instead; https://github.com/matttproud/golang_protobuf_extensions/releases/tag/v2.0.0

go.mod: golang_protobuf_extensions v1.0.4 - prevent incompat versions

---

commands/imagetools/create.go

fixes #1425
related to https://github.com/docker/buildx/pull/1137 (https://github.com/docker/buildx/pull/1137/commits/d3412f1039acd5f13e7891fa2d6b149fc7954d22)
Previously when combining descriptors we were always using the default repo ref for remote resolution. This change brings this logic back and will set the default repo ref for the source if empty.

imagetools: set default repo ref on creation if nil

---

build/build.go
build/utils.go

follow-up https://github.com/moby/moby/pull/44537
When parsing extra hosts, skip "host-gateway" IP address validation with moby driver.

build: skip "host-gateway" validation with moby driver

---

Dockerfile
Makefile
hack/build
hack/git-meta

follow-up https://github.com/docker/buildx/pull/1268#issuecomment-1288488791
Mutualize build opts in Makefile and Dockerfile so we avoid drifting with packaging releases https://github.com/docker/docker-ce-packaging/blob/43635c4329d15c3639d6b8693b653b7ea9818487/deb/common/rules#L22:
We can then change:
```
CGO_ENABLED=0 GO111MODULE=on go build -mod=vendor -o /usr/libexec/docker/cli-plugins/docker-buildx -ldflags "-X github.com/docker/buildx/version.Version=$(BUILDX_VERSION) -X github.com/docker/buildx/version.Revision=$(git rev-parse HEAD) -X github.com/docker/buildx/version.Package=github.com/docker/buildx" ./cmd/buildx
```
with:
```
DESTDIR=/usr/libexec/docker/cli-plugins VERSION=$(BUILDX_VERSION) REVISION=$(BUILDX_GITCOMMIT) make build
```
Signed-off-by: CrazyMax …

hack: mutualize build opts in Makefile and Dockerfile

---

store/nodegroup.go

related to #1454
Forgot to skip `DockerContext` field from being saved. Otherwise when a new builder is created, it will be added to the store:
```json
{
"Name": "hardcore_wu",
"Driver": "docker-container",
"Nodes": [
{
"Name": "hardcore_wu0",
"Endpoint": "unix:///var/run/docker.sock",
"Platforms": null,
"Flags": null,
"DriverOpts": null,
"Files": null
}
],
"Dynamic": false,
"DockerContext": false
}
```

store: skip DockerContext field from being saved

---

bake/bake.go
build/build.go
commands/bake.go
commands/build.go
docs/reference/buildx_bake.md
docs/reference/buildx_build.md
util/buildflags/attests.go

Adds an `--attest` flag to the build command, to add SBOM and provenance attestations. Example usage:
```bash
$ docker buildx build . -t foo --attest type=sbom --attest type=provenance
$ docker buildx build . -t foo --attest type=sbom,generator="<registry>/<image>" --attest type=provenance,mode="<mode>"
```
Also adds an `attest` field to bake. Example usage:
```hcl
target "myimage" {
attest = [
"type=sbom"
]
}
```
The attestation parameters are forwarded to buildkit, which should then include them in the build.

Attestations from buildx

---

build/build.go

This looks like an oversight, all of the other options have similar checks. This can interfere with generated provenance where "add-hosts" will be marked as an argument to the build, even though it's not actually being utilized.

build: don't set add-hosts option if empty

---

commands/bake.go
commands/build.go
commands/inspect.go
store/nodegroup.go
store/store.go
store/store_test.go
store/storeutil/storeutil.go

adds last activity property that will be updated on build or when a node is updated.
```console
$ docker buildx inspect
Name:          builder2
Last Activity: 2022-11-30 13:56:51 +0100 CET
Nodes:
Name:           builder20
Endpoint:       unix:///var/run/docker.sock
Driver Options: env.BUILDKIT_STEP_LOG_MAX_SPEED="10485760" env.JAEGER_TRACE="localhost:6831" image="moby/buildkit:master" network="host" env.BUILDKIT_STEP_LOG_MAX_SIZE="10485760"
Status:         running
Flags:          --debug --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
Buildkit:       7615120
Platforms:      linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, …
```

store: set nodegroup last activity

---

build/build.go
build/git.go
build/git_test.go
util/gitutil/gitutil.go
util/gitutil/gitutil_test.go
util/gitutil/testutil.go

follow-up https://github.com/moby/buildkit/pull/3240#issuecomment-1296613640
Sets provenance vcs details.

build: set provenance vcs details

---

build/git.go
build/git_test.go

build: fix env vars check for vcs details

---

bake/bake.go
bake/bake_test.go
bake/compose.go
bake/compose_test.go
bake/hcl_test.go
bake/hclparser/expr.go
bake/hclparser/hclparser.go

follow-up https://github.com/docker/buildx/issues/1362#issuecomment-1287397312
```hcl
variable "GO_VERSION" {
default = ""
}
args = {
GO_VERSION = GO_VERSION
}
}
```
```dockerfile
ARG GO_VERSION="1.18"
FROM golang:${GO_VERSION}
```
```console
{
"target": {
"default": {
"args": {
"GO_VERSION": ""
}
}
}
}
```
In this example, `GO_VERSION` arg will always be sent in the request and overwrites the one in the Dockerfile. Therefore build would fail as `GO_VERSION` will be empty.
With this PR, `null` type is now handled and will set the arg only if set:
```hcl
variable "GO_VERSION" {
default = null
}
args = {
GO_VERSION = GO_VERSION
}
}
```
```console
{ …
```

bake: support null arg and label value

---

hack/test-driver

e2e: load to docker store

---

builder/builder.go

We should check the endpoint for docker context from the store as `nodes` are only populated through `LoadNodes`.

builder: check endpoint from store when loading factory

---

.github/workflows/docs-release.yml

follow-up https://github.com/docker/docs/pull/16339

ci: do not publish docs on prerelease

---

util/buildflags/attests.go

:bug: Bug report from @tianon:
> `--attest type=sbom,generator=...` did work, but I had `--sbom=true` later in my CLI which then overwrote the whole `--attest type=sbom` with one that had no arguments
We now explicitly error if a single field is repeated (I seem to remember we did this at some point previously, but looks like it was removed).

buildflags: error on duplicate attest field

---

.github/workflows/build.yml
Dockerfile
hack/release

follow-up https://github.com/moby/buildkit/pull/3345 https://github.com/moby/buildkit/pull/3405
cc @laurentsimon

ci: opt-in sbom and provenance

---

build/build.go
build/git.go
build/git_test.go
go.mod
go.sum
util/gitutil/gitpath_unix.go
util/gitutil/gitpath_windows.go
util/gitutil/gitutil.go
util/gitutil/gitutil_test.go
util/gitutil/testutil.go
vendor/github.com/moby/sys/mountinfo/LICENSE
vendor/github.com/moby/sys/mountinfo/doc.go
vendor/github.com/moby/sys/mountinfo/mounted_linux.go
vendor/github.com/moby/sys/mountinfo/mounted_unix.go
vendor/github.com/moby/sys/mountinfo/mountinfo.go
vendor/github.com/moby/sys/mountinfo/mountinfo_bsd.go
vendor/github.com/moby/sys/mountinfo/mountinfo_filters.go
vendor/github.com/moby/sys/mountinfo/mountinfo_freebsdlike.go
vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go
vendor/github.com/moby/sys/mountinfo/mountinfo_openbsd.go
vendor/github.com/moby/sys/mountinfo/mountinfo_unsupported.go
vendor/github.com/moby/sys/mountinfo/mountinfo_windows.go
vendor/modules.txt

closes https://github.com/docker/buildx/pull/1470
Windows drives in WSL version 2 uses the 9P protocol which the WSL instance connects to. When running git operations on a 9p fs using git from `/usr/bin/git`, it can be quite slow:
```console
$ cd /mnt/c/github.com/moby/moby
$ time git -c log.showSignature=false status --porcelain --ignored >/dev/null
real    1m5.620s
user    0m0.387s
sys     0m59.010s
```
But using `git.exe` is quite fast:
```console
$ cd /mnt/c/github.com/moby/moby
$ time git.exe -c log.showSignature=false status --porcelain --ignored >/dev/null
real    0m0.147s
user    0m0.003s
sys     0m0.009s
```
This change will detect if git operations occur on WSL and on a 9p fs and in this case lookup for `git.exe`, otherwise fallback to `git`.
Signed-off-by: CrazyMax …

build: lookup the right git binary on WSL

---

README.md
docker-bake.hcl

As discussed with @tonistiigi, we should not set `BUILDX_EXPERIMENTAL` when releasing binaries or bin-image.
Also adds extra commit related to https://github.com/badges/shields/issues/8671 to fix badge in the readme:

disable buildx experimental in pipeline

---

bake/bake.go
build/build.go

See https://reproducible-builds.org/docs/source-date-epoch/
Expected to be used with BuildKit v0.11 or later (https://github.com/moby/buildkit/issues?q=label%3Aarea%2Freproducible-builds+)

Propagate SOURCE_DATE_EPOCH from the client env

---

.github/workflows/e2e.yml

[`debianmaster/actions-k3s` action](https://github.com/debianmaster/actions-k3s/) triggers warnings in our e2e workflow: https://github.com/docker/buildx/actions/runs/3654304646
Switch to a native script inside our workflow so we don't depend on this action anymore.

e2e: use native k3s installation script

---

bake/bake.go
build/build.go

Cherry-pick (clean)
- https://github.com/docker/buildx/pull/1482

[0.10] Propagate SOURCE_DATE_EPOCH from the client env

---

build/build.go
docs/reference/buildx_build.md

:arrow_up: Follow up to #1173.
We allow any valid image reference format for the oci-layout, not just limiting to name@digest, we additionally allow images of the form name:tag@digest now.
The name of the reference is used to find the local directory to lookup the store in, while the tag and digest are attached to a random identity to generate the dummy reference sent to the oci-layout context.
This separation of the target to replace and the value to replace it with ensures that any tag or digest set in the client is properly sent across to the server. The tag, while not relevant now, may become relevant at some point in the future for the server, so we can should send it across for now.

build: refactor reference parsing for oci image layouts

---

docs/reference/buildx_imagetools_inspect.md
util/imagetools/loader.go
util/imagetools/printers.go

Supports provenance and sbom for `imagetools inspect` command.
```console
$ docker buildx imagetools inspect crazymax/buildkit:attest --format "{{json .}}"
```
https://gist.github.com/crazy-max/5bbc2e60c58263a0162bbf3b920d3d09

imagetools inspect: handle provenance and sboms

---

commands/build.go
docs/reference/buildx.md
docs/reference/buildx_bake.md
docs/reference/buildx_build.md
docs/reference/buildx_create.md
docs/reference/buildx_du.md
docs/reference/buildx_imagetools.md
docs/reference/buildx_imagetools_create.md
docs/reference/buildx_imagetools_inspect.md
docs/reference/buildx_inspect.md
docs/reference/buildx_prune.md
docs/reference/buildx_rm.md
docs/reference/buildx_stop.md
docs/reference/buildx_use.md
go.mod
go.sum
vendor/github.com/docker/cli-docs-tool/README.md
vendor/github.com/docker/cli-docs-tool/clidocstool_md.go
vendor/modules.txt

backports:
- https://github.com/docker/buildx/pull/1493
- https://github.com/docker/buildx/pull/1494
relates to:
- https://github.com/docker/docs/pull/16461
- https://github.com/docker/docs/pull/16460

[0.10 backport] update anchor-links and cli-docs-tool v0.5.1

---

docs/reference/buildx_imagetools_inspect.md
util/imagetools/loader.go
util/imagetools/printers.go

:arrow_up: Follow up to #1444 
This includes 3 main changes:
- Break after first found SPDX document (prioritizes the first attestations to take advantage of https://github.com/moby/buildkit/pull/3479)
- Re-work stub structs to have `interface{}` types instead of `json.RawMessage`; this allows them to be accessed using go template notation, e.g. `--format "{{ range .SBOM.SPDX.packages }}{{ println .name .versionInfo }}{{ end }}"`.
- We strip away the `Predicate` field to directly access the predicate of the attestation. In the future, we should to sanity check the subject of the attestation against the pulled image, as well as the predicate type - this should be the responsibility of the go-imageinspect library.
- If we want to provide access to the raw attestation contents (including …

Improved attestation inspect

---

README.md

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
As I saw in the [docker-bake.hcl](https://github.com/docker/buildx/blob/master/docker-bake.hcl#L104), the binary is outputted into the folder `./bin/build/<binary>,` but in the README, it says `./bin/<binary>,` so, this PR aims to fix this.

fix the directory of the buildx binary

---

.github/workflows/docs-release.yml

When buildx 0.10.0 was released it didn't trigger the docs-release workflow: https://github.com/docker/buildx/actions/workflows/docs-release.yml
Looks like a typo in release filter introduced in https://github.com/docker/buildx/pull/1473

ci: fix typo in docs-release workflow

---

docs/guides/opentelemetry.md

The buildx builder persists across Desktop restarts. So when we start up Jaeger, we should recommend that people configure it to persist across restarts as well.
Signed-off-by: Nick Santos <nick.santos@docker.com>

docs: small tweak to opentelemetry

---

docs/reference/buildx_bake.md
docs/reference/buildx_build.md

:arrow_up: Follow-up to https://github.com/docker/docs/pull/16517
We should have a brief explanation in the reference of the new `--attest`, `--sbom` and `--provenance` flags, which can point to the manuals where we have a more complete write-up and explanation of how to use it.

docs: add reference for new attest family of flags

---

docs/reference/buildx_bake.md
docs/reference/buildx_build.md

:cherries: Cherry-pick of https://github.com/docker/buildx/pull/1523
> We should have a brief explanation in the reference of the new --attest, --sbom and --provenance flags, which can point to the manuals where we have a more complete write-up and explanation of how to use it.

[0.10] docs: add reference for new attest family of flags

---

go.mod
go.sum
vendor/github.com/moby/buildkit/session/sshforward/copy.go
vendor/github.com/moby/buildkit/util/tracing/detect/otlp.go
vendor/modules.txt

- backport of https://github.com/docker/buildx/pull/1529
full diff: https://github.com/moby/buildkit/compare/v0.11.0...v0.11.1
(cherry picked from commit 01e1c28dd9cec63c96139416e7a866cd659a90b5)

[0.10 backport] vendor: github.com/moby/buildkit v0.11.1

---

build/build.go

So it doesn't show up in the History API.
Ideally, we could somehow detect this automatically in the BuildKit side in the future, but don't have good ideas atm.

build: mark capabilities request as internal

---

README.md

https://github.com/moby/buildkit/issues/3490 seems to have been caused by an old docker version - we should add a note to the Buildx README about minimum version requirements (we now need OCI support in the docker daemon now that moby/buildkit uses an OCI image), as well as adding a warning for what users can expect if they go ahead.

docs: add note about minimum docker version

---

util/imagetools/loader.go
util/imagetools/printers.go

:arrow_up: Follow-up to #1498
This PR improves performance for the standard case of doing a simple `imagetools inspect` command. In v0.10.0 we see a performance regression when inspecting images that have [attached attestations](https://github.com/moby/buildkit/blob/master/docs/attestations/attestation-storage.md) using simple format strings like `{{ json . }}`. We can resolve this performance issue by lazily loading attestation data, only when requested to by the format template.
This is split into two patches:
- Split out the template input struct definitions. This allows us to define methods on the struct, so that we can make the `.SBOM` and `.Provenance` attributes into methods instead of properties on the struct. These can be accessed *identically* to the previous attributes for all …

Lazily load attestation data in `imagetools inspect`

---

commands/rm.go

fixes #1541
This change has been introduced in e7b5ee7518703fb284fd9ece81abf71e4838f4d9 but we should not check context builders when removing inactive ones.

rm: do not check for context builders when removing inactive

---

.github/workflows/build.yml

:cherries: Cherry-picks of https://github.com/docker/buildx/pull/1525 and https://github.com/docker/buildx/pull/1543.

[v0.10] Bump Buildx and BuildKit versions in GitHub actions

---

util/imagetools/loader.go
util/imagetools/printers.go

:cherries: Cherry-pick of https://github.com/docker/buildx/pull/1505.

[v0.10] Lazily load attestation data in imagetools inspect

---

build/build.go

:hammer_and_wrench: Fixes https://github.com/docker/buildx/issues/1497.
Using the error group concurrency primitive we can avoid needing to create a separate wait group.
This allows us to sidestep the issue described in https://github.com/docker/buildx/issues/1497#issuecomment-1375905222 where the wait group could be completed, but the build invocation functions had not terminated - if one of the functions was to terminate with an error, then it was possible to encounter a race condition, where the result handling code would begin executing, despite an error.
The refactor to use a separate error group which more elegantly handles the concept of function returns and errors, ensures that we can't encounter this issue.
For clarity, this fix is split in to three separate commits, the first …

Refactor BuildWithResultHandler to simplify concurrency usage

---

build/git_test.go
util/gitutil/gitutil.go
util/gitutil/gitutil_test.go
util/gitutil/testutil.go

fixes #1540
By default we use the first remote url when setting vcs url. This change will use origin url. If it fails, fallback to upstream url. Otherwise get the first remote url.

build: set remote origin url

---

builder/node.go

fixes #1539
fixes #1560
When checking available platforms for current nodes, those are always empty in https://github.com/docker/buildx/blob/a718d07f6414bfe960899050c0107e6baa86dcba/build/build.go#L259
That's because when loading nodes we don't set the preferred platforms from the store. Therefore builds will always run on the very first node available.

build: fix preferred platform not taken into account

---

build/build.go

fixes #1519
While the merge from `imagetools create` used the correct input descriptor that it asked from the registry, the call of the same function from multi-node build just made up a descriptor from the digest.
What is weirder is that the mediatype that the previous code used, didn't really matter because requests have `Accept: */*` passed. But at least for hub it looks like for OCI objects even `Accept: */*` gives an error, while for the old objects, you don't need to pass the correct header(this is why the merge worked both for merging lists and images). Not sure if this is registry specific. I'm trying to find out what behavior is expected from the registry side in this case.
@smira 

build: fix multi-node merge to read descriptor from result

---

build/git.go

reported by @tonistiigi 
> Got this warning `WARNING: failed to get git remote url: no remote URL found for either origin or upstream` from by xx checkout. As a regular user I wouldn't really understand what it is about. Not even clear it came from buildx.
As discussed we should just silently fail if remote Git URL is not found. Also improve warning message by adding `buildx:` prefix.

build: silently fail if git remote not found

---

.github/workflows/docs-upstream.yml

Didn't catch this one as GitHub doesn't give any check failure when a workflow is invalid :persevere:
https://github.com/docker/buildx/actions/runs/4047616608

ci: fix docs-upstream workflow

---

.github/workflows/releases-json.yml

Looks like the `releases-json` workflow [has not been triggered with release v0.10.2](https://github.com/docker/buildx/actions?query=branch%3Av0.10.2) from yesterday.
~I think this is related to the event not being dispatched correctly when using a `release` and `pull_request` event within the same workflow. I have tested this behavior on another repo and looks good without `pull_request`.~
Ok after investigation with @jedevc it looks like the event has not been propagated at all for this workflow. So let's just add a `workflow_dispatch` event to be able to trigger this workflow manually in case it happens again.

ci: add workflow_dispatch in releases-json workflow

---

.github/workflows/releases-json.yml

```
/usr/bin/git checkout --progress -B releases-json/ 9f0b2a21-fceb-4f3a-832c-19ad87af7a3f --
fatal: 'releases-json/' is not a valid branch name
Error: The process '/usr/bin/git' failed with exit code 128
```
Well, on `workflow_dispatch` there is no release name. Let's just put a fixed branch name.

ci: fix pr branch name in releases-json workflow

---

store/storeutil/storeutil.go

Fixes a regression introduced by https://github.com/docker/buildx/pull/1439 (https://github.com/docker/buildx/pull/1439/commits/8c472771418cc676e69fd7744396b7b9a07b7849) (probably bad rebase :disappointed:) where `DockerContext` is not being set anymore and therefore validation is always skipped in: https://github.com/docker/buildx/blob/d2fa4a57244df2d1aae9efc9dfe6f563f72bafc3/builder/builder.go#L111

builder: fix docker context not validated

---

bake/hcl_test.go
bake/hclparser/hclparser.go

:bug: Fixes https://github.com/docker/buildx/issues/1586 (however, it looks like there are still some underlying issues with `funcCall` erroneously detecting contents of those JSON objects as function calls).
With changes made to allow lazy evaluation, we were early exiting if an undefined name was detected, either for a variable or a function.
This had two key implications:
1. The error messages changed, and became significantly less informative.
For example, we went from:
> Unknown variable; There is no variable named "FO". Did you mean "FOO"?, and 1 other diagnostic(s)
To
> Invalid expression; undefined variable "FO"
2. Any issues in our function detection from funcCalls which cause JSON functions to be erroneously detected cause invalid functions to be resolved, which causes new name …

bake: avoid early-exit for resolution failures

---

bake/hclparser/expr.go
bake/hclparser/hclparser.go

With changes to the lazy evaluation, the evaluation order is no longer fixed - this means that we can follow long and confusing paths to get to an error.
Because of the co-recursive nature of the lazy evaluation, we need to take special care that the original HCL diagnostics are not discarded and are preserved so that the original source of the error can be detected. Preserving the full trace is not necessary, and probably not useful to the user - all of the file that is not lazily loaded will be eagerly loaded after all struct blocks are loaded - so the error would be found regardless.
For example, in the following `docker-bake.hcl`:
```hcl
x = x
target "test" {
dockerfile = x
}
```
We expect an error view like:
```
docker-bake.hcl:1
1 | >>> x = x
2 |     
3 | …
```

bake: avoid nesting error diagnostics

---

build/git.go
util/gitutil/gitutil.go
util/gitutil/gitutil_test.go

fixes #1587 
We should check if the working tree has git commits before retrieving the git commit so it would not fail. I was also thinking of just silently fail. Let me know what sounds best.

build: check reachable git commits

---

go.mod
hack/dockerfiles/vendor.Dockerfile

Go 1.20 will be there soon, I think it's time to move our go.mod to latest stable. We can then remove the compat in our vendor.Dockerfile
Downstream projects like compose or github.com/linuxkit/linuxkit should not be affected.
cc @rumpl 

go.mod: bump to Go 1.19

---

util/imagetools/loader.go

See https://github.com/moby/buildkit/issues/3496 for more context.
To give us the option later down the road of producing recommended OCI names in BuildKit (using com instead of vnd, woops), we need to update Buildx to be able to process both.
Ideally, if a Buildx/BuildKit release hadn't been made we could just switch over, but since we have, we'd need to support both (at least for a while, eventually we could consider deprecating+removing the vnd variant).
We should follow this up with a BuildKit update to produce the `com` annotation (though less convinced we'd want to cherry-pick that one).

imagetools: process `com.docker.reference.*` annotations

---

bake/compose.go
bake/hcl_test.go
bake/hclparser/expr.go
bake/hclparser/hclparser.go
bake/remote.go
build/git.go
docs/reference/buildx_build.md
store/storeutil/storeutil.go
util/gitutil/gitutil.go
util/gitutil/gitutil_test.go
util/imagetools/loader.go

* https://github.com/docker/buildx/pull/1592
* https://github.com/docker/buildx/pull/1605
* https://github.com/docker/buildx/pull/1601
* https://github.com/docker/buildx/pull/1596
* https://github.com/docker/buildx/pull/1582 (partial: 48357ee0c6a2fb4e2e68e49ac06386f2fafa51c6)
* https://github.com/docker/buildx/pull/1607
* https://github.com/docker/buildx/pull/1617

[v0.10] cherry-picks for v0.10.3

---

.github/workflows/build.yml

* backport of https://github.com/docker/buildx/pull/1572

[v0.10 backport] ci: update buildx and buildkit to latest

---

commands/build.go
controller/remote/client.go
controller/remote/controller.go

A few commits with various improvements for the remote controller code.
- Don't kill the remote controller immediately after build. We should keep the server alive, since the client can't know exactly what's running on the controller - also we want the behavior for debugging or not to remain relatively similar. At some point in the future, we could introduce logic to the server where it can shut itself down, if no builds are currently being run, however, the server should dictate this, instead of each individual client.
- Add more informative server exit messages, so that the reasons for exit are always available in a log.
- Add signal handling for SIGTERM (in addition to the existing SIGINT). SIGKILL can be caused by pkill and similar programs, which is useful for debugging, etc.
- …

Improvements for remote controller code

---

build/build.go

For certain cases we need to build with `--provenance=false`. However not all build envs (especially in the OSS ethos) have the latest buildx so just blanket setting `--provenance=false` will fail in these cases.
Having an env var allows people to set the value without having to worry about if the buildx version has the `--provenance` flag.

Add env var to disable default attestations

---

build/build.go

For certain cases we need to build with `--provenance=false`. However not all build envs (especially in the OSS ethos) have the latest buildx so just blanket setting `--provenance=false` will fail in these cases.
Having an env var allows people to set the value without having to worry about if the buildx version has the `--provenance` flag.
(cherry picked from commit bc9cb2c66a6ea51bcd4971ee96e22bfe6c6a8ba8)

[0.10] Add env var to disable default attestations

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/SECURITY.md

adds a bug report [issue forms template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms).
will look like this:
___

chore: github issue template

---

controller/remote/controller.go

We should use`os.Executable()` to get the absolute path of the executing binary. https://pkg.go.dev/os#Executable
Otherwise we get the error like:
```
ERROR: failed to use buildx server; use --detach=false: fork/exec /tmp/ctx/buildx: no such file or directory
```
that unexpectedly joins the command name with the current working directory.

controller: use os.Executable() for getting the exceutable path

---

commands/build.go
commands/build_test.go

Following up for https://github.com/docker/buildx/pull/1296#issuecomment-1410470087
Quoted from @jedevc 's comment (https://github.com/docker/buildx/pull/1296#issuecomment-1410470087):
> ```
> BUILDX_EXPERIMENTAL=1 buildx build . --builder=dev --invoke=sh
> INFO: connecting to buildx server
> [+] Building 0.0s (2/2) FINISHED                                                                                                                                  
>  => [internal] load build definition from Dockerfile                                                                                                         0.0s
>  => => transferring dockerfile: 2B                                                                                                                           0.0s
>  => …
```

monitor: resolve paths arguments in client

---

util/gitutil/gitutil.go
util/gitutil/gitutil_test.go

[v0.10 backport] build: strip credentials from remote url on collecting Git provenance info

---

util/gitutil/gitutil.go
util/gitutil/gitutil_test.go

Even though it's fixed by [GHSA-gc89-7gcr-jxqc](https://github.com/moby/buildkit/security/advisories/GHSA-gc89-7gcr-jxqc) in BuildKit 0.11.4 and Buildx uses the latest stable, we want to make sure of the same with Buildx for Git remote URLs.

build: strip credentials from remote url on collecting Git provenance info

---

version/version.go

:arrow_up: Follow-up to https://github.com/docker/buildx/pull/1637#discussion_r1108625166.
:link: Similar to https://github.com/moby/buildkit/pull/3695.
Ensures that `docker buildx version` always begins with a `v` (as in the version tagging convention we use). This will only apply in cases when users build buildx from scratch *without* using the provided build scripts (and just using `go build` directly).

version: add "v" prefix to version for tagging convention consistency

---

bake/bake.go
build/build.go
commands/bake.go
commands/build.go

This PR pushes all `SOURCE_DATE_EPOCH` parsing into the command layer. This fixes two issues (in separate commits):
- For the `build` command, we pull out `SOURCE_DATE_EPOCH` early, and set it in the build-args - then in the case of the remote controller (which connects to a buildx server), we can still set `SOURCE_DATE_EPOCH` correctly.
- For the `bake` command, we pull out `SOURCE_DATE_EPOCH` early, and set it as an override - this fixes https://github.com/NixOS/nixpkgs/pull/221023#discussion_r1134601194, where if `SOURCE_DATE_EPOCH` is set in the test environment (I think this is standard on Nix, though I'm not familiar) we generate additional build args. By splitting into a separate override in the bake command, tests don't end up accidentally reading the contents of the environment.

SOURCE_DATE_EPOCH build arg injection fixes

---

driver/remote/factory.go

:hammer_and_wrench: Fixes what appears to be an oversight I made in https://github.com/docker/buildx/pull/1078.
Previously, we would explicitly error if all TLS parameters were not available. However, it is a perfectly valid use case to connect to a buildkit server that only serves TLS but which does not verify the client (which is possible today with buildctl) - see https://github.com/moby/buildkit/pull/236#issue-283525374:
> - Use a certificate and key on the server and a ca-certificate at the client
>   - an ephemeral key exchange is performed
>   - the client verifies the server certificate
To support this use case, we only need to error if only one of key or cert is set, and the other is not - if both are unspecified, the client will not present a certificate to the server.

remote: avoid tls error if both key and cert are not set

---

.github/ISSUE_TEMPLATE/bug.yml

Found out issues are not correctly formatted like https://github.com/docker/buildx/issues/1697 because we enforce the render for some fields.

chore: fix issue template

---

commands/build.go
commands/build_test.go

Fixes a regression introduced in #1581 - the context path can be a URL, which would not work when using the controller path.
This fixes the detection to not resolve the path to the current working directory if it's a URL, similar to the logic for named contexts.

build: fixup resolvePaths for remote context path

---

bake/bake.go
bake/remote.go
build/build.go
build/utils.go
commands/bake.go
commands/build.go

:hammer_and_wrench: Fixes https://github.com/docker/buildx/issues/1708.
BuildKit's gitutil package behaves slightly differently than moby's urlutil, so we should rely on BuildKit's gitutil when detecting URLs to avoid cases of accidentally producing invalid build requests that can confuse users.

Use buildkit's gitutil package to detect remote git files

---

.github/workflows/build.yml
.github/workflows/docs-release.yml

Avoid pushing image or releasing docs reference from forks on push tag event. This way users can just create a GitHub Release.

ci: check repo origin on push tag event

---

bake/remote.go

Not quite how, but at some point, `ReadRemoteFiles` stopped working with git remotes.
```bash
$ docker buildx bake "git@github.com:docker/buildx.git" --print binaries --progress=plain
#0 building with "container" instance using docker-container driver
#1 [internal] load git source git@github.com:docker/buildx.git
#1 ERROR: Unimplemented: unknown service moby.sshforward.v1.SSH
------
> [internal] load git source git@github.com:docker/buildx.git:
------
ERROR: failed to find target binaries
```
When cloning git remotes, we need to attach the SSH agent service, so that this works:
```bash
docker buildx bake "git@github.com:docker/buildx.git" --print binaries --progress=plain
#0 building with "container" instance using docker-container driver
#1 [internal] load git source …
```

bake: forward default ssh agent for remote bake file

---

bake/bake.go
bake/hcl_test.go
bake/hclparser/hclparser.go
bake/hclparser/stdlib.go

:hammer: Fixes #1150 and #1312
This PR implements the proposal from https://github.com/docker/buildx/issues/1150#issuecomment-1146204434, setting a matrix property on targets which can be used to easily parameterize builds such as https://github.com/docker/buildx/issues/1312#issue-1369020589:
```hcl
group "validate" {
targets = ["validate-lint", "validate-vendor", "validate-docs", "validate-authors"]
}
target "validate-lint" {
dockerfile = "./hack/dockerfiles/lint.Dockerfile"
output = ["type=cacheonly"]
}
target "validate-vendor" {
dockerfile = "./hack/dockerfiles/vendor.Dockerfile"
target = "validate"
output = ["type=cacheonly"]
}
target "validate-docs" {
dockerfile = "./hack/dockerfiles/docs.Dockerfile"
target = "validate"
output = ["type=cacheonly"]
}
target "validate-authors" { …
```

Implement matrix for bake targets

---

bake/bake.go
bake/hcl_test.go

:hammer_and_wrench: Fixes https://github.com/docker/buildx/issues/1721
The docs for `CanIterateElements` aren't quite correct - `AsValueMap` also needs to be able to convert each key into a string. All HCL maps have string keys, so this is fine, but we should explicitly ignore lists, even though you can iterate them (because they have int keys).

bake: fix map type checking to detect matrix property set to list

---

driver/docker/version.go
driver/docker/version_test.go

follow-up https://github.com/moby/moby/releases/tag/v23.0.3

driver: update BuildKit version constraint for docker driver

---

bake/bake.go
commands/build.go

:bug: More context bug fixes :tada:
See commit messages for more details.
1. Fixes resolving the context for remote bake files over SSH:
```
$ docker buildx bake git@github.com:docker/buildx.git
[+] Building 3.8s (2/2) FINISHED                                                                                                                                 docker-container:container
=> CACHED [internal] load git source git@github.com:docker/buildx.git                                                                                                                 3.2s
=> ERROR [internal] load git source git@github.com:docker/buildx.git                                                                                                                  0.0s 
------ …
```

Various context fixups

---

commands/build.go
commands/build_test.go

In 566f41b598b350c2e92df69a4b8392863ae47faf, we added a check to ensure that we avoid resolving http URLs for Dockerfile. However, we have another circumstance we should not resolve the path in - if the context is a remote context, the dockerfile is resolved in that context (see build.go#LoadInputs for more information) :facepalm:
Therefore, we should only resolve the dockerfile to a local directory if the context is also resolved to a local directory.

build: avoid resolution of dockerfile if context is remote

---

monitor/monitor.go

`exec` does not take a server name, so we can remove the unnecessary check here.

monitor: update check for exec args

---

commands/build.go
controller/build/build.go
controller/local/controller.go
controller/remote/controller.go

This ensures that the code used to capture and evaluated a result is only executed when built through the controller. Otherwise, no build result should be recorded.
This ensures that new code added to capture and store the build result for debugging isn't used when BUILDX_EXPERIMENTAL is not set.
See https://github.com/docker/buildx/pull/1640#issuecomment-1513321529 for more information.
**This should be removed at some point in the future** - however, for now, we should have something like this to prevent breaking the state of master while we work on the debugging functionality.

controller: only capture the result when invoked through a controller

---

build/build.go
builder/node.go
commands/create.go
localstate/localstate.go
store/store.go

Some build parameters like directory paths, are never sent to buildkit. But it may still make sense to store them and associate with a unique ref for a build that is used to track other parameters on buildkit side.
@crazy-max

build: support for saving local state by build ref

---

builder/builder.go
store/storeutil/storeutil.go

* Return errors from creating the `NodeGroup`
* Ensure that `b.NodeGroup != nil` before reading from it during validation
This was reported by a Compose user:
* docker/compose#10453

builder: extra init error handling

---

build/build.go
build/result.go
commands/bake.go
commands/build.go
commands/debug-shell.go
controller/build/build.go
controller/control/controller.go
controller/controller.go
controller/local/controller.go
controller/pb/progress.go
controller/remote/client.go
controller/remote/controller.go
controller/remote/controller_nolinux.go
controller/remote/server.go
monitor/monitor.go
util/progress/printer.go

:hammer: Implements https://github.com/docker/buildx/pull/1671#discussion_r1155875282:
> We should create the progress printer outside of each controller call, and pass it into the interface. Then we can lift printWarnings out of the controller entirely tada (should make things a bit neater).
:no_entry_sign: Replaces https://github.com/docker/buildx/pull/1671 (though this PR still doesn't fix the result printing, happy to do that once I get some initial thoughts on this approach)
Refactor the progress printer creation to the caller-side of the controller api. Then, instead of passing around status channels, we can simply pass around the higher level interface progress.Writer, which allows us to correctly pull warnings out of the remote controller.
WDYT @ktock?

controller: refactor progress api

---

go.mod

Basic interfaces satisfy 'comparable' starting with Go 1.20: 
https://github.com/docker/buildx/blob/afcaa8df5fdb9c8c908c8dae325d86a0f8f8c3ef/build/result.go#L32
https://github.com/docker/buildx/blob/afcaa8df5fdb9c8c908c8dae325d86a0f8f8c3ef/vendor/github.com/moby/buildkit/solver/result/result.go#L48

bump go.mod to 1.20

---

docs/reference/buildx_create.md
driver/kubernetes/factory.go
driver/kubernetes/manifest/manifest.go

Addresses #766
Adds a new (optional) `serviceaccount` opt. When provided, it will be set as the created pod's `serviceAccountName`.
Example usage:
```bash
docker buildx create --name example \
--driver kubernetes \
--driver-opt=serviceaccount=example-sa
```

kubernetes driver: add serviceaccount opt

---

monitor/commands/attach.go
monitor/commands/disconnect.go
monitor/commands/exec.go
monitor/commands/kill.go
monitor/commands/list.go
monitor/commands/ps.go
monitor/commands/reload.go
monitor/commands/rollback.go
monitor/monitor.go
monitor/types/types.go

Following-up https://github.com/docker/buildx/pull/1640#issuecomment-1512785173
*From @jedevc 's comment:*
> The commands in the monitor are getting long - we really need to split these up, out of a switch statement, and ideally into 
> something a bit more dynamic. Something like implementations of a monitor.Command interface?
> 
> As inspiration:
> ```golang
> type Command interface {
>     // executes the command
>     Exec(args []string /* anything else we might need*/)
> 
>     // returns command information
>     Info() Info
> }
> 
> type Info struct {
>     // a usage string, e.g. "rollback [--init] [entrypoint] [cmd...]"
>     Usage string
> 
>     // a short description, e.g. "re-runs the interactive container with initial rootfs contents"
>     Description string
> 
>     // a …
```

monitor: Move commands to a separated package

---

driver/docker/driver.go

The client created from the features request is left open, meaning a connection leak will happen if the docker driver is used as a library and a new instance of driver is created.
It would be better if a new client would not be created at all for this check, but the same client would be reused. I will follow-up with combining these but wanted to fix the issue first.

docker: fix connection leak on features check

---

bake/bake.go
commands/bake.go
commands/build.go
commands/create.go
commands/diskusage.go
commands/imagetools/create.go
commands/imagetools/inspect.go
commands/imagetools/root.go
commands/inspect.go
commands/install.go
commands/ls.go
commands/prune.go
commands/rm.go
commands/root.go
commands/stop.go
commands/uninstall.go
commands/use.go
commands/version.go
util/cobrautil/completion/completion.go

closes #1674 
partially solves #1072
Add completion to:
* List builder names for `--builder` persistent flag and as arg for some cmds
* Folders (context) for build command
* List bake targets
```
$ docker __completeNoDesc buildx --builder ""
builder
builder2
buildkit0106
buildkit093
remote-builder
default
desktop-linux
docker201016
docker2300
docker2400
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```
```
$ docker __completeNoDesc buildx --builder "do"
docker201016
docker2300
docker2400
:4
Completion ended with directive: ShellCompDirectiveNoFileComp
```
For bake, can be tested within this repo:
```
$ docker __completeNoDesc buildx ""
bake
build
create
du
help
imagetools
inspect
ls
prune
rm
stop
use
version
:4
Completion ended with directive: …
```

cli: add shell completion

---

monitor/commands/attach.go
monitor/commands/disconnect.go
monitor/commands/ps.go

following-up #1760
This PR fixes monitor to print more understandable messages on errors:
- When `ps` fails because the monitor doesn't attach to any session, print `no attaching session` instead of `unknown ref ""`.
- Avoid `disconnect` silently failing when the monitor doesn't attach to any session. Print `no attaching session` error instead.
- Fix error message of `attach`'s arguments. (`server name must be passed` -> `ID of session or process must be passed`)

monitor: improve error messages

---

commands/build.go

`--detach` shouldn't be the default yet, since it still has the potential to leak some sessions in odd edge cases, and is slightly more painful to debug.
For now, we should set the local controller as the default, with the idea that we can change it back in the future.

controller: default to using local controller

---

build/result.go

Fixes https://github.com/docker/buildx/pull/1640#issuecomment-1513000048
> The second .Build request we create always seems to exit with context cancelled - this means the buildkit logs are full of time="2023-04-18T12:02:37Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Canceled desc = context canceled". This now happens on every build, since we always spin up a second Build right away in getResultAt, instead of waiting until invoke is called.
> 
> Reproducer: buildx build . --builder=dev --detach=false
This is because buildx exits before `Build()` (invoked in a goroutine) completes and returns.
This commit fixes the code to ensure completion of `Build()` on cleanup.
cc @jedevc

controller: avoid "context canceled" error on cleanup

---

bake/compose.go
bake/compose_test.go

:arrow_up: Follow-up to https://github.com/docker/buildx/pull/1753 (cc @nicksieger)
[compose-go v1.13.0](https://github.com/compose-spec/compose-go/releases/tag/v1.13.0) supports the new `dockerfile_inline` and `additional_contexts` properties, so we should translate them to the relevant bake construct.
Will probably need an update in https://docs.docker.com/build/bake/compose-file/ after merging.

Support new compose features in bake

---

docs/guides/debugging.md

Adds some very basic early documentation about monitor mode and debugging - the idea of this is to link to it in our release notes for buildx v0.11, so that we can start getting early feedback from users and work out what we need to focus on in the future :tada:
Not sure where this doc should go actually... we've moved the guides into the docs repo - but ideally we should keep it in buildx, at least while we're quickly iterating on this feature.

docs: add initial guide about debugging monitor mode

---

bake/bake.go
commands/bake.go
docs/bake-reference.md
docs/manuals/bake/file-definition.md
docs/reference/buildx_bake.md

Signed-off-by: David Karlsson <david.karlsson@docker.com>
- Move the bake file reference to `docker/buildx` repo to improve maintainability
- Rewrite the doc to add more examples

docs: move and rewrite bake reference

---

bake/bake.go
commands/bake.go
docs/bake-reference.md
docs/manuals/bake/file-definition.md
docs/reference/buildx_bake.md

:cherries: Cherry-picks https://github.com/docker/buildx/pull/1748
Allows us to point https://github.com/docker/docs/pull/17186 at the v0.10 release branch, so that we can keep multiple versioned copies of the doc.

[v0.10] docs: move and rewrite bake reference

---

driver/kubernetes/context/endpoint_test.go
driver/kubernetes/context/load.go
driver/kubernetes/context/save.go

Hi there :),
Sorry about the previous PR, I opened it prematurely before finalizing all tests, and preparing a proper PR 🙏.
Hopefully, I'm properly following your contribution guidelines, and if I need to change anything please LMK.
This PR attempts to add support in `kuberenetes driver` for `proxy-url` config in the `KUBECONFIG` file - 
[official docs here](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#proxy).
The PR initializes the k8s client config created in `KubernetesConfig` receiver method with the right `proxy-url` parameter.
As a workaround, we were using `HTTPS_PROXY` env var, but that forces every request that `buildx` sends to use the same proxy as well.
This feature, allows **only** the traffic that goes to the k8s cluster (kubeapi) - …

kubernetes driver: add support for proxy-url

---

.github/ISSUE_TEMPLATE/bug.yml

`kind` labels should only be manually added by maintainers after confirming the issue. Otherwise, it can be tricky to sort through all the issues when filtering for legitimate bugs.

github: don't auto-add kind/ labels

---

util/progress/printer.go

:arrow_up: Follow-up to #1737 (e826141af4bbd02872394b8ec1d1beb98b8c44f3)
This fixes a possible race where messages printed directly after calls to NewPrinter may appear before the printer starts. With this change, we delay all of the logs until after.
Example:
```
❯ docker buildx build . --target shell -t test --builder=dev
[+] Building 6.0s (26/26) FINISHED                                                                                            remote:dev
=> [internal] load build definition from Dockerfile                                                                                0.0s
=> => transferring dockerfile: 2.92kB                                                                                              0.0s
=> resolve image config for docker.io/docker/dockerfile:1 …
```

progress: make printer ready only after pausing logrus

---

docs/bake-reference.md

Before this change, there were two bugs:
- the HCL was not valid. in hcl, argument names can't be quoted
- the target argument should be a real target

fix two bugs in bake-reference.md

---

docs/guides/debugging.md

:arrow_up: Follow-up to #1782.
- Fixes typos in the buildkit console output.
- Adds info for the `on-error` and `debug-shell` values to the `--invoke` command.

docs: fixup typo in buildkit console output

---

util/buildflags/cache.go

When the user supply static creds, we must not enrich them with a session token which is unrelated.

Fix AWS Authentication when mixing static creds and IAM profile

---

builder/node.go
commands/inspect.go
docs/reference/buildx_inspect.md

~needs #1430~
Adds builder GC Policies with worker labels. Will be displayed when using `inspect` command:
```console
$ docker buildx inspect
Name:          builder2
Last Activity: 2022-11-30 12:42:47 +0100 CET
Nodes:
Name:           builder20
Endpoint:       unix:///var/run/docker.sock
Driver Options: env.BUILDKIT_STEP_LOG_MAX_SPEED="10485760" env.JAEGER_TRACE="localhost:6831" image="moby/buildkit:latest" network="host" env.BUILDKIT_STEP_LOG_MAX_SIZE="10485760"
Status:         running
Flags:          --debug --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
BuildKit:       v0.10.6
Platforms:      linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, …
```

builder: add worker gc policies and labels

---

go.mod
go.sum
vendor/modules.txt

no changes in vendored files
full diff: https://github.com/moby/moby/compare/v24.0.0...v24.0.1
no changes in vendored files
full diff: https://github.com/docker/cli/compare/v24.0.0...v24.0.1

vendor: github.com/docker/docker and github.com/docker/cli v24.0.1

---

commands/build.go

This was missing, since the driver property can only be fully populated after loading nodes from disk. So we add logic to load the nodes, and check for an error, which ensures that the "docker" driver is always correctly present in the progress description.
I think this was introduced in #1737, when I refactored the progress printing.
Before:
```
$ buildx build . --builder=desktop-linux
[+] Building 2.2s (10/10) FINISHED                                                                                           :desktop-linux
```
After:
```
$ buildx build . --builder=desktop-linux
[+] Building 0.9s (6/6) FINISHED                                                                                       docker:desktop-linux
```

build: fix missing "docker" driver name in build progress

---

commands/build.go
driver/remote/driver.go
tests/build.go

build: fix writing correct image ID with -q

---

util/confutil/container.go

fixes #1827 
Replace invalid characters in the name of the base directory of certificates using the name of the registry which can contain for example a colon when the port is specified.

driver(docker-container): fix incorrect path when writing certs

---

util/logutil/format.go

:arrow_up: Follow-up to https://github.com/docker/buildx/pull/924.
Should help to provide more details for https://github.com/moby/buildkit/issues/3027.
Previously, we would discard the error field provided, which provides valuable contextual information. This patch will include the error field if it is provided. A quick glance through our usage of `WithError` indicates that the errors shown should look mostly reasonable (e.g. we won't display duplicated info).
We still don't want to just print out all the available spans, since that will include the `spanID` and `traceID` from BuildKit, but this singular field is a well-known key, so we should include it whenever present.

Log error from WithError if found

---

build/build.go
driver/docker-container/driver.go
driver/docker/driver.go
driver/driver.go
driver/features.go
driver/kubernetes/driver.go
driver/manager.go
driver/remote/driver.go

related to #1841 
Adds history API feature check for each driver. Also adds cache for driver features.

driver: check history capability

---

build/build.go
build/invoke.go
build/result.go
commands/build.go
controller/build/build.go
controller/local/controller.go
controller/processes/processes.go
controller/remote/controller.go
controller/remote/server.go

:hammer_and_wrench: Replaces #1750. This is a lot neater than the original implementation and doesn't require that we go and change the _entire_ API.
Now, we always perform the full solve request in the main gateway call. This ensures that progress works properly (and doesn't stagger), and makes the lifetime semantics much clearer.
NewResultContext abstracts the details of a successful/failed build, to always return a single ResultContext, even though the details of how a gateway is created is different:
- For a failed build, we can just keep the gateway open.
- For a successful build, we immediately open another gateway and re-evaluate the build definition in that gateway. This should give an instant cache hit (since the build was just successful).

Perform solve request in the main gateway call

---

commands/inspect.go
docs/reference/buildx_inspect.md
driver/features.go

While working on #1846, I wanted to know nodes capability for some builders. I think we should display the list of features when inspecting a builder.
```
$ docker --debug buildx inspect docker2010
Name:   docker2010
Driver: docker
Nodes:
Name:      docker2010
Endpoint:  docker2010
Status:    running
Buildkit:  v0.8.2+eeb7b65
Platforms: linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
Features:
Cache export:       false
Docker exporter:    false
History API:        false
Multiple platforms: false
OCI exporter:       false
```
```
$ docker --debug buildx inspect docker2010
Name:          default
Driver:        docker
Last Activity: 2023-05-30 12:30:59 +0000 UTC
Nodes:
Name:      default
Endpoint:  default
Status:    running …
```

inspect: display builder features

---

bake/bake.go
tests/bake.go
tests/build.go
tests/inspect.go
tests/integration.go
tests/integration_test.go
tests/ls.go
util/gitutil/gitutil.go
util/gitutil/testutil.go
util/gitutil/testutilserve.go

:hammer_and_wrench: Fixes path resolution issue with `BAKE_CMD_CONTEXT`.
In https://docs.docker.com/build/bake/remote-definition/, the following snippet no longer works:
```
$ docker buildx bake "https://github.com/tonistiigi/buildx.git#remote-test" --print
{
"target": {
"default": {
"dockerfile-inline": "FROM alpine\nWORKDIR /src\nCOPY . .\nRUN ls -l \u0026\u0026 stop\n"
}
}
}
```
Instead returning the following error:
```
$ docker buildx bake "https://github.com/tonistiigi/buildx.git#remote-test" --print
ERROR: Rel: can't make . relative to /home/jedevc/Documents/Docker/buildx
```
This issue comes from https://github.com/docker/buildx/blob/341fb65f6f568696ed5e2585eb747aedaed7ee1a/bake/bake.go#L1007-L1010
To resolve this issue, we need to …

bake: fix BAKE_CMD_CONTEXT relative path resolution

---

build/build.go
cmd/buildx/main.go
commands/bake.go
commands/build.go
controller/pb/progress.go
util/desktop/desktop.go
util/progress/printer.go
util/progress/writer.go

https://github.com/docker/buildx/assets/1951866/41a8935a-438f-48f4-be2c-957a56e80f8f
Display build details links if Docker Desktop build backend is enabled.
I'm using an OSC 8 escape sequence with the target links to be displayed in the terminal. Most of the terminal emulators auto-detect when a URL appears onscreen and allow to conveniently open them (e.g. via Ctrl+click or Cmd+click, or the right click menu). A hyperlink is opened upon encountering an OSC 8 escape sequence with the link. The list of supporting terminal emulators and terminal-based apps can be seen here: https://github.com/Alhadis/OSC8-Adoption/.
Atm it only displays links when build is completed and not for active builds. For active builds we need to put links right before build starts so user can just follow build …

build: display build details link

---

monitor/commands/attach.go
monitor/commands/disconnect.go
monitor/commands/exec.go
monitor/commands/kill.go
monitor/commands/list.go
monitor/commands/ps.go
monitor/commands/reload.go
monitor/commands/rollback.go
monitor/monitor.go
monitor/types/types.go

This commit adds long help messages about the usage of  the monitor commands .
example:
```console
(buildx) help attach
attach to a buildx server or a process in the container
Usage:
attach ID
ID is for a session (visible via list command) or a process (visible via ps command).
If you attached to a process, use Ctrl-c-a for swithcing the monitor to that process's STDIO.
```

monitor: add long help for commands

---

build/build.go
util/dockerutil/client.go
util/dockerutil/features.go

Moby with the containerd store supports importing multi-platform OCI images, which means we *should* be able to add functionality to have `--load` work with multi-platform images.
Before:
```
$ buildx build . --platform linux/amd64,linux/arm64 --builder container --load
[+] Building 0.1s (1/1) FINISHED                                                                                         docker-container:container
=> [internal] connecting to local controller                                                                                                  0.0s
ERROR: failed to build: docker exporter does not currently support exporting manifest lists
```
After:
```
$ buildx build . --platform linux/amd64,linux/arm64 --builder container --load
[+] Building 4.0s (24/24) FINISHED …
```

`--load` with moby containerd store should use the `oci` exporter

---

commands/build.go
monitor/monitor.go

When running `--invoke` against images that have `Cmd` set, the interactions with `Entrypoint` start to cause issues like the following:
/usr/local/bin/bash: /usr/local/bin/bash: cannot execute binary file
Or:
sh: can't open 'bash': No such file or directory
This patch fixes those by explicitly setting `Cmd` to be empty if it is unspecified and `Entrypoint` is being set, which matches `docker`'s behavior:
$ docker image inspect --format '{{ json .Config.Entrypoint }} + {{ json .Config.Cmd }}' bash
["docker-entrypoint.sh"] + ["bash"]
$ docker create --name foo --entrypoint bash bash
$ docker container inspect --format '{{ json .Config.Entrypoint }} + {{ json .Config.Cmd }}' foo
["bash"] + null
$ docker rm foo
$ docker create --name foo bash ls
$ docker container inspect --format '{{ json …

Fix a couple `--invoke` entrypoint interaction bugs

---

commands/build.go
docs/guides/debugging.md

This commit allows specifying a JSON array to the long-form entrypoint and args.
Non-JSON-array value can still be specified. Buildx treats the value as a JSON
array only when it can be parsed as a JSON array.
```console
$ BUILDX_EXPERIMENTAL=1 /tmp/out/buildx build --invoke 'entrypoint=["sh"],"args=[""-c"", ""env | grep FOO""]",env=FOO=bar' /tmp/ctx3
[+] Building 1.2s (8/8) FINISHED                        docker-container:latest
=> [internal] connecting to local controller                              0.0s
=> [internal] load build definition from Dockerfile                       0.0s
=> => transferring dockerfile: 100B                                       0.0s
=> [internal] load metadata for docker.io/library/busybox:latest          0.7s
=> [internal] load .dockerignore …
```

invoke: Allow JSON array for entrypoint and args flags in long form 

---

bake/bake.go
bake/bake_test.go
commands/bake.go
commands/build.go
commands/debug-shell.go
util/cobrautil/completion/completion.go

Use command.Cli::In() if it is set, use os.Stdin otherwise.

build(cli): allow passing in-stream using command.Cli

---

go.mod
go.sum
vendor/modules.txt

no changes in vendored files
full diff: https://github.com/docker/docker/compare/v24.0.1...v24.0.2
no changes in vendored files
full diff: https://github.com/docker/cli/compare/v24.0.1...v24.0.2

vendor: github.com/docker/docker and github.com/docker/cli v24.0.2

---

build/build.go
build/url.go
builder/node.go
driver/docker-container/driver.go
driver/docker/driver.go
driver/driver.go
driver/features.go
driver/kubernetes/driver.go
driver/manager.go
driver/remote/driver.go

This makes sure there is no extra client initialization/request unless it is actually needed to detect.
We could also return the history API indicator with the build result or add a cap for it. Actually, if we want to be really sneaky we could use another cap like `source.policy` that was also added in v0.11 to detect this.

avoid extra client for history API detection

---

util/dockerutil/client.go

:arrow_up: Follow-up to https://github.com/docker/buildx/pull/1813#discussion_r1219880911.

dockerutil: cache feature collection

---

bake/bake.go
bake/bake_test.go

:hammer_and_wrench: Fixes https://github.com/docker/buildx/issues/1627
We need to resolve the strip the `cwd://` prefix before attempting to resolve the dockerfile. Otherwise, we'll get the `cwd://` prefix in the dockerfile name, which isn't stripped out later.
Also added this to the test case, where previously we would get a `cwd://` in the dockerfile name, now we correctly resolve it.

bake: fix incorrect dockerfile resolution against `cwd://` context

---

.github/workflows/build.yml
go.mod
go.sum
tests/integration.go
tests/workers/docker-container.go
tests/workers/docker.go
tests/workers/remote.go
vendor/github.com/moby/buildkit/client/llb/fileop.go
vendor/github.com/moby/buildkit/client/llb/meta.go
vendor/github.com/moby/buildkit/client/llb/source.go
vendor/github.com/moby/buildkit/client/llb/state.go
vendor/github.com/moby/buildkit/util/testutil/integration/containerd.go
vendor/github.com/moby/buildkit/util/testutil/integration/dockerd.go
vendor/github.com/moby/buildkit/util/testutil/integration/oci.go
vendor/github.com/moby/buildkit/util/testutil/integration/run.go
vendor/modules.txt

~~:warning: Requires https://github.com/moby/buildkit/pull/3954.~~
This means that we can run our docker-container tests in parallel again, which can help speed up our test runs by a *significant* amount.

tests: share single docker between docker-container backends

---

.github/workflows/build.yml
Dockerfile
tests/build.go
tests/inspect.go
tests/ls.go
tests/workers/docker.go

follow-up https://github.com/docker/buildx/pull/1886#discussion_r1233562589
Adds `docker+containerd` worker to our matrix to be able to test against dockerd with containerd storage enabled.

test: register docker worker with containerd snapshotter

---

hack/build

This is useful for setting things like -buildmode=pie when packaging docker-buildx for distributions.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

build: add GO_EXTRA_FLAGS argument

---

build/build.go
tests/build.go
tests/integration.go

If pull option is not set we should prefer local image resolution for docker driver. In follow-up we should look at making the `--pull` flag accepting a specific state like the `docker run` command does: https://docs.docker.com/engine/reference/commandline/run/#pull

build: prefer local image resolution for docker driver

---

bake/bake.go
bake/bake_test.go
store/store_test.go
store/storeutil/storeutil.go
store/util.go

* https://github.com/docker/buildx/pull/1880
* https://github.com/docker/buildx/pull/1879

[v0.11] cherry-picks for v0.11.1

---

util/buildflags/entitlements.go

Use buildkit's parsing of entitlements to make sure that accepted values match what's accepted by BuildKit.

utils/buildflags: ParseEntitlements(): use BuildKit's parsing

---

bake/compose.go
bake/compose_test.go

fixes https://github.com/docker/buildx/issues/1902
If a profile is being set in the compose file, build will not run against this service unless this profile is enabled: https://docs.docker.com/compose/compose-file/03-compose-file/#profiles
For compose it makes sense but bake doesn't have any support for profiles so I think we should just ignore them: https://github.com/compose-spec/compose-go/blob/532cd92682a3f00c22c1286f7eedccab2a232baa/types/project.go#L258

bake: ignore profiles in compose definitions

---

controller/build/build.go

The `--cgroup-parent` option had no effect in build containers due to the CgroupParent field in build.Options not being set. Related: moby/moby#45796.

Controller: Include CgroupParent in build.Options

---

tests/build.go
util/desktop/desktop.go

Before
```
foo@bar:~ $ docker buildx build .
...
------
Dockerfile:356
355 |     ARG TARGETPLATFORM
356 | >>> RUN --mount=type=cache,sharing=locked,id=moby-rootlesskit-aptlib,target=/var/lib/apt \
357 | >>>     --mount=type=cache,sharing=locked,id=moby-rootlesskit-aptcache,target=/var/cache/apt \
358 | >>>         apt-get update && xx-apt-get install -y --no-install-recommends \
359 | >>>             gcc libc6-dev
360 |     ENV GO111MODULE=on
ERROR: failed to solve: process "/bin/sh -c apt-get update && xx-apt-get install -y --no-install-recommends             gcc libc6-dev" did not complete successfully: exit code: 100
View build details: docker-desktop://dashboard/build/default/default/oj5lusuq2n0ufovvphbaxfjn0foo@bar:~ $
```
After
```
foo@bar:~ …
```

build: missing newline when printing build details on error

---

build/build.go
build/utils.go
driver/manager.go

fixes #1832 
related to https://github.com/moby/moby/pull/45767

build: fix host-gateway handling

---

bake/bake.go
bake/bake_test.go

Revert "bake: fix incorrect dockerfile resolution against cwd:// context"
As discussed, since this is a behavior change, we should't pull this to a patch release.

Revert "bake: fix incorrect dockerfile resolution against cwd:// context"

---

Dockerfile
docker-bake.hcl

A temporary workaround for "http: invalid Host header" introduced in go 1.20.6.
In the future, we should probably keep this pinned to minor versions to prevent these kind of breakages. We can bump these manually in the future without much effort.
This also fixes our CI in the meantime :)

hack: force go version to 1.20.5

---

driver/kubernetes/context/load.go
driver/kubernetes/context/save.go

Investigating #1884 it turned out that Bearer token is not being passed along from config file, resulting in described issues. This PR adds Bearer Token support for authentication.
This fix was tested with GitLab Kubernetes Agent Server successfully.

Add Bearer token support

---

go.mod
go.sum
vendor/github.com/docker/docker/api/swagger.yaml
vendor/github.com/docker/docker/api/types/configs.go
vendor/github.com/docker/docker/api/types/image/opts.go
vendor/github.com/docker/docker/api/types/registry/registry.go
vendor/github.com/docker/docker/client/client.go
vendor/github.com/docker/docker/client/container_create.go
vendor/github.com/docker/docker/client/hijack.go
vendor/github.com/docker/docker/client/interface.go
vendor/github.com/docker/docker/client/request.go
vendor/github.com/docker/docker/pkg/idtools/idtools_unix.go
vendor/modules.txt

relates to
* https://github.com/moby/moby/pull/45942
* https://github.com/moby/moby/issues/45935
closes #1944 
client: define a "dummy" hostname to use for local connections fixes "http: invalid Host header" errors when compiling with go1.20.6 or go1.19.11
full diff: https://github.com/docker/docker/compare/v24.0.2...36e9e796c6fc

vendor: github.com/docker/docker@24.0 36e9e79

---

builder/node.go

Reported by @jer-k on Slack: https://dockercommunity.slack.com/archives/C7S7A40MP/p1689292389773349
> It appears that https://github.com/docker/buildx/pull/1430 (cc: @crazy-max)) removed the `commands/util.go` file. That file was the only place that called `ctxkube.ConfigFromEndpoint`: https://github.com/docker/buildx/blob/69421182cac77598aa6bba886f5241d71e57f00a/driver/kubernetes/context/load.go#L168
> 
> From what I can tell, this makes it so any buildx instances that are using the Kubernetes driver require either
> 1. `KUBECONFIG=<path_to_config>` to be prepended to any `docker buildx` commands
> 2. `KUBECONFIG` is exported as an environment variable in your shell
> 3. `.kube/config` to point to the cluster
> 
> Previously though `ctxkube.ConfigFromEndpoint` would extract the …

k8s: fix missing kubeconfig check from endpoint

---

go.mod
go.sum
vendor/github.com/docker/docker/api/swagger.yaml
vendor/github.com/docker/docker/api/types/configs.go
vendor/github.com/docker/docker/api/types/image/opts.go
vendor/github.com/docker/docker/api/types/registry/registry.go
vendor/github.com/docker/docker/client/client.go
vendor/github.com/docker/docker/client/container_create.go
vendor/github.com/docker/docker/client/hijack.go
vendor/github.com/docker/docker/client/interface.go
vendor/github.com/docker/docker/client/request.go
vendor/github.com/docker/docker/pkg/idtools/idtools_unix.go
vendor/modules.txt

- backport of https://github.com/docker/buildx/pull/1945
relates to
* https://github.com/moby/moby/pull/45942
* https://github.com/moby/moby/issues/45935
closes #1944 
client: define a "dummy" hostname to use for local connections fixes "http: invalid Host header" errors when compiling with go1.20.6 or go1.19.11
full diff: https://github.com/docker/docker/compare/v24.0.2...36e9e796c6fc
(cherry picked from commit 8a3a646c6130937eba92caca09a6beb4d2a1bcda)

[0.11 backport] vendor: github.com/docker/docker@24.0 36e9e79

---

Dockerfile
docker-bake.hcl
hack/dockerfiles/docs.Dockerfile
hack/dockerfiles/generated-files.Dockerfile
hack/dockerfiles/lint.Dockerfile
hack/dockerfiles/vendor.Dockerfile

- backport https://github.com/docker/buildx/pull/1936
- backport https://github.com/docker/buildx/pull/1946

[0.11 backport] update go to 1.20.6

---

build/result.go

Populating result handle should be internal otherwise it will be recorded wrongfully to the history (cc @nico1510)

build: mark result handle build as internal

---

build/result.go

[0.11 backport] build: mark result handle build as internal

---

builder/node.go

[0.11 backport] k8s: fix missing kubeconfig check from endpoint

---

commands/root.go
go.mod
go.sum
vendor/github.com/docker/cli/cli/command/cli.go
vendor/github.com/docker/cli/cli/connhelper/commandconn/commandconn.go
vendor/github.com/docker/cli/cli/connhelper/connhelper.go
vendor/modules.txt

full diff: https://github.com/docker/cli/compare/v24.0.2...v24.0.4
notable changes:
- ssh: fix error on commandconn close, add ping and default (https://github.com/docker/cli/pull/4226)
- commandconn: return original error while closing  (https://github.com/docker/cli/pull/4394)

vendor: github.com/docker/cli v24.0.4

---

commands/root.go
go.mod
go.sum
vendor/github.com/docker/cli/cli/command/cli.go
vendor/github.com/docker/cli/cli/connhelper/commandconn/commandconn.go
vendor/github.com/docker/cli/cli/connhelper/connhelper.go
vendor/modules.txt

- backport https://github.com/docker/buildx/pull/1959
full diff: https://github.com/docker/cli/compare/v24.0.2...v24.0.4
notable changes:
- ssh: fix error on commandconn close, add ping and default
- commandconn: return original error while closing
(cherry picked from commit cc718b34443428ea15933948abf074b20aacf599)

[0.11 backport] vendor: github.com/docker/cli v24.0.4

---

docs/reference/buildx_create.md
driver/kubernetes/factory.go
driver/kubernetes/factory_test.go
driver/kubernetes/manifest/manifest.go

This implements custom annotations and labels to be included in kubernetes manifests. Currently, the user has to patch them in a subsequent call.
Motivation: We provide a tool for developers to create/remove buildx builders on a shared k8s cluster. To prevent wasting resources, the buildx deployments are patched with a label (for filtering) and an annotation (an `expire-after` timestamp). A cron janitor eventually finds and removes them. The user may also refresh the timestamp in order to retain their cache for longer if they desire.
Issue: Because creating the builder and patching the annotations requires two calls, I need to handle the cases when the `create` call fails. This isn't always possible in an exception handler, for instance when this happens on a CI server that gets killed …

kubernetes driver // allow custom annotations and labels

---

build/build.go

Very tiny fix from when I was looking around the area :smile:

chore: tidy splitToDriverPairs to avoid unneccessary int

---

docs/reference/buildx_build.md

follow-up https://github.com/moby/buildkit/pull/3582
Update docs since buildinfo has been removed from BuildKit. We need to keep some buildinfo logic in buildx for backward compat with old builders. Such as:
https://github.com/docker/buildx/blob/4a73abfd645457ee8819855cb1a337ab23f833dc/build/build.go#L559-L562
~Keeping in draft until BuildKit 0.12.~

docs: update since buildinfo removal

---

util/progress/reset.go

No other parts of the progress rendering modify the inputs, so we should avoid this as well.
This actually fixes an edge case in `pushWithMoby` which writes the same VertexStatus multiple times, modifying the timestamps and similar. However, if the operation takes long enough the small time difference can accumulate, and move the Start time far into the past.

progress: don't modify ResetTime inputs

---

Dockerfile
hack/dockerfiles/docs.Dockerfile
hack/dockerfiles/generated-files.Dockerfile
hack/dockerfiles/lint.Dockerfile
hack/dockerfiles/vendor.Dockerfile

Includes a fix for CVE-2023-29409
go1.20.7 (released 2023-08-01) includes a security fix to the crypto/tls package, as well as bug fixes to the assembler and the compiler. See the Go 1.20.7 milestone on our issue tracker for details:
- https://github.com/golang/go/issues?q=milestone%3AGo1.20.7+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.20.6...go1.20.7
From the mailing list announcement:
[security] Go 1.20.7 and Go 1.19.12 are released
Hello gophers,
We have just released Go versions 1.20.7 and 1.19.12, minor point releases.
These minor releases include 1 security fixes following the security policy:
- crypto/tls: restrict RSA keys in certificates to <= 8192 bits
Extremely large RSA keys in certificate chains can cause a client/server
to expend …

update to go1.20.7

---

docs/guides/debugging.md
monitor/commands/attach.go

- 6f37d9bee7e6dd2aaf3813bd0414c4aaee456740 : monitor: attach: fix typo in long help message
- ca08eb65e23672273311780e7897997f46462a93 : docs: debug: update the output of help command to the latest message

docs: monitor: Tiny fixes for help messages

---

build/build.go
tests/build.go

On drivers that do not support multi-platform builds (the default `docker` driver), we do not support building attestations (unless using the containerd store).
We need to check this feature before attempting to build using attestations.
(thanks @cdupuis for the find :tada:)

build: error on attests on non-multiplatform driver

---

commands/root.go

When running in standalone mode, the --debug flag passed to docker cannot be passed. The docker cli also supports a DEBUG env var, however, in standalone mode this won't be consumed.
This patch reads the contents of the DEBUG environment variable and enables debugging logs when it's been set.

commands: consume DEBUG environment variable

---

build/build.go
commands/imagetools/create.go
docs/reference/buildx_imagetools_create.md
tests/imagetools.go
util/imagetools/create.go

Currently there isn't any way to add annotations to OCI image index for [multi-arch](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners). The use case is to have a description in ["About this version"](https://github.com/inspektor-gadget/inspektor-gadget/pkgs/container/inspektor-gadget/106798013?tag=v0.18.1) in GitHub. It will introduce an optional flag of `--annotation` to `imagetools create` to allow adding OCI annotations.
Related: #1171 
```
$ ./bin/build/buildx  imagetools create  -t ghcr.io/inspektor-gadget/inspektor-gadget:v0.18.1 ghcr.io/inspektor-gadget/inspektor-gadget:v0.18.1@sha256:c3780808973801b24c80f8b46835b882fe0d69c08a4460333f28143569665861 ghcr.io/inspektor-gadget/inspektor-gadget:v0.18.1@sha256:d6d5661b02002aa8035e035 …
```

imagetools: Allow annotations for OCI image index

---

util/dockerutil/client.go
util/dockerutil/progress.go

- fixes https://github.com/docker/buildx/issues/593
- fixes https://github.com/docker/build-push-action/issues/321
```dockerfile
FROM nvidia/cuda:12.1.0-cudnn8-devel-ubi9
RUN dd if=/dev/zero of=/output.dat bs=8192M count=1
RUN uname -a
```
```
#6 [2/3] RUN dd if=/dev/zero of=/output.dat bs=8192M count=1
#6 9.653 0+1 records in
#6 9.653 0+1 records out
#6 9.657 2147479552 bytes (2.1 GB, 2.0 GiB) copied, 9.53004 s, 225 MB/s
#6 DONE 12.0s
#7 [3/3] RUN uname -a
#7 0.066 Linux buildkitsandbox 5.15.0-1042-azure #49-Ubuntu SMP Tue Jul 11 17:28:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
#7 DONE 0.1s
#8 exporting to docker image format
#8 exporting layers
#8 exporting layers 14.1s done
#8 exporting manifest sha256:00f00d30fad0d29a48903e5bd5e62f0eb4fa3e64cc4c0c457068e2fb9580e274 done
#8 exporting …
```

build: read body response to check for erroneous image export to docker

---

driver/docker-container/driver.go

Fixes the race condition where two boots are executed simultaneously across multiple processes.
Additionally, this would probably also fix https://github.com/docker/buildx/issues/1868.
We initially check to see if the container exists, but if during container creation we get a name conflict, we don't treat this error as a hard failure, and instead move immediately into waiting for the node to boot.
Not 100% sure about this, we could alternatively attempt to get a file lock when attempting to create the docker container (@crazy-max's suggestion).

docker-container: avoid fail if container conflict

---

bake/bake_test.go
bake/compose_test.go

related to https://github.com/docker/buildx/pull/1971
Since https://github.com/docker/buildx/pull/1971 the context path is now absolute and although the tests run fine in our containerized environment, it wouldn't work running the tests locally, such as:
```
=== CONT  TestReadTargetsCompose
bake_test.go:306: 
Error Trace:	X:/dev/neard/www/github/docker_org/buildx/bake/bake_test.go:306
Error:      	Not equal: 
expected: "/src/bake"
actual  : "/home/foo/buildx/bake"
```

test: fix non-deterministic compose context path

---

bake/bake.go

The `Attest` field is out-of-order, and has the wrong comment attached to it.
This fixup just reorders it to be in the right place.

chore: reorder target fields

---

commands/build.go

This fixes the bug that `--invoke` ignores command name specified as the short-form argument. Sorry, this seems introduced in https://github.com/docker/buildx/pull/1970 that uses `InvokeConfig.NoCmd` in an incorrect way in the short-form flag :pray: .
master branch:
Command name (`ps`) on the short-form flag is ignored.
```console
$ BUILDX_EXPERIMENTAL=1 /tmp/out/buildx build --invoke ps /tmp/ctx3/
...
Launching interactive container. Press Ctrl-a-c to switch to monitor console
Interactive container was restarted with process "a41yfa5q4d20h1ezin01ndcun". Press Ctrl-a-c to switch to the new container
root@buildkitsandbox:/# 
```
This PR:
Command name (`ps`) is enabled.
```
$ BUILDX_EXPERIMENTAL=1 /tmp/out/buildx build --invoke ps /tmp/ctx3/
...
Launching interactive container. Press …
```

debug: fix short-form custom command name on `--invoke` isn't used

---

commands/build.go
tests/build.go

fixes https://github.com/docker/buildx/issues/2022
Adds validation for build arguments and labels that must have a key to be consistent with previous implementation of the `build` command in `docker/cli`.
We already have this validation for bake when we set new overrides: https://github.com/docker/buildx/blob/f6b7a3c522687b64bf406ca9ce48a1e9b5096f20/bake/bake.go#L430-L432 https://github.com/docker/buildx/blob/f6b7a3c522687b64bf406ca9ce48a1e9b5096f20/bake/bake.go#L456-L458 but missing for labels.

build: validate build args and labels

---

build/build.go
driver/features.go
tests/build.go

Improve error messages, and add documentation links, for errors related to the limited capabilities of the `docker` driver
- needs docker/docs#17902
Closes #1996

build: improve error messages for docker driver

---

build/build.go
util/dockerutil/client.go
util/dockerutil/progress.go

Adds sublogger to show load progress when importing to docker:
https://github.com/docker/buildx/assets/1951866/9da993bc-1f71-4222-93a2-621a51715ec7
```
$ docker buildx create --name foo
$ docker buildx --builder foo bake --load https://github.com/crazy-max/docker-docker.git
...
#35 exporting to docker image format
#35 exporting layers
#35 exporting layers 7.3s done
#35 exporting manifest sha256:3ddc93cb4082a582552e7b32cfe439ae4fc2c003f353a8259e055a8b9e373fb6 0.0s done
#35 exporting config sha256:b2f1eaf0595fd4ccb26c63715aca3698d6433d9e34220cd8db358e0332d2b18e 0.0s done
#35 sending tarball
#35 ...
#36 importing to docker
#36 loading layer 4270763b4b7f 294.91kB / 27.73MB 3.0s done
#36 loading layer fc8ab555be16 557.06kB / 70.77MB 2.5s done
#36 loading layer b7eb284ce929 163.84kB / 13.78MB …
```

build: sublogger to show docker load progress output

---

commands/inspect.go

Before:
```
$ docker buildx inspect builder
Name:          builder
Last Activity: 2023-09-12 20:09:21 +0000 UTC
Nodes:
Name:           builder0
Endpoint:       unix:///var/run/docker.sock
Driver Options: env.BUILDKIT_STEP_LOG_MAX_SIZE="10485760" env.BUILDKIT_STEP_LOG_MAX_SPEED="10485760" env.JAEGER_TRACE="localhost:6831" image="moby/buildkit:master" network="host"
Status:         stopped
Flags:          --debug --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
Platforms:
```
Now:
```
$ docker buildx inspect builder
Name:          builder
Last Activity: 2023-09-12 20:09:21 +0000 UTC
Nodes:
Name:           builder0
Endpoint:       unix:///var/run/docker.sock
Driver Options: …
```

inspect: do not display platforms field if empty

---

commands/create.go

If the boot command hung or took a long time, it blocked any read
operations (such as `buildx ls`).
When the boot happens, we no longer need to hold the file lock so we can
release it. Releasing multiple times is legal and causes whichever
release that is second to be a no-op so the defer is kept to ensure the
lock is released even when an error condition happens.
Fixes #2062.

commands: release the file lock before attempting to boot during create

---

bake/compose_test.go
go.mod
go.sum
vendor/github.com/compose-spec/compose-go/cli/options.go
vendor/github.com/compose-spec/compose-go/loader/loader.go
vendor/github.com/compose-spec/compose-go/loader/paths.go
vendor/github.com/compose-spec/compose-go/schema/compose-spec.json
vendor/github.com/compose-spec/compose-go/template/template.go
vendor/github.com/compose-spec/compose-go/types/develop.go
vendor/github.com/compose-spec/compose-go/types/types.go
vendor/modules.txt

Bake is currently broken for projects with a `compose.yaml` that implements the latest version of the compose spec (the one used by Docker Compose v1.22)

vendor: update compose-go to v1.19.0

---

build/build.go
build/result.go
driver/client.go
driver/docker-container/driver.go
driver/docker/driver.go
driver/driver.go
driver/kubernetes/driver.go
driver/manager.go
driver/remote/driver.go

This client abstracts from buildkit client. This will allow further enhancement like caching remote driver responses.

(drivers): Introduce a client interface

---

docs/reference/buildx_create.md
driver/docker-container/driver.go
driver/docker-container/factory.go

fixes #2049
limit builder container memory
use: `docker buildx create --driver docker-container --driver-opt memory=32G --name zmicro`

feat: support memory/cpu driver options for docker-container

---

builder/builder.go
builder/node.go
commands/bake.go
commands/build.go
commands/create.go
commands/diskusage.go
commands/inspect.go
commands/ls.go
commands/prune.go
commands/rm.go
commands/stop.go
controller/build/build.go
driver/docker-container/driver.go
driver/docker-container/factory.go
driver/docker/driver.go
driver/docker/factory.go
driver/driver.go
driver/kubernetes/driver.go
driver/kubernetes/factory.go
driver/manager.go
driver/remote/driver.go
driver/remote/factory.go

if you want some changes apart, it then needs:
* closes https://github.com/docker/buildx/pull/2074
* closes https://github.com/docker/buildx/pull/2075
In some cases it can be useful to set additional dial metadata to the client.

driver(docker): opt to set additional dial meta to the client

---

localstate/localstate.go

related to https://github.com/docker/buildx/actions/runs/6515548684/job/17698128684#step:10:410
```
+ docker buildx rm buildx-test-c52e7aa2a683a0d852229cc602f172c4
ERROR: remove /home/runner/.docker/buildx/refs/__group__/johhgzt9x9jlb16iw392e5bni: no such file or directory
```
Local state group removal can be racy because of the go routine removing each builder node. This removes the go routine that doesn't seem necessary here. Maybe instead we could add a mutex on group removal.

build: fix racy localstate group removal

---

.golangci.yml
Dockerfile
bake/compose.go
bake/hclparser/hclparser.go
build/build.go
commands/use.go
controller/pb/path_test.go
driver/docker-container/driver.go
driver/kubernetes/driver.go
hack/dockerfiles/docs.Dockerfile
hack/dockerfiles/generated-files.Dockerfile
hack/dockerfiles/lint.Dockerfile
hack/dockerfiles/vendor.Dockerfile
store/nodegroup.go
store/store.go
store/store_test.go
tests/workers/docker-container.go

https://tip.golang.org/doc/go1.21
Updates golangci-lint to 1.54.2 and its configuration to show all lint issues and align exclude rules with buildkit ones as well: https://github.com/golangci/golangci-lint/releases/tag/v1.54.2

update to go 1.21.3

---

bake/bake.go
bake/bake_test.go
build/build.go
tests/bake.go

fixes #1627
Allow to use a local dockerfile with a remote bake definition like we do for context using `cwd://` protocol.
Can be tested with https://github.com/crazy-max/buildx-buildkit-tests/tree/main/buildx-1627:
```bash
$ cd /tmp
$ cat <<EOT >> Dockerfile.app
FROM scratch
COPY foo /foo
EOT
$ docker buildx bake https://github.com/crazy-max/buildx-buildkit-tests.git#:buildx-1627
```

bake: local dockerfile support for remote definition

---

bake/bake.go
bake/bake_test.go
commands/bake.go
tests/bake.go
util/cobrautil/completion/completion.go

If no bake definition are specified, it will currently consume the default ones in this specified order: https://github.com/docker/buildx/blob/05b88216251d20597e6a457f0d454dbbeb8d03eb/bake/bake.go#L47-L53
Following-up a discussion with @milas:
> If you have both `docker-bake.hcl` AND `docker-compose.yml` in a directory, Bake always parses the Compose file unless you pass `-f docker-bake.hcl` explicitly
> So if you have a syntax error in your compose file:
> ```
> ❯ docker buildx bake services
> [+] Building 0.0s (0/0)                                                                                                                  cloud:cloud-stage
> ERROR: parsing : yaml: line 3: mapping values are not allowed in this context
> ```
> But:
> ```
> ❯ docker buildx bake -f docker-bake.hcl …
```

bake: display read definition files in build output

---

builder/builder.go

fixes https://github.com/docker/setup-buildx-action/issues/228#issuecomment-1510707981
Before:
```
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 1.6s done
#1 creating container buildx_buildkit_builder-cc8757dc-a94d-4ea0-ac4a-592280318e710 done
#1 ERROR: Error response from daemon: Windows does not support privileged mode
------
> [internal] booting buildkit:
------
Name:          builder-cc8757dc-a94d-4ea0-ac4a-592280318e71
Last Activity: 2023-10-23 12:13:15 +0000 UTC
Nodes:
Name:      builder-cc8757dc-a94d-4ea0-ac4a-592280318e710
Endpoint:  npipe:////./pipe/docker_engine
Status:    inactive
Flags:     --allow-insecure-entitlement security.insecure --allow-insecure-entitlement …
```

builder: return error if all nodes fail to boot

---

commands/build.go
commands/debug/root.go
controller/processes/processes.go
monitor/commands/reload.go
monitor/monitor.go

- 38137b29dd03335611fe190b4ed467e51804bd55 : fixes the following mentioned in https://github.com/docker/buildx/pull/2006#pullrequestreview-1681377351
- > * There is an error in Dockerfile command (eg. change `RUN` to `RUN2`). I get an error. Now I run `reload`. It builds up to the Dockerfile error again but this time I don't see any error.
- b06a55cf53b0c5b34d1e1bffa058394cd673ce2d : following-up for https://github.com/docker/buildx/pull/2006/commits/0dd89f602922851a3159976972832728aafa0bd3
- 267e30a19cd5972187a6553c00e0442e8f45d150 : fixes the following mentioned in https://github.com/docker/buildx/pull/2006#pullrequestreview-1681377351
- > * I run `debug build .` and get an error. I fix the error and issue `reload`. Now my build succeeds. I run some more interactive processes and …

debug: Following-up patches for error messages

---

bake/bake.go
bake/hcl_test.go
bake/hclparser/hclparser.go
bake/hclparser/merged.go

Carry changes from #1025 related to an issue with hcl attributes not set if diagnosed as duplicated: https://github.com/docker/buildx/pull/1025#discussion_r843336438.
~Needs to fork the [merge logic from hcl repo](https://github.com/hashicorp/hcl/blob/main/merged.go). It might be better if hcl exposed its mergedbodies interface. Don't think we should fork the repo and vendor it here with this small change though. Maybe there is a better way?~

bake: set attribute even if diagnosed as duplicated

---

commands/bake.go
tests/bake.go

As I mentioned on Slack. This adds the ability to source additional local build definition files when sourcing Bake files via a remote url.
Prefixing a file with `cwd://` will source the bake file from the local machine, instead of the remote location.
Local files will be read/have precedence before remote files.
Usage:
```
docker buildx bake https://github.com/example/upstream.git --file cwd://docker-bake.override.hcl --print
```
This will source a default file from the example/upstream repository, and also source a build definition from the local machine.
I'm a Go novice so any suggestions are welcome 😄 
Thanks!

command(bake): Specify local and remote bake files

---

bake/bake.go
bake/hcl_test.go

Fixes https://github.com/docker/buildx/issues/2104
Previously, we would fail while trying to use the global "target" field when using a matrix. The contents of the matrix really don't matter for this.
What was happening was that we would copy the "target" property into the child evaluation context, so that when it was updated on the parent, it wouldn't propagate to the child. The correct behavior here is to avoid copying variables from the target evaluation context if it is the root.
Pretty simple fix (a bit of a trickier investigation), but also added a test to make sure we don't hit this again. Honestly, a bit surprised this never showed up before :scream:

bake: fix global target access when using a matrix

---

commands/bake.go
tests/bake.go

bake: improve error message for empty definition

---

driver/docker-container/driver.go

The `docker-container` driver relies on the default config file location
for buildkit when writing the configuration file. When run in a rootless
version of docker (dind), the default location is different.
Instead of trying to figure out where the appropriate default location
is, this just writes the files to the same location and sets the
`--config` parameter explicitly. This flag is placed first so a
user-specified config option in `--buildkitd-flags` will take precedence
over the implicit config parameter.
This also fixes the `--config` option with the rootless image.
Previously, the config directory was being copied in a way that rendered
`/etc` unreadable and the configuration file wasn't readable either. It
also wasn't copied to the correct place. Now, `--config` is used to
specify …

driver: docker-container driver uses --config correctly in rootless mode

---

build/build.go
build/driver.go
build/driver_test.go

This patch reworks and updates the node resolution logic for selecting a node from a builder.
The new implementation reworks the logic to make use of containerd's `platforms.MatchComparer` interface instead of manually associated strings, and additionally provides a few behavioural changes over the original implementation:
- Platforms can be matched with non-strict semantics. e.g. `i386` builds can be scheduled on an `amd64` node, `arm/v7` builds can be scheduled on an `arm/v8` node.
We also add a new collection of tests for tracking regressions and making the intended behaviour clearer.

build: rework node resolution

---

build/build.go

When targets in bake are chained with named build contexts we need to wait for the second target to complete the solve before the session from first build can be released. Otherwise, the first build could already release the definition from the buildkit graph before second build starts. Normally this would not be a problem because the steps from first build should get a direct cache match but there are some edge cases with local sources where another build can take ownership of the shared destination directory and then for specific graph layout BuildKit solver would find that it can possibly match cache if it would recompute content checksums for the local source, causing it to be repulled again via session.
Because `Evaluate()` is called manually in this patch it might cause a small …

build: wait from child targets to complete before session release

---

docs/reference/buildx_imagetools_inspect.md

related to https://github.com/docker/build-push-action/issues/972#issuecomment-1805876213
In https://github.com/docker/buildx/pull/1505 we made a change to fix a performance regression but we didn't update docs.
This change align docs for `imagetools inspect` command since `{{json .}}` format does not print provenance and sbom fields anymore.

docs: fix imagetools inspect json format

---

driver/remote/driver.go

This adds status reporting for the remote driver so it shows the length
of time it is spending waiting for the connection. If the service is
already present, this logger isn't shown but it should help provide a
message to show the user why the build is stalled.
A timeout of 20 seconds has been added to the bootstrap.
Fixes #2120.

driver: add status reporting and a timeout to the remote driver bootstrap

---

docs/reference/buildx_du.md

docs: add buildx du verbose example

---

build/utils.go
build/utils_test.go

- Fixes docker/cli#4648
- See https://github.com/docker/cli/issues/4648#issuecomment-1807992740
- related: https://github.com/docker/cli/pull/4663
**- What I did**
Make it easier to specify IPv6 addresses in the '--add-host' option by permitting 'host=ip' in addition to 'host:ip', and allowing square brackets around the address.
For example:
--add-host=hostname:127.0.0.1
--add-host=hostname:::1
--add-host=hostname=::1
--add-host=hostname:[::1]
**- How I did it**
Updated the function that converts from `--add-host` format to buildx's csv format, stripping brackets from the address.
This pull request is equivalent to one in `docker/cli`, for `docker run` and legacy builds.
**- How to verify it**
New unit tests pass. And ...
```
/work # cat Dockerfile
FROM alpine:latest
RUN ping -c1 …
```

Permit '=' separator and '[ipv6]' in --add-host

---

util/gitutil/gitutil.go
util/gitutil/gitutil_test.go
util/gitutil/testutil.go

Using this command resolves remote based on remote-tracking branch of the currently selected branch and should be more precise in case we can't predict if the user uses origin to mark upstream or their fork.
This reverses https://github.com/docker/buildx/pull/1548 . The issue there isn't unfortunately very clear about what exact case did not show correct output before. It is possible it was just a misunderstanding about how `ls-remote --get-url` works.
https://github.com/git/git/blob/v2.43.0/remote.c#L550-L554
~The "origin" fallback probably does not do anything anymore. 95% sure it is safe to remove.~
~Looking at the git source, another difference is that if there is only one remote, then `ls-remote --get-url` returns that(even if not remote-tracking) while the current implementation …

gitutil: find default remote by tracking branch

---

builder/builder.go
builder/builder_test.go
commands/create.go

This moves the builder creation logic to the builder package as we plan to allow builder creation in the build UI of Docker Desktop so we avoid drifting with the same logic in `command` package.

builder: move builder creation logic to builder package

---

build/build.go
build/driver.go
build/driver_test.go

closes https://github.com/docker/buildx/pull/2124
If user doesn't specify any platform, it should be inferred from the first node instead of using the local platform. In follow-up we should also look at the rules suggested in https://github.com/docker/buildx/issues/2119#issuecomment-1815517521 to take into account the preferred platform as well.

build: infer platform from first node if none set

---

.github/workflows/build.yml

@technicallyjosh Can you check if this account has access to https://hub.docker.com/r/docker/buildx-bin? Thanks

ci: use public bot account to push bin image

---

.github/workflows/build.yml

follow-up https://github.com/docker/buildx/pull/2157
We now have org-wide vars to get the username. Let's us it.

ci: use org-wide var as username

---

util/gitutil/gitutil.go
util/gitutil/path_unix.go
util/gitutil/path_unix_test.go
util/gitutil/path_windows.go
util/gitutil/path_windows_test.go

Fixes an issue on WSL where git root dir didn't not match WSL path but Windows one. This is related to https://github.com/docker/buildx/pull/1477 where Git is invoked on Windows in WSL through `git.exe`.

gitutil: sanitize root dir on WSL

---

build/build.go
build/git.go
build/git_test.go

Set local dirs metadata if relative to ~working~ VCS directory so dockerfile path is tracked accurately.

build: set local dirs as frontend attributes

---

driver/docker-container/factory.go
tests/create.go
tests/integration_test.go
tests/rm.go

fixes #2177 
When creating a builder and setting memory limit, it panics:
```
$ docker --debug buildx create --name foo --driver-opt "memory=3g"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x120c656]
goroutine 46 [running]:
github.com/docker/buildx/builder.(*Node).loadData(0xc000429d40, {0x266fc00, 0xc00025ebd0})
github.com/docker/buildx/builder/node.go:254 +0x56
github.com/docker/buildx/builder.(*Builder).LoadNodes.(*Builder).LoadNodes.func2.func3()
github.com/docker/buildx/builder/node.go:154 +0x625
golang.org/x/sync/errgroup.(*Group).Go.func1()
golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1 …
```

driver(container): fix conditional statement for error handling

---

go.mod
go.sum
vendor/modules.txt

no diff, as the tag is the same commit as we used already; https://github.com/docker/go-connections/compare/fa09c952e3ea...v0.5.0

vendor: github.com/docker/go-connections v0.5.0

---

commands/rm.go
docs/reference/buildx.md
docs/reference/buildx_rm.md
tests/integration_test.go
tests/rm.go

Similar to `docker rm`, it gives the possibility to remove one or more builder instances at once.

rm: support removing multiple builders at once

---

commands/bake.go
commands/build.go
go.mod
util/metrics/metrics.go
util/metrics/otlp.go

Introduce a meter provider to the buildx cli that will send metrics to
the otel-collector included in docker desktop if enabled.
This will send usage metrics to the desktop application but also send
metrics to a user-provided otlp receiver endpoint through the standard
environment variables.
This introduces a single metric which is the cli count for build and
bake along with the command name and a few additional attributes.

metrics: send metrics to the otel collector endpoint when active

---

.github/workflows/build.yml

backport of
* https://github.com/docker/buildx/pull/2157
* https://github.com/docker/buildx/pull/2162
related to https://github.com/docker/buildx/actions/runs/7497002480/job/20410354310#step:6:36
bin-image was not published for 0.12.1, we forgot to backport these changes to v0.12 branch :see_no_evil:

[v0.12 backport] ci: use public bot account to push bin image

---

.github/workflows/codeql.yml
Dockerfile
hack/dockerfiles/docs.Dockerfile
hack/dockerfiles/generated-files.Dockerfile
hack/dockerfiles/lint.Dockerfile
hack/dockerfiles/vendor.Dockerfile

- backport https://github.com/docker/buildx/pull/2190
(cherry picked from commit 61dff684adbf8d0e33008994a52ebcfa7a256ff6)

[v0.12 backport] update to go1.21.6

---

.github/workflows/build.yml
build/git.go
build/git_unix.go
build/git_windows.go
go.mod
util/gitutil/gitutil.go
util/gitutil/path.go
util/gitutil/path_unix_test.go
util/gitutil/path_windows.go
util/gitutil/path_windows_test.go

follow-up https://github.com/docker/buildx/pull/2205#issuecomment-1908035967

ci: test-unit job matrix for win/macos/ubuntu

---

.github/workflows/build.yml
.github/workflows/docs-upstream.yml
.github/workflows/e2e.yml

Related to:
Previous PRs to bump to v4 were closed (https://github.com/docker/buildx/pull/2163) because there was no support for merging multiple files from a matrix but this has been fixed since then: https://github.com/actions/upload-artifact/issues/472#issuecomment-1861571655

bump actions/upload-artifact and actions/download-artifact to 4

---

.github/workflows/docs-upstream.yml

follow-up https://github.com/docker/buildx/pull/2210#issuecomment-1911663381
related to https://github.com/docker/docs/pull/19220
need to pin docs validate upstream workflow to a commit with artifact v3 support as this is not backward compat with v4 from main.

[v0.12] ci(docs-upstream): pin reusable workflow

---

.github/workflows/build.yml

related to:
full diff: https://github.com/crazy-max/.github/compare/1a64ea6d01db9a48aa61954cb20e265782c167d9...fa6141aedf23596fb8bdcceab9cce8dadaa31bd9

bump gotest-annotations to fa6141aedf23596fb8bdcceab9cce8dadaa31bd9

---

commands/bake.go
commands/build.go
go.mod
util/confutil/exp.go
util/metricutil/metric.go
util/metricutil/otlp.go
util/metricutil/resource.go

Add the service instance id to the resource attributes to prevent
downstream OTEL processors and exporters from thinking that the CLI
invocations are a single process that keeps restarting. The unique id
can be removed through downstream aggregation to prevent cardinality
issues, but we need some way to tell OTEL that it shouldn't reset the
counters.
Move the check for the experimental flag to its own package and then use
that invocation to prevent creating exporters so metrics are disabled
completely. This makes it so we don't have to check for the experimental
flag in every place we add metrics until we decide to make metrics
stable in general.
This also moves the OTEL initialization to a `util/metricutil` package
to be more consistent with the existing util naming and to differentiate …

otel: include service instance id attribute to resource and move to metricutil package

---

util/imagetools/create.go

Fixes https://github.com/docker/buildx/issues/2229
It looks like this case could only happen with multiple sources? But regardless, we definitely shouldn't be modifying a source input, we should instead make a clone.

fix: avoid modifying source during resolver.Copy

---

commands/bake.go
tests/bake.go

fixes #2236 
This is a regression introduced in Buildx 0.12.0 (https://github.com/docker/buildx/pull/1838) that makes order when reading bake definitions inconsistent. Changes are minimal to encourage backporting to v0.12 branch but will open a follow-up to review this logic as we should also consider merge order when importing unattended files from remote or archive. This would be an enhancement so I keep this out for now.

bake: fix definitions merge order

---

.github/workflows/build.yml

related to https://github.com/docker/buildx/actions/runs/7784740901
Not sure why this one was left behind by dependabot :thinking:

ci: bump codecov/codecov-action to 4

---

go.mod
go.sum
vendor/modules.txt

- follow-up to https://github.com/docker/buildx/pull/2238
no diff; same commit, but tagged: https://github.com/containerd/console/compare/8f6c4e4faef5...v1.0.4

vendor: github.com/containerd/console v1.0.4

---

driver/remote/util/endpoint.go

Buildkit on windows exposes an npipe endpoint (`npipe:////./pipe/buildkitd`) which can be used to create a remote builder for WCOW.
Testing this with a simple docker file gives the result below:

driver: add npipe url scheme support

---

driver/docker-container/driver.go
driver/docker-container/factory.go
tests/create.go

Currently we can't set the restart policy for buildkit containers created with `docker-container` driver. In my use case I have restarted some machines but as the default restart policy is `no`, the containers were not running. Even if we ensure nodes are booted before building I think it's still useful to have this driver opt.
Current behavior (`unless-stopped`) is kept.
Needs docs update in follow-up (cc @dvdksn): https://docs.docker.com/build/drivers/docker-container/#synopsis

docker-container: restart-policy opt

---

commands/bake.go
commands/build.go

when a build is ran using `--progress=rawjson` output should only contain line-delimited json stream
`PrintBuildDetails` to display an additional human-readable message at the end of the build breaks parsing this stream
Another option would be to use stdout for json and stderr for such messages

don't print build details when progress is rawjson

---

build/dial.go
commands/dial_stdio.go
commands/root.go
docs/reference/buildx.md
docs/reference/buildx_dial-stdio.md
driver/docker-container/driver.go
driver/docker/driver.go
driver/driver.go
driver/kubernetes/driver.go
driver/remote/driver.go
tests/dialstdio.go
tests/integration_test.go

This allows the buildx CLI to act a proxy to the configured instance. It allows external code to use buildx itself as a driver for connecting to buildkitd instances.
Instance and node selection should follow the same semantics as as `buildx build`, including taking into account the `BUILDX_BUILDER` env var and the `--builder` global flag.

Add dial-stdio command

---

build/build.go
build/git.go
build/git_unix.go
build/utils.go
commands/build.go
util/confutil/node.go
util/gitutil/gitutil.go
util/gitutil/path.go
util/gitutil/path_unix_test.go
util/gitutil/path_windows.go
util/gitutil/path_windows_test.go
util/metricutil/metric.go
util/metricutil/resource_test.go
util/osutil/path.go
util/osutil/path_unix.go
util/osutil/path_windows.go

This adds a build duration metric for the build command with attributes 
related to the buildx driver, the error type (if any), and which options 
were used to perform the build from a subset of the options.

metrics: add build command duration metric

---

util/metricutil/metric.go

The `BUILDX_EXPERIMENTAL` check is removed from the docker otel
collector. We'll send metrics to the OTLP endpoint for docker desktop if
it is present and enabled regardless of experimental status.
The user-facing `OTEL` endpoints for enabling the metric reporting for
external use is still hidden behind the experimental flag. We'll likely
remove the experimental flag for this feature for v0.14.

metricutil: remove BUILDX_EXPERIMENTAL from internal docker reporting

---

build/build.go
builder/builder.go
builder/node.go
commands/create.go
commands/inspect.go
commands/rm.go
docs/reference/buildx_build.md
docs/reference/buildx_create.md
docs/reference/buildx_rm.md
driver/docker-container/driver.go
driver/docker-container/factory.go
driver/kubernetes/factory.go
driver/manager.go
driver/remote/factory.go
hack/test-driver
store/nodegroup.go
store/nodegroup_test.go
tests/build.go
tests/workers/docker-container.go

I found it confusing to have `config` as driver opt instead of `buildkitd-config` so we are consistent with `buildkitd-flags`. Same for variables not aligned across our code base.
This is also relevant for #2270

driver: make buildkitd "config" and "flags" names consistent

---

docs/reference/buildx_create.md
go.mod
go.sum
tests/build.go
tests/inspect.go
tests/integration.go
vendor/github.com/moby/buildkit/util/appdefaults/appdefaults.go
vendor/modules.txt

fixes https://github.com/docker/buildx/issues/2256
follow-up https://github.com/docker/buildx/pull/2270#discussion_r1498446323 and closes #2270
needs #2268
This is an alternative to #2270 to document how to set BuildKit daemon network mode using `--buildkitd-flags` instead of introducing a new flag.

driver: docs to set buildkitd network mode and add tests

---

builder/builder.go
builder/builder_test.go
driver/docker-container/factory.go
tests/inspect.go

driver: set network.host entitlement by default for container drivers

---

build/build.go
docs/reference/buildx_build.md
tests/bake.go
tests/build.go

Sets `buildx.build.ref` in the metadata file.
```
$ docker buildx build . --metadata-file md.json
...
$ cat md.json
{
"buildx.build.ref": "default/default/0fjb6ubs52xx3vygf6fgdl611",
"containerimage.config.digest": "sha256:9651cc2b3c508f697c9c43b67b64c8359c2865c019e680aac1c11f4b875b67e0",
"containerimage.digest": "sha256:9651cc2b3c508f697c9c43b67b64c8359c2865c019e680aac1c11f4b875b67e0"
}
```
```
$ docker buildx bake validate --metadata-file md.json
...
$ cat md.json
{
"lint": {
"buildx.build.ref": "default/default/kamngmcgyzebqxwu98b4lfv3n"
},
"validate-docs": {
"buildx.build.ref": "default/default/w1spi3ss9vnatnkznc4fw0btd"
},
"validate-vendor": {
"buildx.build.ref": "default/default/lc2ohlly0xkvop06y81fzyiag"
}
}
```

build: set build ref in response

---

go.mod
go.sum
vendor/github.com/google/uuid/CHANGELOG.md
vendor/github.com/google/uuid/hash.go
vendor/github.com/google/uuid/version7.go
vendor/modules.txt

full diff: https://github.com/google/uuid/compare/v1.5.0...v1.6.0

vendor: update github.com/google/uuid to v1.6.0

---

commands/prune.go
commands/rm.go
commands/util.go

fix #2240
With recent changes, the global cobra context is passed to all commands what usually is correct, but in this case the prompt library does not provide support for cancellation.
Note that although the new function supports cancellation, it does not leave the reader in a clean state. Internally the prompt function uses bufio reader so it is unknown how many bytes it has read and how much data it has dropped once the prompt function returns.

commands: handle ctrl-c on active prompt

---

driver/remote/driver.go
driver/remote/util/dialer_unix.go
driver/remote/util/dialer_windows.go
go.mod

This PR fixes an issue where the [Dialer ](https://pkg.go.dev/net?GOOS=windows#Dialer.DialContextl) in go does not support named pipes which the buildkit daemon on Windows uses. I've added a utility DialContext function that uses  [DialPipeContext](https://github.com/microsoft/go-winio/blob/008bc6ea439f15884bef0b52f2772190c382bf46/pipe.go#L255C6-L255C21) for npipe connections on windows.

remote: use winio DialPipeContext for named pipes

---

build/build.go
controller/pb/export.go
docs/reference/buildx_build.md

build: allow multiple exports if supported by buildkit

---

util/imagetools/loader.go

When running `docker buildx imagetools inspect --format '{{ JSON .SBOM }}` and the attestations use the `application/vnd.in-toto+json` mime type, the In-TOTO predicate is returned. However, then the attestation are wrapped in a DSSE envelope using the `application/vnd.in-toto.spdx+dsse` mime type, the same command returns and empty object (`{}`).
The changes add support for the DSSE mime type and base64 decode the envelope and returnb the payload object to stay consistent with images that do not use a wraper.

Add support for DSSE envelope for attestation in imagetools

---

.github/workflows/docs-release.yml

Follow-up to #2295
We have no underscore in the data dirname anymore. 
https://github.com/docker/docs/tree/main/data

ci(fix): remove underscore in docs data dir

---

commands/bake.go
controller/build/build.go
tests/bake.go
tests/build.go

fixes https://github.com/docker/build-push-action/issues/727
We forgot to handle `push` and `load` shorthands in https://github.com/docker/buildx/pull/2290.
~Keeping this one in draft while I'm working on integration tests.~
~EDIT: Argh GitHub is broken https://www.githubstatus.com/incidents/wcl1sw4mzg60~

build: handle push/load shorthands for multi exporters

---

.github/workflows/docs-release.yml

related to https://github.com/docker/buildx/actions/runs/8162802915/job/22314599528#step:7:120
Also adds a `workflow_dispatch` event to be able to manually trigger this workflow.

ci(docs-release): fix vendoring step

---

.github/workflows/docs-release.yml

Continuation of docker/docs#19569

ci: use make target for vendoring docs release

---

docs/reference/buildx_build.md

[v0.13 backport] docs: fix link to new target in dockerfile reference

---

Dockerfile

picked from #2307 
we can now use `moby/moby-bin` and `dockereng/cli-bin` images for testing docker in our integration tests.

dockerfile: use moby-bin and cli-bin images for docker binaries

---

builder/node.go
driver/driver.go
driver/kubernetes/factory.go
driver/kubernetes/factory_test.go
driver/remote/driver.go
tests/create.go

fix #2324
closes #2329
With the new dial-stdio command the dialer is split from `Client` function in order to access it directly.
This breaks the custom connhelpers functionality
as support for connhelpers is a feature of the default dialer. If client defines a custom dialer then only it is used without extra modifications. This means that remote driver dialer needs to detect the
connhelpers on its own.
The relevant default dialer addition is in https://github.com/moby/buildkit/blob/a38011b9f57db4b805e6bb0322d7d923b341bc6e/client/client.go#L109-L115 .
@cpuguy83 @jsternberg 
@crazy-max For test, should we have one custom test just for connhelpers or maybe just add extra config in the matrix that runs remote driver with a `docker-container://` endpoint address?

remote: fix connhelpers with custom dialer

---

bake/bake_test.go
builder/node.go
commands/bake.go
driver/driver.go
driver/kubernetes/factory.go
driver/kubernetes/factory_test.go
driver/remote/driver.go
tests/bake.go
tests/create.go

[v0.13] cherry-picks for v0.13.1

---

.github/workflows/docs-release.yml
.github/workflows/docs-upstream.yml
.github/workflows/validate.yml

* backport of https://github.com/docker/buildx/pull/2339
also backport docs changes related to https://github.com/docker/buildx/actions/runs/8254729582 (cc @dvdksn):
* https://github.com/docker/buildx/pull/2312
* https://github.com/docker/buildx/pull/2314

[v0.13 backport] ci: enable multi-platform lint only for upstream repo

---

util/progress/metricwriter.go

This measures the transfer size and duration for image pulls along with the
time spent extracting the image contents.

metrics: measure image transfers for image source operations

---

build/build.go
build/git.go
build/git_test.go
build/opt.go
go.mod

* follow-up https://github.com/moby/buildkit/pull/4583

chore: switch to LocalMounts implementation

---

util/progress/metricwriter.go

This measures the duration of exec operations. It does not factor in
whether the operation was cached or not so this should include the
amount of time to determine whether an operation was cached.

metrics: measure run operations for exec operations

---

commands/build.go
commands/root.go

carried from https://github.com/docker/buildx/pull/2280
looks to be an oversight when refactoring in https://github.com/docker/buildx/pull/2224

chore: check experimental from confutil

---

tests/bake.go
tests/build.go
tests/create.go
tests/imagetools.go
tests/inspect.go
tests/integration.go
tests/ls.go
tests/rm.go

carried from https://github.com/docker/buildx/pull/2322
Adds helpers to handle worker being used. This will be helpful with #2322 and #2307

tests: refactor worker handling in sandbox

---

util/progress/metricwriter.go
util/progress/metricwriter_test.go

This measures the amount of time spent idle during the build. This is
done by collecting the set of task times, determining which sections
contain gaps where no task is running, and aggregating that duration
into a metric.

metrics: measure idle time during builds

---

build/build.go
build/utils.go
driver/docker-container/driver.go
driver/docker/driver.go
driver/driver.go
driver/kubernetes/driver.go
driver/manager.go
driver/remote/driver.go

This refactors the driver handle to initialize the tracer delegate inside of the driver handle instead of the individual plugins.
This provides more uniformity to how the tracer delegate is created by allowing the driver handle to pass additional client options to the drivers when they create the client. It also avoids creating the tracer delegate client multiple times because the driver handle will only initialize the client once. This prevents some drivers, like the remote driver, from accidentally registering multiple clients as tracer delegates.
This is an alternative to https://github.com/docker/buildx/pull/2187 for fixing the multiple trace spans sent by the remote driver problem.

driver: initialize tracer delegate in driver handle instead of individual plugins

---

tests/build.go

related to https://github.com/docker/buildx/pull/2363#discussion_r1548281899, will test with #2376 when rebased

tests: build secret

---

bake/remote.go
tests/bake.go
util/gitutil/testutilserve.go

fixes #2360 
Adds support for Git auth when using remote bake definitions through `BUILDX_BAKE_GIT_AUTH_TOKEN` and `BUILDX_BAKE_GIT_AUTH_HEADER` envs var that will set `GIT_AUTH_TOKEN` and `GIT_AUTH_HEADER` secrets respectively, matching https://github.com/moby/buildkit/blob/ad5a64c68f20435c52a51db73ef9246d6a3feba6/client/llb/source.go#L270-L271
Also adds `BUILDX_BAKE_GIT_SSH` to be consistent so user can provide SSH sock paths.

bake: git auth support for remote definitions

---

.github/workflows/build.yml
hack/test
tests/build.go
tests/integration.go

related to https://github.com/docker/buildx/issues/2368

tests: test with buildx experimental

---

commands/build.go

JSON formatting was handled by the known print names, but unclear why the default case was not handled as well if user requested JSON output.
@daghack

handle json formatting for print

---

build/build.go
build/opt.go
driver/docker-container/driver.go
driver/docker-container/factory.go
driver/docker/driver.go
driver/features.go
driver/kubernetes/driver.go
driver/kubernetes/factory.go
driver/kubernetes/factory_test.go
driver/remote/driver.go
driver/remote/factory.go
tests/build.go
tests/create.go

This eases build driver migrations, as it allows aligning the default behavior.
See also https://docs.docker.com/build/drivers/

Implement ability to load images by default in non-Docker build drivers.

---

bake/bake.go
bake/bake_test.go
commands/bake.go
docs/reference/buildx_bake.md
tests/bake.go

follow-up https://github.com/docker/buildx/pull/2330
The `--load` case is not properly handled in v0.13 and previous v0.12 as it doesn't append but overrides the outputs:
```hcl
target "foo" {
output = [ "type=local,dest=out" ]
}
target "bar" {
}
```
```
$ docker buildx bake --load --print foo bar
```
```json
{
"group": {
"default": {
"targets": [
"foo",
"bar"
]
}
},
"target": {
"bar": {
"output": [
"type=docker"
]
},
"foo": {
"output": [
"type=docker"
]
}
}
}
```
With this change it will append only if there is a compatible output already (image, registry) or empty:
```json
{
"group": {
"default": {
"targets": [
"foo",
"bar"
]
}
},
"target": {
"bar": { …
```

bake: load override

---

driver/kubernetes/factory.go
driver/kubernetes/manifest/manifest.go

fixes: #2369 
Adds options to set ephemeral storage requests/limits. 
If everything is ok, I think that the documentation could be updated too

driver: add ephemeral-storage options to kuberentes-driver

---

docs/reference/buildx_build.md

Adds a cross-reference to the build secrets page
Partly addresses #2350

docs: add cross-reference about build secrets

---

go.mod

missed that in https://github.com/docker/buildx/pull/2373

go.mod: move indirect deps to the right require block

---

commands/build.go
tests/build.go

fixes #2368
When building in experimental mode we are using the controller which handles io forwarding operations, such as copying data from a reader to a writer and therefore locks stdin from being read in https://github.com/docker/buildx/blob/5c29e6e26eab79b47220af609ab36be4beb327fe/build/opt.go#L384
To fix this we can skip forwarding if invoke is not used as it seems to be handled only for this case. We also have a clear condition making it not possible to use a Dockerfile or context from stdin if invoke is used: https://github.com/docker/buildx/blob/0a3e5e5257dbecc6da1b501c93fee248fa17d0dd/commands/build.go#L397-L400
This should mitigate this issue but might need a deeper look as follow-up

build: fix stdin handling when building with controller

---

bake/hcl_test.go
bake/hclparser/stdlib.go
bake/hclparser/stdlib_test.go

bake: add `indexof` hcl func

---

build/build.go

Fallback to known supporting image if lint called
on old frontend.

build: add fallback image for --print=lint

---

.github/workflows/e2e.yml

same as https://github.com/docker/setup-buildx-action/pull/219/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR514

ci: switch to reusable workflow to install k3s

---

build/build.go
build/opt.go

related to
* https://github.com/docker/buildx/pull/1100
similar to
* https://github.com/docker/buildx/pull/1954
* https://github.com/docker/buildx/pull/1961

build: mark information requests as internal

---

build/build.go
go.mod
go.sum
vendor/github.com/moby/buildkit/client/llb/fileop.go
vendor/github.com/moby/buildkit/frontend/dockerfile/parser/line_parsers.go
vendor/github.com/moby/buildkit/frontend/subrequests/lint/lint.go
vendor/github.com/moby/buildkit/session/sshforward/sshprovider/agentprovider_unix.go
vendor/github.com/moby/buildkit/session/upload/upload.go
vendor/github.com/moby/buildkit/util/contentutil/buffer.go
vendor/github.com/moby/buildkit/util/gitutil/git_ref.go
vendor/github.com/moby/buildkit/util/imageutil/config.go
vendor/github.com/moby/buildkit/util/imageutil/schema1.go
vendor/github.com/moby/buildkit/util/progress/progressui/display.go
vendor/github.com/moby/buildkit/util/testutil/workers/containerd.go
vendor/github.com/moby/buildkit/util/testutil/workers/oci.go
vendor/github.com/moby/buildkit/util/testutil/workers/util.go
vendor/github.com/moby/buildkit/util/testutil/workers/util_windows.go
vendor/github.com/moby/buildkit/util/tracing/otlptracegrpc/connection.go
vendor/modules.txt

vendor: update buildkit to 71f99c52a669

---

build/build.go
util/progress/writer.go

When the immutable policy is applied to tags and the manifest push fails, the exit code is calculated as 0. This issue occurs when using the remote driver.
We are building images in GitLab CI. Even though the image was not pushed properly, the exitCode is calculated as 0, so the job is not stopping properly.
fix exit code when manifest merge failed as follow:
before:
```
bash-5.2# docker buildx build --push --platform linux/amd64,linux/arm64 -f Dockerfile -t myregistry.com/hello/world:test .
...
=> => pushing layers                                                                                                                                                         0.8s
=> => pushing manifest for myregistry.com/hello/world …
```

fix exit code when manifest merge failed

---

build/opt.go

Avoid creating image by default if `--print` on moby builders.

build: avoid default load with --print

---

.github/workflows/validate.yml
.golangci.yml
Makefile
build/build.go
build/invoke.go
build/result.go
builder/node.go
commands/build.go
commands/install.go
commands/uninstall.go
commands/version.go
controller/build/build.go
controller/remote/client.go
controller/remote/io.go
docker-bake.hcl
driver/docker-container/driver.go
hack/dockerfiles/lint.Dockerfile
tests/workers/docker.go
tests/workers/remote.go
util/gitutil/path_windows.go
util/ioset/mux_test.go

Brings similar updates as moby/buildkit#4828 moby/buildkit#4829 to buildx

linter updates and gopls linting

---

Makefile

make: tidy redirects to bake

---

commands/build.go

related to https://github.com/docker/buildx/pull/2416, we should not generate metadata file when print flag is used

build: don't generate metadata file when print flag is used

---

.github/workflows/validate.yml

follow-up https://github.com/moby/buildkit/pull/4829#issuecomment-2045373882
This generates a matrix for each platform for `lint` and `lint-gopls` targets. I think I will port the logic in "Matrix" step to a subaction similar to https://github.com/docker/bake-action?tab=readme-ov-file#list-targets.
Reduces build time for the whole pipeline from ~30m:
To ~6m30:

ci(validate): split lint

---

docker-bake.hcl

related to
* https://github.com/docker/buildx/pull/2439
* https://github.com/docker/buildx/pull/2166
* https://github.com/docker/buildx/pull/2339
`GOLANGCI_LINT_MULTIPLATFORM != null` will always be true in our bake definition as we set it to "1" or an empty string in https://github.com/docker/buildx/blob/1d88c4b169a298c3d0f9eb41393582f25dace456/.github/workflows/validate.yml#L37

ci(validate): fix GOLANGCI_LINT_MULTIPLATFORM type for multiplatform lint

---

build/build.go

Contexts using target: schema are replaced by input: pointing to previous build result before build request is sent. Currently this replacement did not work if multiple contexts pointed to the same target name.
This happened because there is a map pointing back from result to the calling context. Previously one of the contexts (with random order) would be correctly replaced and another would be sent to buildkit as `target:` (where it would error is something wants to use it because it can't be resolved).
Example case:
```
target "base" {
target = "base"
}
target "base2" {
target = "base2"
}
contexts = {
one = "target:base"
two = "target:base"
three = "target:base2"
}
}
```

build: fix multiple named contexts pointing to same bake target

---

bake/compose.go
bake/compose_test.go

Adds support for compose ssh config with bake. See [spec](https://github.com/compose-spec/compose-spec/blob/master/build.md#ssh). Based on #1069. This does not remove support for the `x-bake` `ssh` field.

Bake: support compose ssh config

---

cmd/buildx/main.go
commands/build.go
go.mod
go.sum
util/metricutil/metric.go
vendor/github.com/docker/cli/cli-plugins/hooks/template.go
vendor/github.com/docker/cli/cli-plugins/manager/hooks.go
vendor/github.com/docker/cli/cli-plugins/manager/manager.go
vendor/github.com/docker/cli/cli-plugins/manager/plugin.go
vendor/github.com/docker/cli/cli-plugins/plugin/plugin.go
vendor/github.com/docker/cli/cli/command/cli.go
vendor/github.com/docker/cli/cli/command/telemetry.go
vendor/github.com/docker/cli/cli/command/telemetry_docker.go
vendor/github.com/docker/cli/cli/command/telemetry_utils.go
vendor/modules.txt

This version of docker/cli has changes to remove compose-cli wrapper and move all CLI metrics to OTEL.

vendor: update buildx to latest docker/cli

---

build/build.go
build/opt.go
cmd/buildx/main.go
commands/build.go
go.mod
go.sum
util/metricutil/metric.go
util/progress/writer.go
vendor/github.com/docker/cli/cli-plugins/hooks/template.go
vendor/github.com/docker/cli/cli-plugins/manager/hooks.go
vendor/github.com/docker/cli/cli-plugins/manager/manager.go
vendor/github.com/docker/cli/cli-plugins/manager/plugin.go
vendor/github.com/docker/cli/cli-plugins/plugin/plugin.go
vendor/github.com/docker/cli/cli/command/cli.go
vendor/github.com/docker/cli/cli/command/telemetry.go
vendor/github.com/docker/cli/cli/command/telemetry_docker.go
vendor/github.com/docker/cli/cli/command/telemetry_utils.go
vendor/modules.txt

- https://github.com/docker/buildx/pull/2421
- https://github.com/docker/buildx/pull/2422
- https://github.com/docker/buildx/pull/2424
- https://github.com/docker/buildx/pull/2444
- https://github.com/docker/buildx/pull/2460

[v0.14] cherry-picks for v0.14.1

---

build/driver.go
driver/driver.go

fixes #2464
In addition to panic fix in the second commit, this fixes the inefficiency where `driver.Boot` could be called multiple times, resulting multiple docker API calls for example in the case of container driver.
I put the fixes to multiple commits in case we want to only cherry pick the second one but the first one is also pretty bad imho.
This could use further refactoring. Passing the `nil` logger should not be necessary if all the resolvedNode instances are guaranteed to already be booted and caps loaded.

build: fix resolvedNode cache and panic protection

---

build/build.go
build/driver.go
build/opt.go
cmd/buildx/main.go
commands/build.go
driver/driver.go
go.mod
go.sum
util/metricutil/metric.go
util/progress/writer.go
vendor/github.com/docker/cli/cli-plugins/hooks/template.go
vendor/github.com/docker/cli/cli-plugins/manager/hooks.go
vendor/github.com/docker/cli/cli-plugins/manager/manager.go
vendor/github.com/docker/cli/cli-plugins/manager/plugin.go
vendor/github.com/docker/cli/cli-plugins/plugin/plugin.go
vendor/github.com/docker/cli/cli/command/cli.go
vendor/github.com/docker/cli/cli/command/telemetry.go
vendor/github.com/docker/cli/cli/command/telemetry_docker.go
vendor/github.com/docker/cli/cli/command/telemetry_utils.go
vendor/modules.txt

From #2461 that were against wrong target branch
- https://github.com/docker/buildx/pull/2421
- https://github.com/docker/buildx/pull/2422
- https://github.com/docker/buildx/pull/2424
- https://github.com/docker/buildx/pull/2444
- https://github.com/docker/buildx/pull/2460
New
- https://github.com/docker/buildx/pull/2467

[v0.14] cherry picks for v0.14.1

---

driver/kubernetes/manifest/manifest.go

When a self-signed certificate is specified in `buildkitd.toml`, the current implementation registers the certificate as a `ConfigMap`, but the `volumes` and `volumeMounts` in `Deployment` are incorrect, so the `Deploymetnt` cannot start.
This fixes #1800.

Fix k8s driver with certs cannot boot

---

build/opt.go

hasTag was always true as it was set to "true" when missing, in which case
the default (`:latest`) tag was applied; https://github.com/docker/buildx/blob/37c4ff09448f30204b141a757d46ccc11982762e/build/opt.go#L500-L504
hasDigest would always be true when reaching this code, because the function
would return with an error when failing to resolve the digest; https://github.com/docker/buildx/blob/37c4ff09448f30204b141a757d46ccc11982762e/build/opt.go#L528-L530

build: loadInputs: remove redundant checks for hasTag, hasDigest

---

commands/prune.go

This allows negative prune filters, eg. `docker buildx prune --filter 'type!=exec.cachemount'`
The patch slightly abuses how the `docker/api/types/filters` package can't understand these separators but alternative would have been to create another package that is a mix of Docker and Containerd filter style.

prune: allow negative and prefix filters

---

build/opt.go

- follow-up to / stacked on https://github.com/docker/buildx/pull/2477
This makes the code slightly more idiomatic, but the errors produced will
change slightly to prevent having to path NamedContext as argument.

build: loadInputs: extract resolving digest to a separate function

---

util/progress/metricwriter.go

This metric records the number of times it sees a lint warning in the
progress stream and categorizes the number of times each rule has been
triggered. This will only record whether a lint warning was triggered
and not whether the linter was even used or which rules were present.
That information isn't presently part of the stream.
With this change, we might be reaching some of the limitations that
spying on the progress stream gives us for metrics and may want to
consider another way for the build to communicate metrics back to the
client.

metrics: record the number of times lint rules are triggered during a build

---

build/build.go
commands/imagetools/create.go
docs/reference/buildx_imagetools_create.md
tests/imagetools.go
util/imagetools/create.go

- Fixes issue #2481 
- I updated the tests that were affected by this change to test the new logic, however there were some tests in the repo that seem to have already been failing before I made any changes, so the few tests that are failing shouldn't have anything to do with my changes
- As a response to comments below, the default behavior isn't being changed -- the new logic is now behind the flag `--prefer-index=false`
- As a response to the comments below, I removed the mediaType check that I originally just added to because I can't really see a reason for it at this point
- Updated docs

Add `--prefer-index` flag for`imagetools create` on a single source

---

build/build.go

Updates the fallback image to the new one that contains more lint rule validations.

build: update --print fallback image to 1.8.0-rc1

---

commands/dial_stdio.go

might have been an oversight in https://github.com/docker/buildx/pull/2112
cc @cpuguy83

dial-stdio: remove extra cmd.flags()

---

driver/kubernetes/context/fixtures/k3s-kubeconfig
driver/kubernetes/context/load.go
driver/kubernetes/context/load_test.go

fixes #2436 
Addresses a concurrency issue in the `ConfigFromEndpoint` function where multiple kubeconfig files were accessed simultaneously when loading nodes. This change ensures that kubeconfig files are accessed in a thread-safe manner by making config from the endpoint taking precedence, preventing potential race conditions.
cc @gitfxx

k8s: fix concurrent kubeconfig access when loading nodes

---

commands/build.go
tests/build.go

Update the lint subrequest call to error when a build error was encountered during linting.
When using the `--call=check` flag, `buildx` currently returns `0`, even when there was a build error. This correctly updates that behavior and causes the build error to print its source, bringing the behavior in-line with `--call=build`.
Example 
```
$ BUILDX_EXPERIMENTAL=1 docker buildx --builder=dev build -t trash --call=check . && echo "apple"
[+] Building 0.2s (2/2) FINISHED                                                                                                         docker-container:dev
=> [internal] connecting to local controller                                                                                                            0.0s
=> [internal] load build definition from …
```

update the lint subrequest call to error

---

docs/reference/buildx_build.md

Adds cross-references to exporter descriptions from the `buildx b -o` reference documentation, for detailed information about each exporter

docs: link to exporter descriptions from reference docs

---

.github/workflows/e2e.yml
commands/bake.go
commands/build.go
docs/reference/buildx_bake.md
docs/reference/buildx_build.md
go.mod
go.sum
hack/test-driver
tests/bake.go
tests/build.go
util/confutil/metadata.go
util/progress/printer.go
vendor/github.com/mitchellh/hashstructure/v2/LICENSE
vendor/github.com/mitchellh/hashstructure/v2/README.md
vendor/github.com/mitchellh/hashstructure/v2/errors.go
vendor/github.com/mitchellh/hashstructure/v2/hashstructure.go
vendor/github.com/mitchellh/hashstructure/v2/include.go
vendor/modules.txt

alternative to https://github.com/docker/buildx/pull/2511 and similar to https://github.com/docker/buildx/pull/2280, we can set build checks warnings in the metadata file. Does not set them by default but can be enabled by using the `BUILDX_METADATA_WARNINGS=1` environment variable.
This will be useful with our GitHub Actions so we can generate GitHub Annotations without having to do a subrequest build like in https://github.com/crazy-max/docker-build-push-action/pull/39/files#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR132
@tonistiigi Also added extra commit to dedup warnings for bake related to https://github.com/docker/buildx/pull/2534#issue-2358036103
```dockerfile
frOM busybox as base
cOpy Dockerfile .
from scratch
COPy --from=base \
/Dockerfile \
/
```
``` …
```

build: opt to set progress warnings in response

---

go.mod
util/buildflags/export.go
util/buildflags/export_test.go

The Docker docs in multiple places describe passing an annotation at the command line like "index,manifest:com.example.name=my-cool-image", and say that this will result in the annotation being applied to both the index and the manifest. It doesn't seem like this was actually implemented, and instead it just results in an annotation key with "index,manifest:" at the beginning being applied to the manifest.
This change splits the part of the key before the colon by comma, and creates an annotation for each type/platform given, so the implementation should now match the docs.

Make multi-type annotation settings match docs

---

build/opt.go

fixes #2552
regression from #2254 (v0.14)
When LocalDirs were changed to LocalMounts, this broke the sharedKey computation that was based on the context directory path. SharedKey defines if directory is valid candidate for incremental context transfer and if not set properly then different directories do metadata-based transfers to same destination.

build: fix sharedkey computation for local context

---

commands/build.go

Currently, in the case that `--check` produces no errors or warnings, there is no output to clarify this. This adds a simple user facing message in the case to indicate such when it occurs.
```
~/example$ BUILDX_EXPERIMENTAL=1 docker --debug buildx --builder=dev build --check .
[+] Building 0.1s (3/3) FINISHED                                                                                                         docker-container:dev
=> [internal] connecting to local controller                                                                                                            0.0s
=> [internal] load build definition from Dockerfile                                                                                                     0.0s
=> => transferring dockerfile: 105B …
```

Add message when --check does not produce warnings or errors

---

build/build.go
commands/imagetools/create.go
controller/build/build.go
util/imagetools/create.go

I've tried to put together the smallest possible change that I think should solve #2540, but I'm not sure where or if to add a good test. 
Fixes #2540

Pass in index annotations from builds on multiple nodes

---

build/localstate.go
localstate/localstate.go
tests/build.go
tests/integration.go

relates to https://github.com/docker/buildx/pull/1735
needs or closes #2561 
When using a remote context or stdin the `LocalPath` and `DockerfilePath` are not correct:
```
$ docker buildx buildx https://github.com/docker/buildx.git
...
#14 exporting to image
#14 exporting layers done
#14 writing image sha256:d9015ff8b549fee9b8b8100cd168efea32015136c1a0a463dd5f696e130e72fa done
#14 DONE 0.0s
View build details: docker-desktop://dashboard/build/default/default/aav2ix4nw5eky66fw045dkylr
$ jq . ~/.docker/buildx/refs/default/default/aav2ix4nw5eky66fw045dkylr
{
"Target": "default",
"LocalPath": "/home/crazy/foo/bar/https:/github.com/docker/buildx.git",
"DockerfilePath": ""
}
```
```
$ docker buildx build -f hello.Dockerfile https://github.com/docker/actions-toolkit.git#:__tests__/fixtures
... …
```

build: fix localstate for remote context and stdin

---

commands/bake.go

Add progress warnings to the output for `bake` commands same way as they show up in `build`.
```
1 warning found (use --debug to expand):
- UndefinedVar: Usage of undefined variable '$PAHT' (did you mean $PATH?) (line 2)
```
```
1 warning found:
- UndefinedVar: Usage of undefined variable '$PAHT' (did you mean $PATH?) (line 2)
Variables should be defined before their use
More info: https://docs.docker.com/go/dockerfile/rule/undefined-var/
Dockerfile:2
1 |     FROM alpine
2 | >>> ENV PATH=$PAHT:/foo
3 |     RUN env && stop
4 |
```
--
There is a bit of an issue with this atm that when two targets invoked by `bake` use the same Dockerfile they are likely to generate the same warnings. Some deduplication would be needed.

bake: print warnings on progress

---

commands/build.go
docs/reference/buildx_build.md
docs/reference/buildx_debug_build.md

Move descriptions of flags common with the legacy build client to the buildx
build reference doc.

docs: make buildx build the canonical doc

---

driver/remote/driver.go

Because remote driver implements Info() by calling Client() internally, two instances on Client are created backed by separate TCP connection. This hack avoids it and improves performance.

remote: ensure that client connection is not established twice

---

build/build.go
build/opt.go

Currently when building with `bake` we are setting the build ref for each target which results with the same ref being set in solve request when building on multiple nodes: https://github.com/docker/buildx/blob/5656c9813373bda688737449735d080905871aeb/commands/bake.go#L232-L238
But for `build` we don't do this in commands package and therefore it will generate a different one for each node: 
* https://github.com/docker/buildx/blob/5656c9813373bda688737449735d080905871aeb/build/build.go#L229
* https://github.com/docker/buildx/blob/5656c9813373bda688737449735d080905871aeb/build/opt.go#L108
@tonistiigi I think we should align `build` with `bake` to have the same ref across nodes but let me know if this should be the other way around.
cc @fiam

build: set same ref when building on multiple nodes

---

bake/bake.go
bake/bake_test.go
bake/hcl_test.go
bake/hclparser/hclparser.go
bake/hclparser/merged.go
commands/bake.go
commands/build.go
docs/reference/buildx_bake.md
tests/bake.go
util/progress/printer.go

```
target "validate" {
call = "check"
}
```
```
docker buildx bake validate
```
```
docker buildx bake --call=outline
docker buildx bake --check
docker buildx bake --call check,format=json
```
The text output of `call=outline` should be updated in follow-up to include bake definition and variables. Getting variables seems tricky and I think needs HCL parser updates.
```
» docker buildx bake binaries test --call=outline 
[+] Building 1.0s (11/11) FINISHED                                                                                                                                           0.0s
binaries
TARGET: binaries
BUILD ARG                  VALUE   DESCRIPTION
GO_VERSION                 1.21
XX_VERSION                 1.4.0
GO_EXTRA_FLAGS
BUILDKIT_SBOM_SCAN_STAGE   true
test …
```

bake: add call methods support and printing

---

bake/bake.go
bake/bake_test.go

Clearing the exporter may result in default export behavior from the driver.
fixes #2580

bake: use cacheonly exporter for implicit targets

---

tests/bake.go

Because the test checked for combinedoutput, it
could contain internal warning messages in stderr. JSON output is guaranteed in stdout.
Fixes #2575
This was the debug output:
```
=== FAIL: tests TestIntegration/TestBakeCallCheckFlag/worker=docker-container (3.96s)
bake.go:1086: 
Error Trace:	/src/tests/bake.go:1086
/src/vendor/github.com/moby/buildkit/util/testutil/integration/run.go:96
/src/vendor/github.com/moby/buildkit/util/testutil/integration/run.go:211
Error:      	Received unexpected error:
invalid character '/' after top-level value
Test:       	TestIntegration/TestBakeCallCheckFlag/worker=docker-container
Messages:   	2024/07/09 00:57:04 http2: server connection error from localhost: connection error: PROTOCOL_ERROR
{
"group": {
"default": {
"targets": [
"build",
"another"
]
} …
```

bake: fix testing json formatted output

---

builder/node.go
driver/manager.go

driver: allow arbitrary client opts

---

commands/bake.go
tests/bake.go
tests/integration.go

fixes https://github.com/docker/buildx/issues/2598
A simple fix for a patch release but we should do a proper one as follow-up to avoid this situation with `printer` in the first place.

bake: check printer before printing warnings

---

commands/build.go

This updates the warning message to clarify where to pass in the `--debug` flag when viewing warnings.

update warning message

---

.github/dependabot.yml

follow-up https://github.com/moby/buildkit/pull/5153#discussion_r1683157902
swap issues/prs with `dependencies` label to `area/dependencies` and remove `dependencies` label when merged.

chore: update dependabot labels

---

controller/build/build.go

`RunBuild` accepts a `command.Cli` interface, but the configuration it ultimately uses for builds is always sourced from `LoadDefaultConfigFile`. This makes it impossible for custom `Cli` implementations to directly provide their own non-default `ConfigFile`.
This PR changes the logic to use the output of `cli.ConfigFile()` instead of `LoadDefaultConfigFile`. The common-case `DockerCli` implementation will continue to use the result of `LoadDefaultConfigFile` ([ref](https://github.com/docker/cli/blob/dc23e775077b00cae2b6c239144053c8e2b5202e/cli/command/cli.go#L152-L159), [ref](https://github.com/docker/cli/blob/dc23e775077b00cae2b6c239144053c8e2b5202e/cli/command/cli.go#L279)), however it will now respect the CLI's error stream instead of forcing stderr.

build: don't force default configuration

---

build/build.go
build/git.go
build/git_test.go
build/opt.go

This is a preparation to shared local sources for bake targets and makes it possible to have equality check between locals from different targets.

build: refactor setting git info to local mounts

---

bake/hclparser/hclparser.go
bake/hclparser/stdlib.go
bake/hclparser/stdlib_test.go
build/build.go
build/opt.go
controller/remote/io.go
driver/docker/driver.go
driver/driver.go
driver/kubernetes/manifest/manifest.go
driver/remote/util/dialer_unix.go
driver/remote/util/dialer_windows.go
driver/remote/util/endpoint.go
driver/remote/util/endpoint_test.go

Selection of improvements for best practices and avoiding big memory allocations in init stage in places where it doesn't degrade readability. For benchmarks this doesn't make a giant difference overall as bigger issues are in some of the dependencies, but need to start somewhere. This is mostly preparation for some other updates and for defining standards for future changes. All `regexp.Compile` issues were skipped for now but the detection logic is in https://gist.github.com/tonistiigi/1d58b4c2de41d194f35ac2c9f029f586 . Validations like this should be eventually integrated into CI.

Improvements based on inittrace

---

.github/workflows/build.yml

similar to https://github.com/moby/buildkit/pull/5184

ci: scan bin image with docker scout

---

tests/bake.go
tests/build.go

add test build and bake multiplatform (--platform), to improve test coverage based on #1857

tests: build multiplatform

---

.github/workflows/build.yml

checkout seems suggested when uploading the SARIF report: https://github.com/docker/buildx/actions/runs/10093571745/job/27910395571#step:4:25
```
Processing sarif files: ["/tmp/docker-scout-action-72Brf6/result.txt"]
Validating /tmp/docker-scout-action-72Brf6/result.txt
Combining SARIF files using the CodeQL CLI
Adding fingerprints to SARIF file. See https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#providing-data-to-track-code-scanning-alerts-across-runs for more information.
Could not determine current commit SHA using git. Continuing with data from user input or environment. The checkout path provided to the action does not appear to be a git repository.
Uploading results
Successfully uploaded …
```

ci: checkout step for scout job

---

.github/workflows/build.yml
docker-bake.hcl
hack/dockerfiles/govulncheck.Dockerfile

Runs [govulncheck](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck) tool in our workflow to report known vulnerabilities that affect Go code using the Go vulnerability database at https://vuln.go.dev/ and output a SARIF report that will be uploaded to [GitHub Code scanning](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning) so we have these issues reported in the [Security tab](https://github.com/docker/buildx/security) like we have done with Docker Scout in https://github.com/docker/buildx/pull/2624.
Atm dependabot will open a pull request when such vulnerabilities are found similar to https://github.com/docker/buildx/pull/2337 but we often close them because it needs coordination with upstream repositories first.
I …

govulncheck to report known vulnerabilities

---

docs/reference/buildx_build.md

`buildx.build.warnings` note is not in the right section :see_no_evil:

docs: fix metadata section for build command

---

Dockerfile

Also adding a DOCKER_CLI_VERSION build-arg, so that we can set versions
independently for (untagged) pre-releases.

Dockerfile: update to docker 27.1.1

---

build/build.go

fixes #1377
fixes https://github.com/docker/buildx/issues/92
~depends on #2607~
Detect cases where multiple bake targets would use the same
local source. For such cases a separate session request is
made in addition to session per target and local source
is made available in that source as well.
The new sessionID is sent with the request so the frontend
can ask associate it with the local source it needs.
The sources are still available in the main request session
as well. This would be used if frontend ignores the local-sessionid
parameter and makes sure that old version continue working.
```
> docker buildx bake lint validate-golangci
Before:
=> [validate-golangci internal] load build definition from lint.Dockerfile                                                        0.0s
=> => …
```

bake: use shared session for local sources for multiple targets

---

builder/node.go
driver/kubernetes/driver.go
driver/kubernetes/factory.go
driver/kubernetes/factory_test.go
driver/manager.go
driver/remote/factory.go

fixes https://github.com/docker/buildx/issues/2597

builder: move kube config handling to k8s driver package

---

util/progress/metricwriter.go

Compile the regular expressions only on first use rather than implicitly as part of the `init()` function of the package. This prevents taking a speed hit on the initialization of the package regardless if this type is used and moves it to the time when a regular expression is first used.
Fixes #2596.

metricwriter: compile regular expressions only on first use

---

commands/bake.go
commands/build.go
tests/bake.go
tests/build.go

Atm when using `--call` or `--check`, the metadata file is not generated:
```
$ docker buildx build --call check --file ./test/bad.Dockerfile --metadata-file md.json ./test
...
12 |     CMD [ "echo", "Hello, Sweden!" ]
13 |     ENTRYPOINT my-program start
WARNING: JSONArgsRecommended - https://docs.docker.com/go/dockerfile/rule/json-args-recommended/
JSON arguments recommended for ENTRYPOINT to prevent unintended behavior related to OS signals
bad.Dockerfile:13
11 |     CMD [ "echo", "Hello, Norway!" ]
12 |     CMD [ "echo", "Hello, Sweden!" ]
13 | >>> ENTRYPOINT my-program start
14 |
$ cat md.json
cat: md.json: No such file or directory
```
I think we should allow it for build warnings related to …

support metadata file with call flag for build and bake commands

---

commands/bake.go
commands/build.go

This adds metrics for the bake command using a different method of calculating the build identifier but with the same attributes otherwise.

metrics: add metrics for bake command

---

hack/dockerfiles/govulncheck.Dockerfile

relates to https://github.com/moby/moby/pull/48311#discussion_r1711079896

hack: ensure SARIF output has results field defined for govulncheck

---

build/build.go
tests/bake.go
tests/build.go

relates to
* https://github.com/docker/buildx/pull/2640#issuecomment-2283808570
* https://github.com/moby/buildkit/pull/5248#discussion_r1714912571

build: skip build ref and provenance metadata for subrequests

---

bake/hclparser/stdlib.go
bake/hclparser/stdlib_test.go

These functions help with dealing with path inputs and using parts of them to configure targets.
For example, this improves cases like https://github.com/moby/buildkit/pull/5248/files#diff-870f6fe23fc034f008f5203ee1e628d7bfa65a49095d5a4688db498328449ed2R238 where current best approach is to take hash and lose readability of the variable.

bake: add basename, dirname and sanitize functions

---

build/build.go

Some errors can appear without a stacktrace or progress record, eg. wrong Dockerfile name passed. In that case when building many targets with bake it might be hard to figure out which target failed as in the progressbar there will only be steps that were cancelled.

build: when building multiple targets include name in error

---

util/progress/metricwriter.go

It was possible for multiple status messages to be written at the same time which caused some of the metric writer code to have a race condition.
This code should be fast enough that it doesn't interrupt the display, but some further work might be needed here.

metrics: add mutex to the metric writer

---

README.md
docs/bake-reference.md
docs/debugging.md
docs/reference/buildx_bake.md
docs/reference/buildx_build.md
docs/reference/buildx_create.md
docs/reference/buildx_imagetools_create.md
docs/reference/buildx_inspect.md

docs.docker.com now supports the gh alerts syntax for notes, warnings, and other callouts.
Example:
```
> [!NOTE]
> This is a note
```
This means notes will render more-or-less the same on GitHub as they do on the site:
> [!NOTE]
> This is a note
- related pr: docker/docs#20608

docs: use gh alert syntax for callouts

---

build/build.go
build/opt.go
build/replicatedstream.go
build/replicatedstream_test.go
controller/build/build.go

fixes #2193
When building from same stream all nodes need to read data from the same stream. In order to achive that there is a new SyncMultiReader wrapper that sends the stream concurrently to all readers. Readers must read at similar speed or pauses will happen while they wait for each other.
Dockerfiles were already written to disk before sent. Now the file written by the first node is reused for others.

build: allow builds from stdin for multi-node builders

---

commands/root.go
docs/reference/buildx.md
docs/reference/buildx_bake.md
docs/reference/buildx_build.md
docs/reference/buildx_create.md
docs/reference/buildx_debug.md
docs/reference/buildx_debug_build.md
docs/reference/buildx_dial-stdio.md
docs/reference/buildx_du.md
docs/reference/buildx_imagetools.md
docs/reference/buildx_imagetools_create.md
docs/reference/buildx_imagetools_inspect.md
docs/reference/buildx_inspect.md
docs/reference/buildx_ls.md
docs/reference/buildx_prune.md
docs/reference/buildx_rm.md
docs/reference/buildx_stop.md
docs/reference/buildx_use.md
docs/reference/buildx_version.md

Allows using `--debug` to enable debug logging under any subcommand. Currently it needed to be set as
`docker --debug buildx` meaning only way to enable debug in standalone mode was to set env variable instead and updating existing commands to add `--debug` was cumbersome.

commands: add debug as persistent flag

---

build/git.go

Not all the error cases from getGitAttributes returned appendNoneFunc. When nil was returned it caused a panic.

build: avoid possible panic when reading git info

---

docs/reference/buildx_bake.md
docs/reference/buildx_build.md
docs/reference/buildx_create.md

- relates to https://github.com/docker/docs/pull/20592

docs: update links to moved manuals pages

---

docs/reference/buildx_bake.md
docs/reference/buildx_build.md
docs/reference/buildx_create.md

[v0.16 backport] docs: update links to moved manuals pages

---

commands/build.go
tests/bake.go
tests/build.go

Atm when building with `--check`, when there are no warnings we generate the output
`Check completed, no warnings found.`
```                                                                                                                   0.0s
=> => transferring context: 88B                                                                                                                         0.0s
Check completed, no warnings found.
```
When there are warnings, we leap right into displaying them.
```                                                                                                               0.0s
=> => transferring context: 88B 
WARNING: FromAsCasing - https://docs.docker.com/go/dockerfile/rule/from-as-casing/ ....
```
This updates the output in the later case to contain …

build: print out the number of warnings after completing a rule check

---

bake/bake.go
bake/bake_test.go
bake/entitlements.go
commands/bake.go
docs/reference/buildx_bake.md
util/progress/printer.go

Ref #179
Add support for `security.insecure` and `network.host` entitlements via bake. User needs to confirm elevated privileges through a prompt or CLI flags.

bake: enable support for entitlements

---

PROJECT.md

This PR introduces a project processing guide (`PROJECT.md`) to help streamline issue and pull request management. This is inspired by guides in projects such as [moby/buildkit](https://github.com/moby/buildkit/blob/master/PROJECT.md), [spf13/cobra](https://github.com/spf13/cobra/issues/1603), and [moby/moby](https://github.com/moby/moby/tree/master/project). Key highlights:
- Document and refine `label` usage for issues and PRs
- Milestones for backlog management
- Triage process details and example
- Release types, commitments
- Issue and PR lifecycle description
- Add stale processing action
- Update links in `PROJECT.md`

docs: add project processing guide

---

PROJECT.md

There appears to be some issues with GitHub rendering mermaid diagrams where a node references itself.
```
apple --> apple
```
Results in
```mermaid
apple --> apple
```

Update PROJECT mermaid daigrams

---

builder/builder.go
builder/builder_test.go
util/confutil/config.go
util/confutil/container.go

follow-up https://github.com/docker/buildx/issues/2683#issuecomment-2343100380
On container builder creation, it's possible to define buildkitd configuration path that will injected and used inside the container.
If insecure-entitlements opts are set in this configuration they will be skipped because we are always setting the `--allow-insecure-entitlement network.host` https://github.com/docker/buildx/pull/2266 if user does not set it explicitly and buildkitd overrides configuration values with flags: https://github.com/moby/buildkit/blob/3a7055008a5e58a2abbe0e0c21c919d9e014e062/cmd/buildkitd/main.go#L583-L584.
With this change we are now detecting if `network.host` insecure entitlement is set within the buildkitd configuration and skip setting `--allow-insecure-entitlement network.host` …

builder: do not set network.host entitlement flag if already set in buildkitd conf

---

commands/inspect.go
tests/inspect.go

follow-up https://github.com/docker/buildx/issues/2683#issuecomment-2343001508
Displays buildkit daemon configuration file content used when creating a builder in inspect output:
```toml
debug = true
trace = true
insecure-entitlements = [ "network.host", "security.insecure" ]
[log]
format = "text"
```
```
$ docker buildx create --name builder --driver-opt "image=moby/buildkit:v0.16.0"
builder
```
```
$ docker buildx inspect builder --bootstrap
Name:          builder
Last Activity: 2024-09-11 08:31:27 +0000 UTC
Nodes:
Name:                  builder0
Endpoint:              unix:///var/run/docker.sock
Driver Options:        image="moby/buildkit:v0.16.0"
Status:                running
BuildKit daemon flags: --allow-insecure-entitlement=network.host
BuildKit …
```

inspect: display buildkit daemon configuration file

---

.github/workflows/build.yml

follow-up https://github.com/moby/buildkit/pull/5326

ci: fix golvulncheck job permissions

---

.github/workflows/build.yml
bake/bake.go
builder/builder.go
builder/builder_test.go
tests/bake.go
util/confutil/config.go
util/confutil/container.go

backport of:
* https://github.com/docker/buildx/pull/2689
* https://github.com/docker/buildx/pull/2685
* https://github.com/docker/buildx/pull/2691

[v0.17] cherry-picks for v0.17.1

---

bake/bake.go

Small fix for the condition of linking to itself. `target.Name` is usually empty as used by the matrix feature. This still errored before as well because the infinite loop was detected, but this error condition was ineffective.

bake: fix validation for linking to itself

---

tests/workers/docker-container.go
tests/workers/remote.go

We are missing some envs to use the right buildx config dir when cleaning up remote and container workers.

test: fix missing envs when cleaning up some workers

---

build/build.go
build/opt.go
commands/bake.go
commands/build.go
controller/build/build.go
controller/control/controller.go
controller/local/controller.go
controller/remote/client.go
controller/remote/controller.go
controller/remote/server.go
monitor/commands/reload.go
monitor/monitor.go
tests/bake.go
tests/build.go

fixes https://github.com/docker/buildx/issues/2542
Currently, when printing warnings from the rule checks, it will only report the base Dockerfile name.
`docker build --check -f foo/bar/Dockerfile .`
```WARNING: ConsistentInstructionCasing - https://docs.docker.com/go/dockerfile/rule/consistent-instruction-casing/
Command 'copy' should match the case of the command majority (uppercase)
Dockerfile:2
1 |     FROM alpine
2 | >>> copy ./tmp /tmp
3 |
4 |
```
This updates printing for the warnings to include a more specific path if one is available.
```WARNING: ConsistentInstructionCasing - https://docs.docker.com/go/dockerfile/rule/consistent-instruction-casing/
Command 'copy' should match the case of the command majority (uppercase) …
```

build: display Dockerfile path on check warnings

---

build/build.go

- printFallbackImage -> this image was actually 1.7.0 and using wrong text tag. Updated in https://github.com/docker/buildx/pull/2406 . I don't think it makes sense to use `.0` that has a patch release with bugfixes so updated to that.
- printLintFallbackImage -> pull the reference from production dockerfile upstream instead of staging area. The image is the same but users would previously see confusing "upstream" repo in the progress.

build: use better references for --call fallback images

---

bake/bake.go

When linked target requires entitlement, same entitlement is also needed by the caller. Otherwise, the request will fail when the build is processed.
Example (before):
```
target "base" {
target = "base"
entitlements = ["network.host"]
}
contexts = {
base = "target:base"
}
}
```
```
from alpine as base
run --network=host ip a
from alpine
copy --from=base /etc/passwd /foo
```
```
» docker buildx bake
[+] Building 0.0s (1/1) FINISHED                                                                                                     docker-container:gifted_dijkstra
=> [internal] load local bake definitions                                                                                                                       0.0s
=> => reading docker-bake.hcl 138B / 138B …
```

bake: fix linking to targets with entitlements

---

commands/ls.go
commands/ls_test.go
docs/reference/buildx_ls.md

follow-up https://github.com/docker/buildx/pull/830 with the `no-trunc` opt.
When using `ls`, platforms can get wieldy easily and make output in the terminal difficult to read:
```
NAME/NODE            DRIVER/ENDPOINT                       STATUS     BUILDKIT               PLATFORMS
bk12                 docker-container
\_ bk120             \_ unix:///var/run/docker.sock       running    v0.12.5                linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
bk13                 docker-container
\_ bk130             \_ unix:///var/run/docker.sock       running    v0.13.2                linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, …
```

ls: no-trunc opt

---

build/url.go

Raise the maximum size limit for the dockerfile and correct the size check. The size check was intended to use the size attribute from the file stat, but the original gogo version confused the `Size()` method (which returned the size of the proto message) with the `Size` attribute (which was named `Size_`).
During the conversion, we noticed the mistake but kept the incorrect behavior for the sake of keeping the conversion simple.
This also raises the maximum limit because 512 kB is likely a bit too conservative. The limit has been raised to 2 MB and the limit has been included in the error message.

build: raise maximum size limit for dockerfile and fix size check

---

bake/remote.go

Similar to https://github.com/docker/buildx/pull/2716.
Use the file size rather than the proto size, raise the allowed limit to the same value for consistency, and improve the error message to include the limit in human units.

bake: raise maximum size limit and fix size check

---

commands/ls.go

relates to https://github.com/docker/buildx/actions/runs/11169979364/job/31051857680#step:6:1094
```
=== FAIL: commands TestTruncPlatforms/all_preferred (0.00s)
ls_test.go:171: 
Error Trace:	/home/runner/work/buildx/buildx/commands/ls_test.go:171
Error:      	Not equal: 
expected: "linux/arm64*, linux/arm* (+3), darwin/arm64*, windows/arm64*"
actual  : "linux/arm64*, linux/arm* (+3), windows/arm64*, darwin/arm64*"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-linux/arm64*, linux/arm* (+3), darwin/arm64*, windows/arm64*
+linux/arm64*, linux/arm* (+3), windows/arm64*, darwin/arm64*
Test:       	TestTruncPlatforms/all_preferred
--- FAIL: TestTruncPlatforms/all_preferred (0.00s)
=== FAIL: commands TestTruncPlatforms (0.00s)
```

ls: ensure deterministic output for truncated platforms

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/docs-release.yml
.github/workflows/docs-upstream.yml
.github/workflows/e2e.yml
.github/workflows/labeler.yml
.github/workflows/validate.yml

make the OpenSSF scorecard slightly happier;
https://securityscorecards.dev/viewer/?uri=github.com/docker/buildx
Warn: no topLevel permission defined: .github/workflows/build.yml:1
Warn: topLevel 'security-events' permission set to 'write': .github/workflows/codeql.yml:13
Warn: no topLevel permission defined: .github/workflows/docs-release.yml:1
Warn: no topLevel permission defined: .github/workflows/docs-upstream.yml:1
Warn: no topLevel permission defined: .github/workflows/e2e.yml:1
Warn: no topLevel permission defined: .github/workflows/labeler.yml:1
Warn: no topLevel permission defined: .github/workflows/validate.yml:1

gha: set default permissions to "contents: read"

---

docs/reference/buildx_build.md

Improve descriptions of the attributes for the `--secret` flag for `buildx build`.
- Clarify how buildx determines whether to use `type=file` or `type=env`.
- Clarify that relative filepaths for `type=file` are calculated based on CWD where the buildx command is executed.
- Add `src` and `source` as possible attributes for `type=env`, but clarify that they require `type=env` to be set explicitly if you want to source from an env var (otherwise `type=file` is assumed).
- Closes docker/buildx#2386

docs: clarify options for secret types (file, env)

---

commands/imagetools/root.go
commands/root.go
tests/common.go
tests/integration_test.go

fixes #2738 
By default if there is no `Run` / `RunE` in parent command, cobra will just print help and exit 0.
No regression point, it fails since first release https://github.com/docker/buildx/releases/tag/v0.2.0 in plugin mode (`docker buildx`) but "only" since `v0.9.0` in standalone.

cli: error out on unknown command

---

cmd/buildx/debug.go
cmd/buildx/main.go

When run in standalone mode, the environment variables `DOCKER_BUILDX_CPU_PROFILE` and `DOCKER_BUILDX_MEM_PROFILE` will cause profiles to be written by the CLI.

pprof: take cpu and memory profiles by setting environment variables

---

build/localstate.go
commands/bake.go

Relates to https://github.com/docker/docs/actions/runs/11502549192/job/32017891983#step:6:21
```
Warning: Failed to export build record: /home/runner/work/_temp/docker-actions-toolkit-16m5IG/export/rec.dockerbuild not found
```
When generating build summary in our GitHub Actions, we are using the `buildx.build.ref` from metadata to export the build record. When using `call`, this attribute is not set: https://github.com/docker/buildx/blob/746eadd16e461ac1a961bb22e7fea8f1d05da88f/build/build.go#L525-L526
Which is the right behavior as no build record is written for subrequests anyway.
But we also have a fallback in our GitHub Actions in case `buildx.build.ref` is not set that checks if a local state is available as part of this build. And in this case we have one as we are generating a …

build: don't generate local state for subrequests

---

build/build.go

Small improvement for OTEL trace to group all the grpc requests made by build function under the same parent.

build: add OTEL span around build function

---

commands/bake.go

Add the flags `--list-targets` and `--list-variables` to the cases where initializing the builder can be skipped.
This allows the listing of targets and variables when no builder is available.
Resolves: docker/buildx#2755

Skip Builder Init For Bake List Flags

---

bake/bake.go

Improves the error message when using an incorrect format for setting labels. This includes the intended format directly in the error message instead of assuming the user knows what the format is.
Fixes https://github.com/docker/buildx/issues/2315.

bake: improve error when using incorrect format for setting labels

---

commands/build.go

Supports metadata descriptors list in BuildKit https://github.com/moby/buildkit/pull/5454

Add ability to output json lists in metadata build file

---

bake/compose.go
tests/bake.go

relates to https://github.com/docker/docs/pull/21410#discussion_r1842300599

bake: check for empty build network with compose

---

docs/bake-reference.md

docs: add "call" attribute for target

---

bake/bake_test.go
bake/hclparser/hclparser.go

fixes https://github.com/docker/buildx/issues/1346
This adds basic validation for variables similar to what terraform does: https://developer.hashicorp.com/terraform/language/values/variables#custom-validation-rules
As follow-up and with work being made in #2758 we could handle additional types to variables and handle some kind of pre-validation if type is not compatible but I think HCL already handles this kind of diag for evaluation already.
___
```hcl
variable "FOO" {
validation {
condition = FOO != ""
error_message = "FOO is required."
}
}
args = {
FOO = FOO
}
}
```
```
#1 [internal] load local bake definitions
#1 reading docker-bake.hcl 148B / 148B done
#1 DONE 0.0s
docker-bake.hcl:3
1 |     variable "FOO" {
2 | …
```

bake: basic variable validation

---

.github/workflows/build.yml

relates to https://github.com/actions/runner-images/issues/10721

ci: update runner to macos-14

---

.github/workflows/build.yml
Dockerfile
tests/build.go
tests/inspect.go
tests/integration.go
tests/ls.go
tests/workers/docker.go

* ~needs https://github.com/moby/buildkit/pull/4736~

tests: handle multiple docker versions

---

bake/bake.go
bake/bake_test.go
bake/compose.go
bake/compose_test.go
bake/hcl_test.go
bake/hclparser/LICENSE
bake/hclparser/gohcl/decode.go
bake/hclparser/gohcl/decode_test.go
bake/hclparser/gohcl/doc.go
bake/hclparser/gohcl/encode.go
bake/hclparser/gohcl/encode_test.go
bake/hclparser/gohcl/schema.go
bake/hclparser/gohcl/schema_test.go
bake/hclparser/gohcl/types.go
bake/hclparser/hclparser.go
bake/hclparser/type_implied.go
bake/hclparser/type_implied_ext.go
controller/pb/export.go
go.mod
util/buildflags/cache.go
util/buildflags/cty.go
util/buildflags/export.go
util/buildflags/secrets.go
util/buildflags/ssh.go

This allows using either the csv syntax or object syntax to specify
certain attributes.
This applies to the following fields:
- output
- cache-from
- cache-to
- secret
- ssh
There are still some remaining fields to translate. Specifically
ulimits, annotations, and attest.
Related to #438.

bake: initial set of composable bake attributes

---

bake/entitlements_test.go

As the paths returned by validator have the symlinks resolved, the test needs to resolve the symlinks also in the expected values. Previously this would fail if t.TempDir() or os.GetWd() returned a path that contained a symlink.
The issue was purely in the test and not in the entitlements validation logic.

bake: fix entitlement test when running from symlink temp

---

bake/bake.go
bake/bake_test.go
bake/entitlements.go
bake/entitlements_test.go
build/build.go
commands/bake.go
controller/build/build.go
controller/pb/export.go

Previous check based on dest attributes was not correct as the attributes already get converted before validation happens.
Because the local path is not preserved for single-file outputs and gets replaced by io.Writer, a temporary array variable was needed. This value should instead be added to ExportEntry struct in BuildKit in future revision.

bake: fix entitlements path checks for local outputs

---

bake/bake.go
bake/bake_test.go
bake/entitlements.go
bake/entitlements_test.go
build/build.go
commands/bake.go
controller/build/build.go
controller/pb/export.go

[v0.19] v0.19.2 cherry-picks

---

Dockerfile
hack/dockerfiles/authors.Dockerfile
hack/dockerfiles/docs.Dockerfile
hack/dockerfiles/govulncheck.Dockerfile
hack/dockerfiles/lint.Dockerfile
hack/dockerfiles/vendor.Dockerfile

Similar to what we have on buildkit repo so we avoid side effects like https://github.com/docker/buildx/pull/2830#issuecomment-2528706259. Also bump alpine and xx version on remaining dockerfiles.

dockerfiles: pin alpine version

---

bake/bake_test.go
util/buildflags/cache.go
util/buildflags/export.go
util/buildflags/secrets.go
util/buildflags/ssh.go

regression from https://github.com/docker/buildx/pull/2846/commits/b2c0c26c26791019ffa0fc1153626d515553ca3d
fixes #2858 for v0.19
These parser functions are called for `--set` to
resolve entitlement paths that would be automatically added and will fail for empty value.
The empty values would already be ignored but in v0.19 is done after merging the `--set` values and then calling parse again.

[v0.19] bake: remove empty values set by --set

---

bake/entitlements.go
bake/entitlements_test.go
tests/bake.go

Currently, to compare the local path used by bake against the paths allowed by entitlements, symlinks were evaluated for path normalization so that the local path used by build was allowed to not exist while the path allowed by entitlement needed to exist. If the path used by the build did not exist, then the deepest existing parent path was used instead. This was concistent with entitlement rules as that parent path would be the actual path access is needed.
This raised an issue with `--set` if one provides a non-existing path as an argument, as these paths are supposed to be allowed automatically. With the above restrictions set to allowed paths, this meant the build would fail as it can't grant entitlement to the non-existing paths.
This changes the evaluation logic for allowing paths …

bake: change evaluation of entitlement paths

---

bake/entitlements.go
bake/entitlements_test.go
tests/bake.go

* backport of https://github.com/docker/buildx/pull/2860

[v0.19 backport] bake: change evaluation of entitlement paths

---

bake/bake_test.go

Cherry pick of afc9cebb4861d02086e8f4d043256cfcebf1d3a9.

bake: test empty override

---

util/dockerutil/progress.go

Because of the bugs in the logic of how layer progress is throttled the last event may never be written, leaving behind incomplete output like
```
=> importing to docker                                                                                   0.9s
=> => loading layer f0074c45c2c0 190B / 190B                                                             0.9s
=> => loading layer 0e8819756174 393.22kB / 38.08MB                                                      0.8s
=> => loading layer 63ec8d9b4ac7 144B / 144B                                                             0.0s
```
Fix by always updating the current values, even if an event is initially throttled and not shown, plus make sure it always gets updated in the map.

progress: fix missing last progress from loading layers

---

bake/bake.go
bake/bake_test.go

Updates the context from target platform validation, allowing a subset of the target platforms.
cc @tonistiigi 
Closes https://github.com/docker/buildx/issues/2486

bake: fix context from target platform matching

---

go.mod
go.sum
vendor/github.com/docker/docker/api/swagger.yaml
vendor/github.com/docker/docker/client/ping.go
vendor/github.com/docker/docker/pkg/system/lstat_unix.go
vendor/github.com/docker/docker/pkg/system/lstat_windows.go
vendor/github.com/docker/docker/pkg/system/mknod.go
vendor/github.com/docker/docker/pkg/system/mknod_freebsd.go
vendor/github.com/docker/docker/pkg/system/mknod_unix.go
vendor/github.com/docker/docker/pkg/system/stat_linux.go
vendor/github.com/docker/docker/pkg/system/stat_unix.go
vendor/github.com/docker/docker/pkg/system/stat_windows.go
vendor/modules.txt

full diff: https://github.com/docker/docker/compare/v27.4.0...v27.4.1
no changes in vendored code
full diff: https://github.com/docker/cli/compare/v27.4.0...v27.4.1

vendor: github.com/docker/docker, github.com/docker/cli v27.4.1

---

bake/bake.go
docs/bake-reference.md

fixes #2873 
This change the lookup order for a bake definition by placing override files for both HCL and JSON at the lowest.
cc @jonapich

bake: update lookup order for override

---

bake/bake.go
bake/bake_test.go

fixes https://github.com/docker/buildx/issues/2859
https://github.com/docker/buildx/commit/77b33260f82140af2d1ce4cf7cebf61d0814f797 made special `default` target not being added to targets of the default group but it should otherwise it doesn't correlate with solved targets. But it should not add a `default` group to it. Also fix sorting to make output consistent.
cc @klutchell
```hcl
dockerfile = "Dockerfile"
platforms = [
"linux/amd64"
]
}
target "multiarch" {
dockerfile = "Dockerfile"
platforms = [
"linux/amd64",
"linux/arm64",
"linux/arm/v7",
"linux/arm/v6"
]
}
```
```
$ docker buildx bake --print default multiarch
{
"group": {
"default": {
"targets": [
"multiarch"
]
}
},
"target": {
"default": {
"platforms": [ …
```

bake: fix missing default target in group's default targets

---

bake/entitlements.go
hack/test-driver

Change FS entitlements checks from warning to error by default as expressed in initial PR. Users can still opt-out with environment variable if the choose to.

bake: make FS entitlements error by default

---

builder/builder_test.go
util/confutil/config.go

fixes https://github.com/docker/buildx/issues/2853
We should validate buildkit configuration before creating the builder.

builder: validate buildkit configuration

---

bake/entitlements.go
tests/bake.go

There was a mixup between fs.read and ssh entitlements check.
Corrected behavior is that if bake definition requires default SSH forwarding then "ssh" entitlement is needed. If it requires SSH forwarding via fixed file path then "fs.read" entitlement is needed for that path.

bake: fix entitlements check for default SSH socket

---

bake/hclparser/hclparser.go
commands/bake.go
docs/reference/buildx_bake.md
tests/bake.go

follow-up https://github.com/docker/buildx/pull/2556#pullrequestreview-2151553029
* Replace `--list-targets` and `--list-variables` flags with `--list` flag and put it out of experimental.
* `--print` and `--list` are now mutually exclusive.
* Add `json` format support for `--list` flag.
```
$ docker buildx bake --list=targets
#1 [internal] load local bake definitions
#1 reading docker-bake.hcl 4.97kB / 4.97kB done
#1 DONE 0.0s
TARGET                          DESCRIPTION
binaries
binaries-cross
default                         binaries
govulncheck
image
image-cross
image-local
integration-test
integration-test-base
lint
lint-gopls
meta-helper
mod-outdated
release
test
update-authors
update-docs
update-generated-files
update-vendor
validate                        lint, lint-gopls, …
```

bake: replace --list-targets and --list-variables flags with --list flag

---

docs/reference/buildx_bake.md

docs: add description for bake --list

---

.github/workflows/e2e.yml

Build some projects using bake with advanced features to catch regressions before release.

ci: e2e bake

---

go.mod
go.sum
vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md
vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go
vendor/github.com/hashicorp/hcl/v2/hclsyntax/parser.go
vendor/github.com/hashicorp/hcl/v2/hclsyntax/parser_traversal.go
vendor/github.com/hashicorp/hcl/v2/hclsyntax/public.go
vendor/github.com/hashicorp/hcl/v2/ops.go
vendor/github.com/hashicorp/hcl/v2/spec.md
vendor/github.com/zclconf/go-cty/cty/convert/conversion.go
vendor/github.com/zclconf/go-cty/cty/convert/conversion_collection.go
vendor/github.com/zclconf/go-cty/cty/function/function.go
vendor/github.com/zclconf/go-cty/cty/function/stdlib/collection.go
vendor/github.com/zclconf/go-cty/cty/walk.go
vendor/modules.txt

full diff: https://github.com/hashicorp/hcl/compare/v2.20.1...v2.23.0
full diff: https://github.com/zclconf/go-cty/compare/v1.14.4...v1.16.0
Some non-breaking changes in `convert` function:
* https://github.com/zclconf/go-cty/pull/194
* https://github.com/zclconf/go-cty/pull/198

vendor: update hcl dependencies

---

commands/history/inspect.go
go.mod

For failed builds, show source with error location and last logs for vertex that caused the error. When debug mode is on, stacktrace is printed.
```
docker buildx history inspect m38a1hxgttgm2qcyrjs14yf3j                                                           !10057
Context:	.
Dockerfile:	Dockerfile
Started:	2025-01-17 04:48:42
Duration:	4.1s
Error:		Unknown process "/bin/sh -c apk add foo" did not complete successfully: exit code: 1
Build Steps:	8/10 (0% cached)
Dockerfile:4
2 |     copy Dockerfile .
3 |     run apk add git
4 | >>> run apk add foo
5 |     run apk add vim
6 |     copy Dockerfile d2
=> [4/6] RUN apk add foo:
ERROR: unable to select packages:
foo (no such package):
required by: world[foo]
Enable --debug to see stack traces for …
```

history: add error details to history inspect command

---

go.mod
go.sum
vendor/modules.txt

* backport of https://github.com/docker/buildx/pull/2932

[v0.20 backport] vendor: update buildkit to v0.19.0

---

util/buildflags/attests.go
util/buildflags/attests_test.go
util/buildflags/cache_test.go
util/buildflags/secrets.go
util/buildflags/secrets_test.go
util/buildflags/ssh.go
util/buildflags/ssh_test.go

`MarshalJSON` would not include the extra attributes because it iterated over the target map rather than the source map.
Also fixes JSON unmarshaling for SSH and secrets. The intention was to
unmarshal into the struct, but `UnmarshalText` takes priority over the
default struct unmarshaling so it didn't work as intended.
Tests have been added for all marshaling and unmarshaling methods.
Fixes #2936.

buildflags: marshal attestations into json with extra attributes correctly

---

util/buildflags/attests.go
util/buildflags/attests_test.go
util/buildflags/cache_test.go
util/buildflags/secrets.go
util/buildflags/secrets_test.go
util/buildflags/ssh.go
util/buildflags/ssh_test.go

backport of:
* https://github.com/docker/buildx/pull/2937

[v0.20] v0.20.1 cherry-picks

---

docs/bake-reference.md
docs/reference/buildx_bake.md

- **docs(bake): improve docs on "call" and "description" in bake file**
- **docs: add docs for bake --allow**

docs: bake v0.19 entitlements

---

cmd/buildx/main.go

Before this patch, both "usage" and shell-completion scripts would preserve
the path of the invoked command, which was especially problematic for the
completion-scripts, because Cobra's completion depends on Command.Name()
for this (see [1], [2]);
```bash
./bin/build/buildx --help | head -n 5
Extended build capabilities with BuildKit
Usage:
./bin/build/buildx
./bin/build/buildx [command]
./bin/build/buildx completion bash | head -n 3
__./bin/build/buildx_debug()
```
This would also be problematic if the path contained a space, for example;
```bash
ln -s $(pwd)/bin/build $(pwd)/bin/Program\ Files
./bin/Program\ Files/buildx completion bash | head -n 3
__./bin/Program_debug()
```
With this patch, the path is stripped to prevent this issue;
```bash
make
./bin/build/buildx --help | head -n 5 …
```

fix: strip path from usage output and shell-completion scripts

---

driver/docker-container/driver.go

It's a wrapper around errdefs.IsNotFound, which is already used, so we can skip the wrapper.
https://github.com/docker/buildx/blob/934841f3292a158c8807306c13b31b52d1b065b5/vendor/github.com/docker/docker/client/errors.go#L42-L46

driver/docker-container: remove uses of dockerclient.IsErrNotFound

---

bake/hcl_test.go
go.mod
hack/dockerfiles/lint.Dockerfile
util/buildflags/attests_cty.go
util/buildflags/cache_cty.go
util/buildflags/export_cty.go
util/buildflags/secrets_cty.go
util/buildflags/ssh_cty.go
util/buildflags/utils.go

Update the buildflags cty code to handle unknown values. When hcl decodes a value with an invalid variable name, it appends a diagnostic for the error and then returns an unknown value so it can continue processing the file and finding more errors.
The iteration code has now been changed to use a rangefunc from go 1.23 and it skips empty or unknown values. Empty values are valid when they are skipped and unknown values will have a diagnostic for itself.
Fixes #2960.

buildflags: handle unknown values from cty

---

commands/bake.go

When ran with `rawjson` progress mode, client only expect output to contain json messages. warning about missing `--allow` should then be skipped.

don't warn user about missing --allows when running with progress=rawjson

---

commands/ls.go

fixes #2969 
JSON format for `ls` command without Go template (`--format json`) should not set nodes in formatter context.

ls: fix duplicated builders for json format

---

.github/workflows/build.yml

relates to https://github.com/docker/buildx/pull/2904#issuecomment-2648101032

ci: install latest vagrant

---

go.mod
util/buildflags/attests_cty.go
util/buildflags/cache_cty.go
util/buildflags/export_cty.go
util/buildflags/secrets_cty.go
util/buildflags/ssh_cty.go
util/buildflags/utils.go

- supersedes / closes https://github.com/docker/buildx/pull/2977
Reverts the usage of rangefunc and attempts to keep the foundation of it in for when we move to go 1.23. We have downstream dependencies that aren't ready to move to go 1.23. We can likely move after go 1.24 is released.
Related to https://github.com/docker/buildx/pull/2965#discussion_r1949182858.

buildflags: make work on go 1.22 by reverting rangefunc usage

---

commands/history/ls.go
go.mod

This is some kind of `goimports` bug that went unnoticed.
ref https://github.com/compose-spec/compose-go/issues/735

remove import of x/exp

---

util/progress/printer.go

Current progress writer has a logic of pausing/unpausing the printer and internally recreating internal channels.
This conflicts with a change that added sync.Once to Wait to allow it being called multiple times without erroring.
In debug shell this could mean that new progress printer showed up in debug shell because it was not closed.
cc097db675b439e99d0ebb7e524e16ba22f92a6f

progress: fix race on pausing progress on debug shell

---

util/buildflags/cache.go

After testing latest RC, gha cache backend is always disabled when cache service v2 is detected. We forgot to check if `url_v2` is set in https://github.com/docker/buildx/pull/2983.
Also fixes gha cache url handling to always set both `url` and `url_v2` if possible to match fallback of github actions tookit.

cache: enable gha cache backend if cache service v2 detected

---

bake/bake.go
bake/bake_test.go
bake/entitlements.go
bake/entitlements_test.go
build/build.go
build/opt.go
commands/build.go
docs/reference/buildx_build.md
docs/reference/buildx_debug_build.md
go.mod
go.sum
util/buildflags/entitlements.go
vendor/github.com/moby/buildkit/client/solve.go
vendor/github.com/moby/buildkit/cmd/buildkitd/config/config.go
vendor/github.com/moby/buildkit/util/entitlements/entitlements.go
vendor/modules.txt

Buildx side of https://github.com/moby/buildkit/pull/5742
Allow access to CDI Devices in Buildkit v0.20.0+ for devices that are not automatically allowed to be used by everyone in BuildKit configuration.
```
--allow device grants access to any device.
--allow device=kind|name grants access to specific device.
--allow device=kind|name,alias=kind|name allows mapping kind to a specific device or one device to another. Alias is the name requested by the build and device is the actual device that is being enabled.
```

support for device entitlement in build and bake

---

bake/bake.go
bake/bake_test.go
bake/entitlements.go
bake/entitlements_test.go
build/build.go
build/opt.go
commands/build.go
docs/reference/buildx_build.md
docs/reference/buildx_debug_build.md
go.mod
go.sum
util/buildflags/cache.go
util/buildflags/entitlements.go
util/progress/printer.go
vendor/github.com/moby/buildkit/client/solve.go
vendor/github.com/moby/buildkit/cmd/buildkitd/config/config.go
vendor/github.com/moby/buildkit/util/entitlements/entitlements.go
vendor/modules.txt

* https://github.com/docker/buildx/pull/3003
* https://github.com/docker/buildx/pull/3001
* https://github.com/docker/buildx/pull/2994

[v0.21] cherry-picks 0.21.0-rc3

---

.github/workflows/build.yml
Dockerfile

closes #3009
Also adds alt for previous Docker 27 release.

Dockerfile: update to docker v28.0.0

---

.github/workflows/build.yml
hack/Vagrantfile.freebsd
hack/Vagrantfile.openbsd

To be consistent with go version used in our workflows.

ci: infer go version from workflow for bsd tests

---

bake/bake.go
bake/bake_test.go
docs/reference/buildx_bake.md

Annotations were not merged correctly. The overrides in `ArrValue` would be merged, but the section of code setting them from the command line did not include `annotations` in the list of available attributes so the command line option was completely discarded.
Fixes https://github.com/docker/buildx/issues/2989.

bake: allow annotations to be set on the command line

---

tests/bake.go
util/buildflags/cache.go

Broken in 11c84973ef104e48eb88a41b5b23d6a559efe868. The section to skip
an empty input was accidentally removed when some code was refactored to
fix a separate issue.
This skips empty cache entries which allows disabling the `cache-from` and
`cache-to` entries from the command line overrides.
Fixes https://github.com/docker/buildx/issues/3020.

buildflags: skip empty cache entries when parsing

---

build/build.go
driver/docker-container/driver.go
driver/docker/driver.go
driver/features.go
driver/kubernetes/driver.go
driver/remote/driver.go

In this mode buildkit can push directly so pushing manually with docker would result in pushing image twice.

avoid double pushing with docker driver with containerd

---

util/buildflags/secrets.go
util/buildflags/secrets_test.go
util/buildflags/ssh.go
util/buildflags/ssh_test.go

* follow-up https://github.com/docker/buildx/pull/3031#discussion_r1975283999
```hcl
secret = [
"id=FOO,env=FOO",
"id=FOO,env=BAR",
"id=BAR,env=BAZ"
]
}
```
Currently:
```
#1 [internal] load local bake definitions
#1 reading docker-bake.hcl 103B / 103B done
#1 DONE 0.0s
{
"group": {
"default": {
"targets": [
"default"
]
}
},
"target": {
"default": {
"secret": [
{
"id": "FOO",
"env": "FOO"
},
{
"id": "FOO",
"env": "BAR"
},
{
"id": "BAR",
"env": "BAZ"
}
]
}
}
}
```
With this change:
```
#1 [internal] load local bake definitions
#1 reading docker-bake.hcl 103B / 103B done
#1 DONE 0.0s
{
"group": {
"default": {
"targets": [
"default"
]
}
},
"target": {
"default": { …
```

correctly remove duplicated secrets and ssh keys

---

.github/workflows/e2e.yml

relates to https://github.com/docker/buildx/pull/3040#issuecomment-2698312251

ci: bump to ubuntu-24.04

---

commands/history/inspect.go

Allows specifying ref as `^offset` for `buildx history inspect` (default is equivalent to `^0`). Same format was already supported for `history trace`.

history: allow index based inspect of builds

---

commands/history/inspect.go
commands/history/inspect_attachment.go
commands/history/logs.go
commands/history/ls.go
commands/history/open.go
commands/history/trace.go
commands/history/utils.go

Some commands (logs/open) were still missing offset handling. Now all commands use the same reference parsing/sort.

history: generalize query loading

---

.github/workflows/build.yml

relates to https://github.com/docker/buildx/actions/runs/13643604134/job/38138677210
```
System.IO.IOException: No space left on device : '/home/runner/runners/2.322.0/_diag/Worker_20250304-005208-utc.log'
at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.Diagnostics.TextWriterTraceListener.Flush()
at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
at …
```

ci: fix faulty bin-image job

---

driver/docker-container/driver.go
driver/docker-container/factory.go

With CDI support added in BuildKit https://github.com/moby/buildkit/pull/4056, we need to request GPUs when creating a container builder.
This is necessary on WSL for Nvidia GPUs because there is no linux drivers available that we could install in BuildKit container during `OnDemand` setup. Mounting `/usr/lib/wsl` works https://github.com/docker/buildx/compare/master...crazy-max:buildx:driver-ctn-mount-wsl-lib?expand=1 but this is not desired and could be error prone if a remote context/builder is used. So instead we can make a device request when creating the container builder.
Can be tested by creating a BuildKit container with ubuntu base:
```
$ EXPORT_BASE=ubuntu PLATFORMS=linux/amd64,linux/arm64 ./hack/images ubuntu crazymax/buildkit push
```
You can use `crazymax/buildkit:ubuntu` …

driver: request gpu when creating container builder

---

commands/bake.go
commands/build.go
localstate/localstate.go
localstate/localstate_test.go
localstate/migrate.go
util/tracing/trace.go

[v0.21] cherry-picks for v0.21.3

---

.golangci.yml

This is not needed. One from `go.mod` should be the minimal supported version.

don't set go version in golangci-lint config

---

bake/compose.go
bake/compose_test.go

fixes https://github.com/docker/buildx/issues/3074
The result of one target as a build context of another is supported with bake hcl/json definitions using `target:` prefix: https://docs.docker.com/build/bake/contexts/#using-a-target-as-a-build-context
But not directly with compose syntax where the target is defined as service using `service:` prefix: https://docs.docker.com/reference/compose-file/build/#additional_contexts

bake: support compose service as build context

---

commands/history/export.go
commands/history/root.go
docs/reference/buildx_history.md
docs/reference/buildx_history_export.md
util/desktop/bundle/content.go
util/desktop/bundle/export.go
util/desktop/bundle/trace.go

part of https://github.com/docker/buildx/issues/2711
Allow builds to be exported into .dockerbuild bundles that can be shared and imported into Docker Desktop.

history: add export command

---

bake/compose.go
bake/compose_test.go

fix #3086
Another example of `x-bake` field becoming native field but implemented via JSON conversion or API wrapper in compose instead of native support in `bake`.

bake: fix platforms field in compose yaml

---

build/git_test.go
tests/bake.go
tests/build.go
util/gitutil/credentials_test.go
util/gitutil/gittestutil/testutil.go
util/gitutil/gittestutil/testutilserve.go
util/gitutil/gitutil.go
util/gitutil/gitutil_test.go

These utilities should not be included in the main build.
This only has a minimal 2.5KB binary size difference atm as there is still import to "testing" via containerd libs atm https://github.com/containerd/containerd/pull/11666 . Removing that one releases more.

avoid import to testing helpers outside of tests

---

bake/bake.go
tests/bake.go

fixes https://github.com/docker/buildx/issues/2613
The interpolation and directive introductions are escaped by doubling their leading characters. The `${` sequence is escaped as `$${` and the `%{` sequence is escaped as `%%{`.
When the definition is parsed, the escape sequence is removed but we need to keep it as we expect a valid input when printing the definition with `--print`.

bake: keep escaped interpolation in print output

---

build/build.go

fix #3117
Avoiding creating temp dir for stdin can be done in a follow-up.

build: make sure defers always run in the end of the build

---

bake/bake.go
bake/bake_test.go

`path.IsAbs` assumes Unix paths, prefer filepath so an absolute windows paths is well identified
fixes https://github.com/docker/compose/issues/12669

use filepath.IsAbs to support windows paths

---

go.mod
go.sum
vendor/github.com/containerd/containerd/v2/core/remotes/docker/pusher.go
vendor/github.com/containerd/containerd/v2/defaults/defaults_snapshotter_linux.go
vendor/github.com/containerd/containerd/v2/defaults/defaults_snapshotter_unix.go
vendor/github.com/containerd/containerd/v2/version/version.go
vendor/github.com/docker/docker/api/types/registry/registry.go
vendor/golang.org/x/oauth2/README.md
vendor/golang.org/x/oauth2/oauth2.go
vendor/golang.org/x/oauth2/pkce.go
vendor/golang.org/x/oauth2/token.go
vendor/modules.txt

notable changes
- fixes CVE-2025-22868
- oauth2.go: use a more straightforward return value
- oauth2: Deep copy context client in NewClient
- jws: improve fix for CVE-2025-22868
full diff: https://github.com/golang/oauth2/compare/v0.23.0...v0.29.0
full diff: https://github.com/containerd/containerd/compare/v2.0.4...v2.0.5
diff:  https://github.com/docker/docker/compare/v28.1.0...v28.1.1
no changes in vendored code
diff:  https://github.com/docker/cli/compare/v28.1.0...v28.1.1

vendor: github.com/docker/docker, docker/cli v28.1.1, containerd v2.0.5

---

go.mod
util/dockerutil/api.go

This allows to correlate operations triggered by a build (e.g.
a client-side pull) with the build that generated them.
Signed-off-by: Alberto Garcia Hierro <damaso.hierro@docker.com>

chore(dockerutil): propagate OTEL context to Docker daemon

---

.github/workflows/build.yml

relates to https://github.com/docker/actions-toolkit/pull/677#issuecomment-2826750069
Switch from git context to path context for bin-image job to fix buildx version. We can get back to git context when https://github.com/moby/buildkit/pull/5903 is released and necessary changes made in actions-toolkit.

ci: fix bin-image job

---

build/build.go
build/opt.go
tests/build.go

Prior to this change, the following command emits the wrong image ID when buildx uses the "docker-container" driver and Docker is configured with the containerd-snapshotter.
```
$ docker buildx build --load --iidfile=img.txt
$ docker run --rm "$(cat img.txt)" echo hello
docker: Error response from daemon: No such image: sha256:4ac37e81e00f242010e42f3251094e47de6100e01d25e9bd0feac6b8906976df. See 'docker run --help'.
```
The problem is that buildx is outputing the incorrect image ID in this scenario (it's outputing the container image config digest, instead of the container image digest used by the containerd-snapshotter).
This commit fixes this. See https://github.com/moby/moby/issues/45458.

Output correct image ID when using Docker with the containerd-snapshotter

---

docs/reference/buildx_history.md
docs/reference/buildx_history_export.md
docs/reference/buildx_history_import.md
docs/reference/buildx_history_inspect.md
docs/reference/buildx_history_inspect_attachment.md
docs/reference/buildx_history_logs.md
docs/reference/buildx_history_ls.md
docs/reference/buildx_history_open.md
docs/reference/buildx_history_rm.md
docs/reference/buildx_history_trace.md

- Adds descriptions and examples for buildx history commands
- Need a review on examples
@crazy-max to review

docs: add descriptions and examples for buildx history commands

---

commands/bake.go

fix nil dereference in this definition
```
target foo {
call = ""
}
```

bake: fix nil deference on empty call definition

---

bake/hcl_test.go
bake/hclparser/hclparser.go

Resolves #3160 and likely replaces #3161
In https://github.com/docker/buildx/issues/3160#issuecomment-2840204139 it was suggested that prior to allowing variable lists to be overridden via environment, proper typing capabilities should be implemented (and used).  This implements that typing, which results in the actual override code being superior to #3161 in every way, but touches more code.
This allows (but does not require) variables to have explicit types, similar to Terraform variables.  It uses HCL's `typeexpr` extension for the specification. For conversion of overrides to complex types (when explicit typing is provided), HCL's native JSON-based unmarshalling is used.
Typing is independent of any default value, but if a default is provided, it will be validated.  Similarly, if an …

Allow variables to be explicitly typed (and enforced)

---

commands/ls.go

fixes #3175
While lsBuilder has a field called Current that gets lost because the embedded struct implements custom MarshalJSON method.
This was the best workaround hack I could come up with. Didn't know about this behavior, but here is the sample case https://go.dev/play/p/XH8oRG_wGEU

ls: make sure current builder is available in JSON output

---

docs/bake-reference.md

This documents the variable typing introduced in #3167.

Add variable typing to reference docs

---

bake/hcl_test.go
bake/hclparser/hclparser.go
docs/bake-reference.md
go.mod
go.sum
vendor/modules.txt

backport of:
* https://github.com/docker/buildx/pull/3198
* https://github.com/docker/buildx/pull/3189
* https://github.com/docker/buildx/pull/3199

[v0.24] cherry-picks for v0.24.0

---

bake/hclparser/hclparser.go
commands/bake.go
docs/reference/buildx_bake.md
tests/bake.go

If a type was explicitly provided, it will be displayed in the variable listing. Inferred type names are not displayed, as they likely would not match the user's intent.
Previously only `string` and `bool` default values were displayed in the listing.  All default values, regardless of type, are now displayed.
Fixes #3202

Show types during variable list operation

---

docs/reference/buildx_build.md

Restructure of the examples for the build context command and remove duplicated information.

docs: restructure examples for context

---

hack/dockerfiles/lint.Dockerfile

Something has changed in golang or alpine requiring gold linker by default. In future this could be updated to clang/lld instead, eg. by just calling xx.

lint: fix linter error on arm64

---

bake/bake.go
bake/bake_test.go
bake/compose.go
bake/compose_test.go
docs/bake-reference.md
docs/reference/buildx_bake.md
tests/bake.go

fixes https://github.com/docker/buildx/issues/494

bake: extra-hosts support

---

docker-bake.hcl
hack/dockerfiles/lint.Dockerfile

Atm I was invoking `modernize -fix ./...` to fix issues reported by lint-gopls but it doesn't fix everything. Using our sandbox with linux container seems to do the trick.

hack: modernize-fix bake target

---

bake/compose.go
bake/compose_test.go
build/utils.go
build/utils_test.go
tests/bake.go
tests/build.go

follow-up
* https://github.com/docker/buildx/pull/3234
* https://github.com/docker/compose/pull/12935
Adds multiple IPs support for extra hosts value using `,` separator for Bake.
```hcl
extra-hosts = {
myhost = "1.2.3.4"
myhostmulti = "162.242.195.81,162.242.195.82"
}
}
```
```dockerfile
FROM busybox
RUN cat /etc/hosts
```
```
$ docker buildx bake
...
#7 [2/5] RUN cat /etc/hosts
#7 0.243 127.0.0.1      localhost buildkitsandbox
#7 0.243 ::1    localhost ip6-localhost ip6-loopback
#7 0.243 1.2.3.4        myhost
#7 0.243 162.242.195.81 myhostmulti
#7 0.243 162.242.195.82 myhostmulti
#7 DONE 0.3s
```

bake: multi ips support for extra hosts

---

driver/kubernetes/factory.go
driver/kubernetes/manifest/manifest.go

Depending on the size of the layers, it can increase build speed by a lot.
our use case is an docker buildx on a c7i.4xlarge. For a big COPY of about 1GB, we gained 1min of build time!

driver kubernetes: allow to work in a Memory mount to speed up things

---

docs/reference/buildx_history_inspect_attachment.md

Some types were missing in the docs and provenance output was not correct.

docs: fix history inspect attachment examples

---

commands/history/inspect_attachment.go
docs/reference/buildx_history_inspect_attachment.md

follow-up https://github.com/docker/buildx/pull/3258#discussion_r2160905234
Ref should not be required.
Before:
```
$ docker buildx history inspect attachment --type provenance
ERROR: accepts between 1 and 2 arg(s), received 0
```
After:
```
$ docker buildx history inspect attachment --type provenance
{
"builder": {
"id": ""
},
"buildType": "https://mobyproject.org/buildkit@v1",
"materials": [
{
"uri": "pkg:docker/docker/dockerfile@1",
"digest": {
"sha256": "9857836c9ee4268391bb5b09f9f157f3c91bb15821bb77969642813b0d00518d"
}
},
{
"uri": "pkg:docker/alpine@3.21?platform=linux%2Famd64",
"digest": {
"sha256": "a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c"
}
},
{
"uri": "pkg:docker/golang@1.24-alpine3.21?platform=linux%2Famd64",
"digest": {
"sha256": …
```

history: fix required args for inspect attachment command

---

bake/compose.go
bake/compose_test.go

fixes https://github.com/docker/compose/issues/12947

compose: ignore dotenv that is a directory

---

build/build.go
dap/adapter.go
dap/handler.go
dap/server.go
dap/thread.go
monitor/monitor.go

It is now possible to send next and continue as separate signals. When
executing a build, the debug adapter will divide the LLB graph into
regions. Each region corresponds to an uninterrupted chain of
instructions. It will also record which regions depend on which other
ones.
This determines the execution order and it also determines what the
stack traces look like.
When continue is used, we will attempt to evaluate the last leaf node
(the head). If we push next, we will determine which digest would be the
next one to be processed.
In the future, this will be used to also support breakpoints.

dap: add stack traces with next and continue functionality

---

commands/history/export.go
commands/history/inspect.go
commands/history/inspect_attachment.go
commands/history/logs.go
commands/history/ls.go
commands/history/open.go
commands/history/rm.go
commands/history/trace.go
commands/history/utils.go
tests/history.go

fixes #3296 
Before:
```
$ docker buildx --builder builder history ls
ERROR: Error response from daemon: container 82f708fa6dfc1935f56ea3f97c57872f47b24774d182928c3560a21187a2d869 is not running
```
After:
```
$ docker buildx --builder builder history ls
#1 [internal] booting buildkit
#1 starting container buildx_buildkit_builder0
#1 starting container buildx_buildkit_builder0 0.9s done
#1 DONE 0.9s
BUILD ID                    NAME                                   STATUS      CREATED AT       DURATION   
1i4j7lqd7egb2s27xkqlyx83k   buildx                                 Error       16 seconds ago   3.6s       Open
```

history: bootstrap builder

---

docs/reference/buildx_build.md

follow-up
* https://github.com/moby/buildkit/issues/6071
* https://github.com/docker/buildx/issues/3303

docs: update links and add missing type for build cache exporters

---

commands/root.go

fixes https://github.com/docker/buildx/issues/2495
Use [`additionalHelp` annotation](https://github.com/docker/cli/blob/84038691220e7ba3329a177e4e3357b4ee0e3a52/cli/cobra.go#L229) to set Buildx experimental command hint to avoid duplicated commands description in the output.
Before:
```
$ docker buildx
Extended build capabilities with BuildKit
Usage:  docker buildx [OPTIONS] COMMAND
Extended build capabilities with BuildKit
Options:
--builder string   Override the configured builder instance
-D, --debug            Enable debug logging
Management Commands:
history     Commands to work on build records
imagetools  Commands to work on images in registry
Commands:
bake        Build from a file
build       Start a build
create      Create a new builder instance
dial-stdio  Proxy current stdio …
```

cmd: fix duplicated commands description

---

dap/adapter.go
dap/thread.go

Implement the first iteration of breakpoints. When a breakpoint is set,
it starts unverified. When a thread begins evaluation, it tries to see
if a breakpoint corresponds to one of the parsed instructions and will
verify it.
Breakpoints work when continue is used.
At the current moment, setting breakpoints while a thread is currently
running doesn't work. Breakpoints are rechecked each time execution is
about to restart.

dap: implement first pass at breakpoints

---

dap/adapter.go
dap/handler.go
dap/server.go
dap/thread.go
dap/variables.go

Implement variable references to inspect the state of a stack frame.
Variable reference ids are composed of two sections. A thread mask that
is the first 8 bytes and the remainder is an increasing number that gets
reset each time a thread is resumed. This allows the adapter to know
which thread to delegate the variables request to and allows the
variable references to still remain confined to each thread. An int32 is
used for this because variable references need to be in the range of
(0, 2^32).
At the moment, only the platform variables and some of the exec
operations for an operation. These are labeled as "arguments" to the
stack frame.

dap: implement variable references

---

dap/adapter.go
dap/handler.go
dap/server.go

Step into and step out are required by the UI for DAP. We don't have a
way to implement these in a logical manner but they need to exist. We'll
discuss in further iterations how these might differ from next and
continue, but for now, we just need some implementation for the UI.

dap: alias step into to next and step out to continue

---

bake/compose.go

close https://github.com/docker/compose/issues/13070

do not assume input is a compose file on .env parsing error

---

commands/history/utils.go
tests/history.go

fixes https://github.com/docker/buildx/issues/3321

history: use built-in build-arg to override the build name

---

dap/adapter.go
dap/eval.go
dap/thread.go
dap/variables.go

Change how breakpoints and stepping works. These now work more how you
would expect another programming language to work. Breakpoints happen
before the step has been invoked rather than after which means you can
inspect the state before the command runs.
This has the advantage of being more intuitive for someone familiar with
other debuggers. The negative is that you can't run to after a certain
step as easily as you could before. Instead, you would run to that stage
and then use next to go to the step directly afterwards.
Step in and out also now have different behaviors. When a step has
multiple inputs, the inputs of non-zero index are considered like
"function calls". The most common cause of this is to use `COPY --from`
or a bind mount. Stepping into these will cause it to jump to the …

dap: refactor how step in/step out works

---

bake/bake.go
bake/bake_test.go

When trying to build a bake target with an empty Dockerfile:
```hcl
dockerfile = ""
}
```
```
#1 [internal] load local bake definitions
#1 reading docker-bake.hcl 39B / 39B done
#1 DONE 0.0s
{
"group": {
"default": {
"targets": [
"default"
]
}
},
"target": {
"default": {
"dockerfile": ""
}
}
}
```
```
$ docker buildx bake
#0 building with "default" instance using docker driver
#1 [internal] load local bake definitions
#1 reading docker-bake.hcl 39B / 39B done
#1 DONE 0.0s
#2 [internal] load build definition from .
#2 transferring dockerfile: 132B done
#2 DONE 0.0s
ERROR: failed to solve: failed to read dockerfile: read /var/lib/docker/tmp/buildkit-mount205981038: is a directory
```
It doesn't set the default but tries to …

bake: fix dockerfile default if empty

---

docs/reference/buildx_bake.md

https://github.com/docker/bake-action/issues/337#issuecomment-3135798103

docs: missing call as override field

---

build/opt.go

Handle the `BUILDKIT_SYNTAX` build argument directly in buildx instead of relying on the `dockerfile.v0` frontend to perform forwarding.
Derived from #3157 preserving the initial commit from @wnonnemaker and making changes requested by @tonistiigi.

Add BUILDKIT_SYNTAX option handling

---

go.mod

fixes https://github.com/docker/buildx/issues/3221
Since Go 1.23, reparse points are not read anymore: 
> On Windows, the mode bits reported by [Lstat](https://go.dev/pkg/os#Lstat) and [Stat](https://go.dev/pkg/os#Stat) for reparse points changed. Mount points no longer have [ModeSymlink](https://go.dev/pkg/os#ModeSymlink) set, and reparse points that are not symlinks, Unix sockets, or dedup files now always have [ModeIrregular](https://go.dev/pkg/os#ModeIrregular) set. This behavior is controlled by the winsymlink setting. For Go 1.23, it defaults to winsymlink=1. Previous versions default to winsymlink=0.
> (from https://go.dev/doc/go1.23#ospkgos)
> 
> ...
> 
> On Windows, [EvalSymlinks](https://go.dev/pkg/path/filepath#EvalSymlinks) no longer evaluates mount points, which was a source …

restore junctions to have os.ModeSymlink flag set on Windows

---

bake/bake.go
build/build.go
build/opt.go
commands/build.go
tests/build.go

fixes https://github.com/docker/buildx/issues/2605

build: fail early if trying to export index annotations with moby exporter

---

commands/prune.go
docs/reference/buildx_du.md
docs/reference/buildx_prune.md

follow-up:
* https://github.com/docker/buildx/issues/1065#issuecomment-3102936155
* https://github.com/docker/buildx/issues/3367#issue-3321034339
* https://github.com/docker/buildx/issues/931
fixes https://github.com/docker/buildx/issues/1922
Currently we have filters for the following keys: https://github.com/moby/buildkit/blob/3d43066f2e814d4d10383ba871256245edf08a25/cache/manager.go#L1641-L1659
Key `type` can be one of: https://github.com/moby/buildkit/blob/3d43066f2e814d4d10383ba871256245edf08a25/client/diskusage.go#L81-L88
We also have the `until` key that is used on client side to set `KeepDuration` for prune info request: https://github.com/docker/buildx/blob/3f4bf829d8c5b92a8f670609417d9aa4c0b6be98/commands/prune.go#L190-L243
We are using containerd module to parse filters: …

docs: list available filters for du and prune commands

---

build/opt.go
commands/build.go

requires https://github.com/moby/buildkit/pull/6183

git querystring frontend capability detection

---

build/opt.go
commands/build.go
go.mod
go.sum
tests/build.go
tests/integration_test.go
vendor/modules.txt

backport of:
* https://github.com/docker/buildx/pull/3401
* https://github.com/docker/buildx/pull/3398
* https://github.com/docker/buildx/pull/3399

[v0.28] cherry-picks for v0.28.0

---

build/build.go
build/utils.go
builder/builder.go
commands/history/inspect.go
commands/inspect.go
go.mod
tests/create.go
tests/inspect.go
tests/integration.go
tests/ls.go
tests/workers/docker.go
util/buildflags/export.go

relates to https://github.com/docker/buildx/pull/3318#pullrequestreview-3020426158
similar to https://github.com/moby/buildkit/pull/6205
`modernize-fix` run output:
```
#22 0.472 + /gopls-analyzers/modernize -fix ./...
#22 18.12 modernize: modernize@github.com/docker/buildx/builder: ignoring alternative fix "Replace omitempty with omitzero (behavior change)"
#22 18.12 modernize: modernize@github.com/docker/buildx/commands/history: ignoring alternative fix "Replace omitempty with omitzero (behavior change)"
#22 18.12 modernize: modernize@github.com/docker/buildx/builder [github.com/docker/buildx/builder.test]: ignoring alternative fix "Replace omitempty with omitzero (behavior change)"
#22 18.15 + git status --porcelain
#22 18.15 + awk '/^ M/ {print $2}'
#22 18.20 + dirname build/build.go …
```

go.mod: bump to go 1.24

---

docs/bake-reference.md

adds https://github.com/docker/buildx/pull/2556#issuecomment-2958243837

docs: add variable 'description' attribute
